/*
 * Decompiled with CFR 0.152.
 */
import com.arenaofkings.packets.gameserver.PUB_GAME_CONNECTION_ESTABLISHED;
import com.arenaofkings.packets.gameserver.PUB_GAME_FOG_UPDATE;
import com.arenaofkings.packets.gameserver.PUB_GAME_INIT;
import com.arenaofkings.packets.gameserver.PUB_GAME_MESSAGE;
import com.arenaofkings.packets.gameserver.PUB_GAME_PING;
import com.arenaofkings.packets.gameserver.PUB_GAME_PING_RESPONSE;
import com.arenaofkings.packets.gameserver.PUB_GAME_SCOREBOARD_UPDATE;
import com.arenaofkings.packets.gameserver.PUB_GAME_SNAPSHOT;
import com.arenaofkings.packets.gameserver.PUB_GAME_STATUS_UPDATE;
import com.arenaofkings.packets.gameserver.PUB_MISC_PLAYER_TOKEN;
import com.arenaofkings.packets.gameserver.PUB_PLAY_READY;
import com.arenaofkings.packets.gameserver.data.Direction;
import com.arenaofkings.packets.gameserver.data.EffectList;
import com.arenaofkings.packets.gameserver.data.EnemyPlayerData;
import com.arenaofkings.packets.gameserver.data.FriendlyPlayerData;
import com.arenaofkings.packets.gameserver.data.GameStatus;
import com.arenaofkings.packets.gameserver.data.HitCircle;
import com.arenaofkings.packets.gameserver.data.Location;
import com.arenaofkings.packets.gameserver.data.LocationType;
import com.arenaofkings.packets.gameserver.data.PlayerAction;
import com.arenaofkings.packets.gameserver.data.ScoreboardItem;
import com.arenaofkings.packets.gameserver.data.ScoreboardUpdate;
import com.arenaofkings.packets.gameserver.data.Target;
import com.arenaofkings.packets.gameserver.data.updates.CollisionEvent;
import com.arenaofkings.packets.gameserver.data.updates.PlayerComboPointUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerCoordinateUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerDeathUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerDirectionChange;
import com.arenaofkings.packets.gameserver.data.updates.PlayerEffectAdd;
import com.arenaofkings.packets.gameserver.data.updates.PlayerEffectRemove;
import com.arenaofkings.packets.gameserver.data.updates.PlayerEffectUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerForcedPositionUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerGCDReset;
import com.arenaofkings.packets.gameserver.data.updates.PlayerHealthManaUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerInterrupted;
import com.arenaofkings.packets.gameserver.data.updates.PlayerMaxHealthUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerMovementActionUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerMovementPressEastUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerMovementPressNorthUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerMovementPressSouthUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerMovementPressWestUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerMovementReleaseEastUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerMovementReleaseNorthUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerSelfInterrupt;
import com.arenaofkings.packets.gameserver.data.updates.PlayerSnapshot;
import com.arenaofkings.packets.gameserver.data.updates.PlayerSpellDestroyedUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerTargetUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerUpdate;
import com.arenaofkings.packets.gameserver.data.updates.PlayerUpdateBundle;
import com.arenaofkings.packets.gameserver.data.updates.PlayerUpdateList;
import com.arenaofkings.packets.gameserver.data.updates.Snapshot;
import com.arenaofkings.packets.gameserver.data.updates.SpellBarState;
import com.arenaofkings.packets.gameserver.data.updates.SpellName;
import com.arenaofkings.packets.gameserver.data.updates.UpdatePacket;
import com.arenaofkings.packets.gameserver.data.updates.conveyed.Conveyorable;
import com.arenaofkings.packets.gameserver.data.updates.conveyed.PlayerActionUpdate;
import com.arenaofkings.packets.gameserver.data.updates.conveyed.PlayerPositionUpdate;
import com.arenaofkings.packets.gameserver.data.updates.items.TrinketUseRequest;
import com.arenaofkings.packets.gameserver.data.updates.items.TrinketUseUpdate;
import com.arenaofkings.packets.gameserver.data.updates.sct.SCT_Event;
import com.arenaofkings.packets.gameserver.data.updates.sct.SCT_FloatingFeedbackText;
import com.arenaofkings.packets.gameserver.data.updates.sct.SCT_PlayerHealthChange;
import com.arenaofkings.packets.gameserver.data.updates.sct.SCT_PlayerManaChange;
import com.arenaofkings.packets.gameserver.data.updates.spells.PlayerSpellCastStart;
import com.arenaofkings.packets.gameserver.data.updates.spells.PlayerSpellUpdate;
import com.arenaofkings.packets.gameserver.data.updates.spells.catalog.DynamicCoordinateSpellFinish;
import com.arenaofkings.packets.gameserver.data.updates.spells.catalog.DynamicPlayerSpellFinish;
import com.arenaofkings.packets.gameserver.data.updates.spells.catalog.DynamicPlayerSpellStart;
import com.arenaofkings.packets.gameserver.data.updates.spells.catalog.FixedCoordinateSpellFinish;
import com.arenaofkings.packets.gameserver.data.updates.spells.catalog.FixedCoordinateSpellStart;
import com.arenaofkings.packets.gameserver.data.updates.spells.catalog.FixedPlayerSpellFinish;
import com.arenaofkings.packets.gameserver.data.updates.spells.catalog.FixedPlayerSpellStart;
import com.arenaofkings.packets.gameserver.data.updates.spells.catalog.SpellClassification;
import com.arenaofkings.packets.gameserver.data.updates.spells.catalog.TargetedProjectileSpellFinish;
import com.arenaofkings.packets.gameserver.data.updates.spells.catalog.TargetedProjectileSpellStart;
import com.arenaofkings.packets.gameserver.requests.input.DIRECTION_CHANGE_REQUEST;
import com.arenaofkings.packets.gameserver.requests.input.ItemPickupRequest;
import com.arenaofkings.packets.gameserver.requests.input.ItemRemove;
import com.arenaofkings.packets.gameserver.requests.input.JAVA_16_GFX_CL$61892;
import com.arenaofkings.packets.gameserver.requests.input.MOVEMENT_UPDATE;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_FORCE_POSITION_REQUEST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_RELEASE_EAST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_RELEASE_NORTH;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_RELEASE_NORTH_EAST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_RELEASE_NORTH_WEST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_RELEASE_SOUTH;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_RELEASE_SOUTH_EAST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_RELEASE_SOUTH_WEST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_RELEASE_WEST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_REQUEST_EAST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_REQUEST_NORTH;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_REQUEST_NORTH_EAST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_REQUEST_NORTH_WEST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_REQUEST_SOUTH;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_REQUEST_SOUTH_EAST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_REQUEST_SOUTH_WEST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_REQUEST_WEST;
import com.arenaofkings.packets.gameserver.requests.input.MOVE_SPELL_REQUEST;
import com.arenaofkings.packets.gameserver.requests.input.SPELL_REQUEST;
import com.arenaofkings.packets.gameserver.requests.input.SpellRequest;
import com.arenaofkings.packets.gameserver.requests.input.TRINKET_REQUEST_0;
import com.arenaofkings.packets.gameserver.requests.input.TargetOfTargetRequest;
import com.arenaofkings.packets.gameserver.requests.input.TargetRequest;
import com.arenaofkings.packets.misc.ArenaName;
import com.arenaofkings.packets.misc.ArenaTeamData;
import com.arenaofkings.packets.misc.ArenaTeamMemberData;
import com.arenaofkings.packets.misc.CharacterClass;
import com.arenaofkings.packets.misc.GameType;
import com.arenaofkings.packets.misc.PlayerStatus;
import com.arenaofkings.packets.misc.Privilege;
import com.arenaofkings.packets.misc.PublicPacket;
import com.arenaofkings.packets.misc.items.ArmorRequirement;
import com.arenaofkings.packets.misc.items.ClassRequirement;
import com.arenaofkings.packets.misc.items.EquippableRequirement;
import com.arenaofkings.packets.misc.items.ItemArmorType;
import com.arenaofkings.packets.misc.items.ItemDBState;
import com.arenaofkings.packets.misc.items.ItemData;
import com.arenaofkings.packets.misc.items.ItemLocation;
import com.arenaofkings.packets.misc.items.ItemModData;
import com.arenaofkings.packets.misc.items.ItemRequirement;
import com.arenaofkings.packets.misc.items.ItemSlot;
import com.arenaofkings.packets.misc.items.LevelRequirement;
import com.arenaofkings.packets.misc.items.PlayerItemDropData;
import com.badlogic.gdx.utils.Array;
import com.esotericsoftware.kryo.Kryo;
import com.esotericsoftware.kryo.util.DefaultInstantiatorStrategy;
import java.util.ArrayList;
import java.util.List;
import org.objenesis.strategy.StdInstantiatorStrategy;

public class af {
    public static void a(Kryo kryo) {
        ((DefaultInstantiatorStrategy)kryo.getInstantiatorStrategy()).setFallbackInstantiatorStrategy(new StdInstantiatorStrategy());
        kryo.register(List.class);
        kryo.register(Object[].class);
        kryo.register(ArrayList.class);
        kryo.register(Array.class);
        kryo.register(PublicPacket.class);
        kryo.register(CharacterClass.class);
        kryo.register(GameStatus.class);
        kryo.register(SpellName.class);
        kryo.register(Direction.class);
        kryo.register(ArenaName.class);
        kryo.register(GameType.class);
        kryo.register(Privilege.class);
        kryo.register(PlayerStatus.class);
        kryo.register(SpellBarState.class);
        kryo.register(EffectList.class);
        kryo.register(LocationType.class);
        kryo.register(PlayerAction.class);
        kryo.register(ItemSlot.class);
        kryo.register(ItemLocation.class);
        kryo.register(ItemDBState.class);
        kryo.register(ItemArmorType.class);
        kryo.register(ItemRequirement.class);
        kryo.register(ArmorRequirement.class);
        kryo.register(ClassRequirement.class);
        kryo.register(LevelRequirement.class);
        kryo.register(EquippableRequirement.class);
        kryo.register(ItemModData.class);
        kryo.register(ItemData.class);
        kryo.register(PlayerItemDropData.class);
        kryo.register(PlayerItemDropData.class);
        kryo.register(FriendlyPlayerData.class);
        kryo.register(EnemyPlayerData.class);
        kryo.register(ArenaTeamMemberData.class);
        kryo.register(ArenaTeamData.class);
        kryo.register(HitCircle.class);
        kryo.register(Target.class);
        kryo.register(Conveyorable.class);
        kryo.register(PlayerActionUpdate.class);
        kryo.register(Location.class);
        kryo.register(ScoreboardItem.class);
        kryo.register(ScoreboardUpdate.class);
        kryo.register(UpdatePacket.class);
        kryo.register(PlayerPositionUpdate.class);
        kryo.register(TrinketUseRequest.class);
        kryo.register(TrinketUseUpdate.class);
        kryo.register(SCT_Event.class);
        kryo.register(SCT_FloatingFeedbackText.class);
        kryo.register(SCT_PlayerHealthChange.class);
        kryo.register(SCT_PlayerManaChange.class);
        kryo.register(SpellClassification.class);
        kryo.register(DynamicCoordinateSpellFinish.class);
        kryo.register(DynamicPlayerSpellFinish.class);
        kryo.register(DynamicPlayerSpellStart.class);
        kryo.register(FixedCoordinateSpellFinish.class);
        kryo.register(FixedCoordinateSpellStart.class);
        kryo.register(FixedPlayerSpellFinish.class);
        kryo.register(FixedPlayerSpellStart.class);
        kryo.register(TargetedProjectileSpellFinish.class);
        kryo.register(TargetedProjectileSpellStart.class);
        kryo.register(PlayerSpellCastStart.class);
        kryo.register(PlayerSpellUpdate.class);
        kryo.register(CollisionEvent.class);
        kryo.register(PlayerComboPointUpdate.class);
        kryo.register(PlayerCoordinateUpdate.class);
        kryo.register(PlayerDeathUpdate.class);
        kryo.register(PlayerDirectionChange.class);
        kryo.register(PlayerEffectAdd.class);
        kryo.register(PlayerEffectRemove.class);
        kryo.register(PlayerEffectUpdate.class);
        kryo.register(PlayerForcedPositionUpdate.class);
        kryo.register(PlayerGCDReset.class);
        kryo.register(PlayerHealthManaUpdate.class);
        kryo.register(PlayerInterrupted.class);
        kryo.register(PlayerMaxHealthUpdate.class);
        kryo.register(PlayerMovementActionUpdate.class);
        kryo.register(PlayerMovementPressEastUpdate.class);
        kryo.register(PlayerMovementPressNorthUpdate.class);
        kryo.register(PlayerMovementPressSouthUpdate.class);
        kryo.register(PlayerMovementPressWestUpdate.class);
        kryo.register(PlayerMovementReleaseEastUpdate.class);
        kryo.register(PlayerMovementReleaseNorthUpdate.class);
        kryo.register(PlayerSelfInterrupt.class);
        kryo.register(PlayerSpellDestroyedUpdate.class);
        kryo.register(PlayerTargetUpdate.class);
        kryo.register(PlayerSnapshot.class);
        kryo.register(PlayerUpdateList.class);
        kryo.register(PlayerUpdate.class);
        kryo.register(Snapshot.class);
        kryo.register(DIRECTION_CHANGE_REQUEST.class);
        kryo.register(ItemPickupRequest.class);
        kryo.register(ItemRemove.class);
        kryo.register(JAVA_16_GFX_CL$61892.class);
        kryo.register(MOVE_FORCE_POSITION_REQUEST.class);
        kryo.register(MOVE_RELEASE_EAST.class);
        kryo.register(MOVE_RELEASE_NORTH_EAST.class);
        kryo.register(MOVE_RELEASE_NORTH_WEST.class);
        kryo.register(MOVE_RELEASE_NORTH.class);
        kryo.register(MOVE_RELEASE_SOUTH_EAST.class);
        kryo.register(MOVE_RELEASE_SOUTH_WEST.class);
        kryo.register(MOVE_RELEASE_SOUTH.class);
        kryo.register(MOVE_RELEASE_WEST.class);
        kryo.register(MOVE_REQUEST_EAST.class);
        kryo.register(MOVE_REQUEST_NORTH_EAST.class);
        kryo.register(MOVE_REQUEST_NORTH_WEST.class);
        kryo.register(MOVE_REQUEST_NORTH.class);
        kryo.register(MOVE_REQUEST_SOUTH_EAST.class);
        kryo.register(MOVE_REQUEST_SOUTH_WEST.class);
        kryo.register(MOVE_REQUEST_SOUTH.class);
        kryo.register(MOVE_REQUEST_WEST.class);
        kryo.register(MOVE_SPELL_REQUEST.class);
        kryo.register(MOVEMENT_UPDATE.class);
        kryo.register(SPELL_REQUEST.class);
        kryo.register(SpellRequest.class);
        kryo.register(TargetOfTargetRequest.class);
        kryo.register(TargetRequest.class);
        kryo.register(TRINKET_REQUEST_0.class);
        kryo.register(PUB_GAME_CONNECTION_ESTABLISHED.class);
        kryo.register(PUB_GAME_FOG_UPDATE.class);
        kryo.register(PUB_GAME_INIT.class);
        kryo.register(PUB_GAME_MESSAGE.class);
        kryo.register(PUB_GAME_PING.class);
        kryo.register(PUB_GAME_PING_RESPONSE.class);
        kryo.register(PUB_GAME_SCOREBOARD_UPDATE.class);
        kryo.register(PUB_GAME_SNAPSHOT.class);
        kryo.register(PUB_GAME_STATUS_UPDATE.class);
        kryo.register(PUB_MISC_PLAYER_TOKEN.class);
        kryo.register(PUB_PLAY_READY.class);
        kryo.register(PlayerUpdateBundle.class);
    }
}

