/*
 * Decompiled with CFR 0.152.
 */
import com.badlogic.gdx.audio.Sound;
import com.badlogic.gdx.graphics.Texture;
import com.badlogic.gdx.graphics.g2d.TextureAtlas;
import com.badlogic.gdx.maps.tiled.TiledMap;
import com.badlogic.gdx.utils.Array;
import com.badlogic.gdx.utils.Disposable;

public final class ajw
extends Enum<ajw> {
    public static final /* enum */ ajw var_ajw_a;
    public static final /* enum */ ajw b;
    public static final /* enum */ ajw c;
    public static final /* enum */ ajw d;
    public static final /* enum */ ajw e;
    public static final /* enum */ ajw f;
    public static final /* enum */ ajw g;
    public static final /* enum */ ajw h;
    public static final /* enum */ ajw i;
    public static final /* enum */ ajw j;
    public static final /* enum */ ajw k;
    public static final /* enum */ ajw l;
    public static final /* enum */ ajw m;
    public static final /* enum */ ajw n;
    public static final /* enum */ ajw o;
    public static final /* enum */ ajw p;
    public static final /* enum */ ajw q;
    public static final /* enum */ ajw r;
    public static final /* enum */ ajw s;
    public static final /* enum */ ajw t;
    public static final /* enum */ ajw u;
    public static final /* enum */ ajw v;
    public static final /* enum */ ajw w;
    public static final /* enum */ ajw x;
    public static final /* enum */ ajw y;
    public static final /* enum */ ajw z;
    public static final /* enum */ ajw A;
    public static final /* enum */ ajw B;
    public static final /* enum */ ajw C;
    public static final /* enum */ ajw D;
    public static final /* enum */ ajw E;
    public static final /* enum */ ajw F;
    public static final /* enum */ ajw G;
    public static final /* enum */ ajw H;
    public static final /* enum */ ajw I;
    public static final /* enum */ ajw J;
    public static final /* enum */ ajw K;
    public static final /* enum */ ajw L;
    public static final /* enum */ ajw M;
    public static final /* enum */ ajw N;
    public static final /* enum */ ajw O;
    public static final /* enum */ ajw P;
    public static final /* enum */ ajw Q;
    public static final /* enum */ ajw R;
    public static final /* enum */ ajw S;
    public static final /* enum */ ajw T;
    public static final /* enum */ ajw U;
    public static final /* enum */ ajw V;
    public static final /* enum */ ajw W;
    public static final /* enum */ ajw X;
    public static final /* enum */ ajw Y;
    public static final /* enum */ ajw Z;
    public static final /* enum */ ajw aa;
    public static final /* enum */ ajw ab;
    public static final /* enum */ ajw ac;
    public static final /* enum */ ajw ad;
    public static final /* enum */ ajw ae;
    public static final /* enum */ ajw af;
    public static final /* enum */ ajw ag;
    public static final /* enum */ ajw ah;
    public static final /* enum */ ajw ai;
    public static final /* enum */ ajw aj;
    public static final /* enum */ ajw ak;
    public static final /* enum */ ajw al;
    public static final /* enum */ ajw am;
    public static final /* enum */ ajw an;
    public static final /* enum */ ajw ao;
    public static final /* enum */ ajw ap;
    public static final /* enum */ ajw aq;
    public static final /* enum */ ajw ar;
    public static final /* enum */ ajw as;
    public static final /* enum */ ajw at;
    public static final /* enum */ ajw au;
    public static final /* enum */ ajw av;
    public static final /* enum */ ajw aw;
    public static final /* enum */ ajw ax;
    public static final /* enum */ ajw ay;
    public static final /* enum */ ajw az;
    public static final /* enum */ ajw aA;
    public static final /* enum */ ajw aB;
    public static final /* enum */ ajw aC;
    public static final /* enum */ ajw aD;
    public static final /* enum */ ajw aE;
    public static final /* enum */ ajw aF;
    public static final /* enum */ ajw aG;
    public static final /* enum */ ajw aH;
    public static final /* enum */ ajw aI;
    public static final /* enum */ ajw aJ;
    public static final /* enum */ ajw aK;
    public static final /* enum */ ajw aL;
    public static final /* enum */ ajw aM;
    public static final /* enum */ ajw aN;
    public static final /* enum */ ajw aO;
    public static final /* enum */ ajw aP;
    public static final /* enum */ ajw aQ;
    public static final /* enum */ ajw aR;
    public static final /* enum */ ajw aS;
    public static final /* enum */ ajw aT;
    public static final /* enum */ ajw aU;
    public static final /* enum */ ajw aV;
    public static final /* enum */ ajw aW;
    public static final /* enum */ ajw aX;
    public static final /* enum */ ajw aY;
    public static final /* enum */ ajw aZ;
    public static final /* enum */ ajw ba;
    public static final /* enum */ ajw bb;
    public static final /* enum */ ajw bc;
    public static final /* enum */ ajw bd;
    public static final /* enum */ ajw be;
    public static final /* enum */ ajw bf;
    public static final /* enum */ ajw bg;
    public static final /* enum */ ajw bh;
    public static final /* enum */ ajw bi;
    public static final /* enum */ ajw bj;
    public static final /* enum */ ajw bk;
    public static final /* enum */ ajw bl;
    public static final /* enum */ ajw bm;
    public static final /* enum */ ajw bn;
    public static final /* enum */ ajw bo;
    public static final /* enum */ ajw bp;
    public static final /* enum */ ajw bq;
    public static final /* enum */ ajw br;
    public static final /* enum */ ajw bs;
    public static final /* enum */ ajw bt;
    public static final /* enum */ ajw bu;
    public static final /* enum */ ajw bv;
    public static final /* enum */ ajw bw;
    public static final /* enum */ ajw bx;
    public static final /* enum */ ajw by;
    public static final /* enum */ ajw bz;
    public static final /* enum */ ajw bA;
    public static final /* enum */ ajw bB;
    public static final /* enum */ ajw bC;
    public static final /* enum */ ajw bD;
    public static final /* enum */ ajw bE;
    public static final /* enum */ ajw bF;
    public static final /* enum */ ajw bG;
    public static final /* enum */ ajw bH;
    public static final /* enum */ ajw bI;
    public static final /* enum */ ajw bJ;
    public static final /* enum */ ajw bK;
    public static final /* enum */ ajw bL;
    public static final /* enum */ ajw bM;
    public static final /* enum */ ajw bN;
    public static final /* enum */ ajw bO;
    public static final /* enum */ ajw bP;
    public static final /* enum */ ajw bQ;
    public static final /* enum */ ajw bR;
    public static final /* enum */ ajw bS;
    public static final /* enum */ ajw bT;
    public static final /* enum */ ajw bU;
    public static final /* enum */ ajw bV;
    public static final /* enum */ ajw bW;
    public static final /* enum */ ajw bX;
    public static final /* enum */ ajw bY;
    public static final /* enum */ ajw bZ;
    public static final /* enum */ ajw ca;
    public static final /* enum */ ajw cb;
    public static final /* enum */ ajw cc;
    public static final /* enum */ ajw cd;
    public static final /* enum */ ajw ce;
    public static final /* enum */ ajw cf;
    public static final /* enum */ ajw cg;
    public static final /* enum */ ajw ch;
    public static final /* enum */ ajw ci;
    public static final /* enum */ ajw cj;
    public static final /* enum */ ajw ck;
    public static final /* enum */ ajw cl;
    public static final /* enum */ ajw cm;
    public static final /* enum */ ajw cn;
    public static final /* enum */ ajw co;
    public static final /* enum */ ajw cp;
    public static final /* enum */ ajw cq;
    public static final /* enum */ ajw cr;
    public static final /* enum */ ajw cs;
    public static final /* enum */ ajw ct;
    public static final /* enum */ ajw cu;
    public static final /* enum */ ajw cv;
    public static final /* enum */ ajw cw;
    public static final /* enum */ ajw cx;
    public static final /* enum */ ajw cy;
    public static final /* enum */ ajw cz;
    public static final /* enum */ ajw cA;
    public static final /* enum */ ajw cB;
    public static final /* enum */ ajw cC;
    public static final /* enum */ ajw cD;
    public static final /* enum */ ajw cE;
    public static final /* enum */ ajw cF;
    public static final /* enum */ ajw cG;
    public static final /* enum */ ajw cH;
    public static final /* enum */ ajw cI;
    public static final /* enum */ ajw cJ;
    public static final /* enum */ ajw cK;
    public static final /* enum */ ajw cL;
    public static final /* enum */ ajw cM;
    public static final /* enum */ ajw cN;
    public static final /* enum */ ajw cO;
    public static final /* enum */ ajw cP;
    public static final /* enum */ ajw cQ;
    public static final /* enum */ ajw cR;
    public static final /* enum */ ajw cS;
    public static final /* enum */ ajw cT;
    public static final /* enum */ ajw cU;
    public static final /* enum */ ajw cV;
    public static final /* enum */ ajw cW;
    public static final /* enum */ ajw cX;
    public static final /* enum */ ajw cY;
    public static final /* enum */ ajw cZ;
    public static final /* enum */ ajw da;
    public static final /* enum */ ajw db;
    public static final /* enum */ ajw dc;
    public static final /* enum */ ajw dd;
    public static final /* enum */ ajw de;
    public static final /* enum */ ajw df;
    public static final /* enum */ ajw dg;
    public static final /* enum */ ajw dh;
    public static final /* enum */ ajw di;
    public static final /* enum */ ajw dj;
    public static final /* enum */ ajw dk;
    public static final /* enum */ ajw dl;
    public static final /* enum */ ajw dm;
    public static final /* enum */ ajw dn;
    public static final /* enum */ ajw cfr_renamed_3;
    public static final /* enum */ ajw dp;
    public static final /* enum */ ajw dq;
    public static final /* enum */ ajw dr;
    public static final /* enum */ ajw ds;
    public static final /* enum */ ajw dt;
    public static final /* enum */ ajw du;
    public static final /* enum */ ajw dv;
    public static final /* enum */ ajw dw;
    public static final /* enum */ ajw dx;
    public static final /* enum */ ajw dy;
    public static final /* enum */ ajw dz;
    public static final /* enum */ ajw dA;
    public static final /* enum */ ajw dB;
    public static final /* enum */ ajw dC;
    public static final /* enum */ ajw dD;
    public static final /* enum */ ajw dE;
    public static final /* enum */ ajw dF;
    public static final /* enum */ ajw dG;
    public static final /* enum */ ajw dH;
    public static final /* enum */ ajw dI;
    public static final /* enum */ ajw dJ;
    public static final /* enum */ ajw dK;
    public static final /* enum */ ajw dL;
    public static final /* enum */ ajw dM;
    public static final /* enum */ ajw dN;
    public static final /* enum */ ajw dO;
    public static final /* enum */ ajw dP;
    public static final /* enum */ ajw dQ;
    public static final /* enum */ ajw dR;
    public static final /* enum */ ajw dS;
    public static final /* enum */ ajw dT;
    public static final /* enum */ ajw dU;
    public static final /* enum */ ajw dV;
    public static final /* enum */ ajw dW;
    public static final /* enum */ ajw dX;
    public static final /* enum */ ajw dY;
    public static final /* enum */ ajw dZ;
    public static final /* enum */ ajw ea;
    public static final /* enum */ ajw eb;
    public static final /* enum */ ajw ec;
    public static final /* enum */ ajw ed;
    public static final /* enum */ ajw ee;
    public static final /* enum */ ajw ef;
    public static final /* enum */ ajw eg;
    public static final /* enum */ ajw eh;
    public static final /* enum */ ajw ei;
    public static final /* enum */ ajw ej;
    public static final /* enum */ ajw ek;
    public static final /* enum */ ajw el;
    public static final /* enum */ ajw em;
    public static final /* enum */ ajw en;
    public static final /* enum */ ajw eo;
    public static final /* enum */ ajw ep;
    public static final /* enum */ ajw eq;
    public static final /* enum */ ajw er;
    public static final /* enum */ ajw es;
    public static final /* enum */ ajw et;
    public static final /* enum */ ajw eu;
    public static final /* enum */ ajw ev;
    public static final /* enum */ ajw ew;
    public static final /* enum */ ajw ex;
    public static final /* enum */ ajw ey;
    public static final /* enum */ ajw ez;
    public static final /* enum */ ajw eA;
    public static final /* enum */ ajw eB;
    public static final /* enum */ ajw eC;
    public static final /* enum */ ajw eD;
    public static final /* enum */ ajw eE;
    public static final /* enum */ ajw eF;
    public static final /* enum */ ajw eG;
    public static final /* enum */ ajw eH;
    public static final /* enum */ ajw eI;
    public static final /* enum */ ajw eJ;
    public static final /* enum */ ajw eK;
    public static final /* enum */ ajw eL;
    public static final /* enum */ ajw eM;
    public static final /* enum */ ajw eN;
    public static final /* enum */ ajw eO;
    public static final /* enum */ ajw eP;
    public static final /* enum */ ajw eQ;
    public static final /* enum */ ajw eR;
    public static final /* enum */ ajw eS;
    public static final /* enum */ ajw eT;
    public static final /* enum */ ajw eU;
    public static final /* enum */ ajw eV;
    public static final /* enum */ ajw eW;
    public static final /* enum */ ajw eX;
    public static final /* enum */ ajw eY;
    public static final /* enum */ ajw eZ;
    public static final /* enum */ ajw fa;
    public static final /* enum */ ajw fb;
    public static final /* enum */ ajw fc;
    public static final /* enum */ ajw fd;
    public static final /* enum */ ajw fe;
    public static final /* enum */ ajw ff;
    public static final /* enum */ ajw fg;
    public static final /* enum */ ajw fh;
    public static final /* enum */ ajw fi;
    public static final /* enum */ ajw fj;
    public static final /* enum */ ajw fk;
    public static final /* enum */ ajw fl;
    public static final /* enum */ ajw fm;
    public static final /* enum */ ajw fn;
    public static final /* enum */ ajw fo;
    public static final /* enum */ ajw fp;
    public static final /* enum */ ajw fq;
    public static final /* enum */ ajw fr;
    public static final /* enum */ ajw fs;
    public static final /* enum */ ajw ft;
    public static final /* enum */ ajw fu;
    public static final /* enum */ ajw fv;
    public static final /* enum */ ajw fw;
    public static final /* enum */ ajw fx;
    public static final /* enum */ ajw fy;
    public static final /* enum */ ajw fz;
    public static final /* enum */ ajw fA;
    public static final /* enum */ ajw fB;
    public static final /* enum */ ajw fC;
    public static final /* enum */ ajw fD;
    public static final /* enum */ ajw fE;
    public static final /* enum */ ajw fF;
    public static final /* enum */ ajw fG;
    public static final /* enum */ ajw fH;
    public static final /* enum */ ajw fI;
    public static final /* enum */ ajw fJ;
    public static final /* enum */ ajw fK;
    public static final /* enum */ ajw fL;
    public static final /* enum */ ajw fM;
    public static final /* enum */ ajw fN;
    public static final /* enum */ ajw fO;
    public static final /* enum */ ajw fP;
    public static final /* enum */ ajw fQ;
    public static final /* enum */ ajw fR;
    public static final /* enum */ ajw fS;
    public static final /* enum */ ajw fT;
    public static final /* enum */ ajw fU;
    public static final /* enum */ ajw fV;
    public static final /* enum */ ajw fW;
    public static final /* enum */ ajw fX;
    public static final /* enum */ ajw fY;
    public static final /* enum */ ajw fZ;
    public static final /* enum */ ajw ga;
    public static final /* enum */ ajw gb;
    public static final /* enum */ ajw gc;
    public static final /* enum */ ajw gd;
    public static final /* enum */ ajw ge;
    public static final /* enum */ ajw gf;
    public static final /* enum */ ajw gg;
    public static final /* enum */ ajw gh;
    public static final /* enum */ ajw gi;
    public static final /* enum */ ajw gj;
    public static final /* enum */ ajw gk;
    public static final /* enum */ ajw gl;
    public static final /* enum */ ajw gm;
    public static final /* enum */ ajw gn;
    public static final /* enum */ ajw go;
    public static final /* enum */ ajw gp;
    public static final /* enum */ ajw gq;
    public static final /* enum */ ajw gr;
    public static final /* enum */ ajw gs;
    public static final /* enum */ ajw gt;
    public static final /* enum */ ajw gu;
    public static final /* enum */ ajw gv;
    public static final /* enum */ ajw gw;
    public static final /* enum */ ajw gx;
    public static final /* enum */ ajw gy;
    public static final /* enum */ ajw gz;
    public static final /* enum */ ajw gA;
    public static final /* enum */ ajw gB;
    public static final /* enum */ ajw gC;
    public static final /* enum */ ajw gD;
    public static final /* enum */ ajw gE;
    public static final /* enum */ ajw gF;
    public static final /* enum */ ajw gG;
    public static final /* enum */ ajw gH;
    public static final /* enum */ ajw gI;
    public static final /* enum */ ajw gJ;
    public static final /* enum */ ajw gK;
    public static final /* enum */ ajw gL;
    public static final /* enum */ ajw gM;
    public static final /* enum */ ajw gN;
    public static final /* enum */ ajw gO;
    public static final /* enum */ ajw gP;
    public static final /* enum */ ajw gQ;
    public static final /* enum */ ajw gR;
    public static final /* enum */ ajw gS;
    public static final /* enum */ ajw gT;
    public static final /* enum */ ajw gU;
    public static final /* enum */ ajw gV;
    public static final /* enum */ ajw gW;
    public static final /* enum */ ajw gX;
    public static final /* enum */ ajw gY;
    public static final /* enum */ ajw gZ;
    public static final /* enum */ ajw ha;
    public static final /* enum */ ajw hb;
    public static final /* enum */ ajw hc;
    public static final /* enum */ ajw hd;
    public static final /* enum */ ajw he;
    public static final /* enum */ ajw hf;
    public static final /* enum */ ajw hg;
    public static final /* enum */ ajw hh;
    public static final /* enum */ ajw hi;
    public static final /* enum */ ajw hj;
    public static final /* enum */ ajw hk;
    public static final /* enum */ ajw hl;
    public static final /* enum */ ajw hm;
    public static final /* enum */ ajw hn;
    public static final /* enum */ ajw ho;
    public static final /* enum */ ajw hp;
    public static final /* enum */ ajw hq;
    public static final /* enum */ ajw hr;
    public static final /* enum */ ajw hs;
    public static final /* enum */ ajw ht;
    public static final /* enum */ ajw hu;
    public static final /* enum */ ajw hv;
    public static final /* enum */ ajw hw;
    public static final /* enum */ ajw hx;
    public static final /* enum */ ajw hy;
    public static final /* enum */ ajw hz;
    public static final /* enum */ ajw hA;
    public static final /* enum */ ajw hB;
    public static final /* enum */ ajw hC;
    public static final /* enum */ ajw hD;
    public static final /* enum */ ajw hE;
    public static final /* enum */ ajw hF;
    public static final /* enum */ ajw hG;
    public static final /* enum */ ajw hH;
    public static final /* enum */ ajw hI;
    public static final /* enum */ ajw hJ;
    public static final /* enum */ ajw hK;
    public static final /* enum */ ajw hL;
    public static final /* enum */ ajw hM;
    public static final /* enum */ ajw hN;
    public static final /* enum */ ajw hO;
    public static final /* enum */ ajw hP;
    public static final /* enum */ ajw hQ;
    public static final /* enum */ ajw hR;
    public static final /* enum */ ajw hS;
    public static final /* enum */ ajw hT;
    public static final /* enum */ ajw hU;
    public static final /* enum */ ajw hV;
    public static final /* enum */ ajw hW;
    public static final /* enum */ ajw hX;
    public static final /* enum */ ajw hY;
    public static final /* enum */ ajw hZ;
    public static final /* enum */ ajw ia;
    public static final /* enum */ ajw ib;
    public static final /* enum */ ajw ic;
    public static final /* enum */ ajw id;
    public static final /* enum */ ajw ie;
    public static final /* enum */ ajw cfr_renamed_6;
    public static final /* enum */ ajw ig;
    public static final /* enum */ ajw ih;
    public static final /* enum */ ajw ii;
    public static final /* enum */ ajw ij;
    public static final /* enum */ ajw ik;
    public static final /* enum */ ajw il;
    public static final /* enum */ ajw im;
    public static final /* enum */ ajw in;
    public static final /* enum */ ajw io;
    public static final /* enum */ ajw ip;
    public static final /* enum */ ajw iq;
    public static final /* enum */ ajw ir;
    public static final /* enum */ ajw is;
    public static final /* enum */ ajw it;
    public static final /* enum */ ajw iu;
    public static final /* enum */ ajw iv;
    public static final /* enum */ ajw iw;
    public static final /* enum */ ajw ix;
    public static final /* enum */ ajw iy;
    public static final /* enum */ ajw iz;
    public static final /* enum */ ajw iA;
    public static final /* enum */ ajw iB;
    public static final /* enum */ ajw iC;
    public static final /* enum */ ajw iD;
    public static final /* enum */ ajw iE;
    public static final /* enum */ ajw iF;
    public static final /* enum */ ajw iG;
    public static final /* enum */ ajw iH;
    public static final /* enum */ ajw iI;
    public static final /* enum */ ajw iJ;
    public static final /* enum */ ajw iK;
    public static final /* enum */ ajw iL;
    public static final /* enum */ ajw iM;
    public static final /* enum */ ajw iN;
    public static final /* enum */ ajw iO;
    public static final /* enum */ ajw iP;
    public static final /* enum */ ajw iQ;
    public static final /* enum */ ajw iR;
    public static final /* enum */ ajw iS;
    public static final /* enum */ ajw iT;
    public static final /* enum */ ajw iU;
    public static final /* enum */ ajw iV;
    public static final /* enum */ ajw iW;
    public static final /* enum */ ajw iX;
    public static final /* enum */ ajw iY;
    public static final /* enum */ ajw iZ;
    public static final /* enum */ ajw ja;
    public static final /* enum */ ajw jb;
    public static final /* enum */ ajw jc;
    public static final /* enum */ ajw jd;
    public static final /* enum */ ajw je;
    public static final /* enum */ ajw jf;
    public static final /* enum */ ajw jg;
    public static final /* enum */ ajw jh;
    public static final /* enum */ ajw ji;
    public static final /* enum */ ajw jj;
    public static final /* enum */ ajw jk;
    public static final /* enum */ ajw jl;
    public static final /* enum */ ajw jm;
    public static final /* enum */ ajw jn;
    public static final /* enum */ ajw jo;
    public static final /* enum */ ajw jp;
    public static final /* enum */ ajw jq;
    public static final /* enum */ ajw jr;
    public static final /* enum */ ajw js;
    public static final /* enum */ ajw jt;
    public static final /* enum */ ajw ju;
    public static final /* enum */ ajw jv;
    public static final /* enum */ ajw jw;
    public static final /* enum */ ajw jx;
    public static final /* enum */ ajw jy;
    public static final /* enum */ ajw jz;
    public static final /* enum */ ajw jA;
    public static final /* enum */ ajw jB;
    public static final /* enum */ ajw jC;
    public static final /* enum */ ajw jD;
    public static final /* enum */ ajw jE;
    public static final /* enum */ ajw jF;
    public static final /* enum */ ajw jG;
    public static final /* enum */ ajw jH;
    public static final /* enum */ ajw jI;
    public static final /* enum */ ajw jJ;
    public static final /* enum */ ajw jK;
    public static final /* enum */ ajw jL;
    public static final /* enum */ ajw jM;
    public static final /* enum */ ajw jN;
    public static final /* enum */ ajw jO;
    public static final /* enum */ ajw jP;
    public static final /* enum */ ajw jQ;
    public static final /* enum */ ajw jR;
    public static final /* enum */ ajw jS;
    public static final /* enum */ ajw jT;
    public static final /* enum */ ajw jU;
    public static final /* enum */ ajw jV;
    public static final /* enum */ ajw jW;
    public static final /* enum */ ajw jX;
    public static final /* enum */ ajw jY;
    public static final /* enum */ ajw jZ;
    public static final /* enum */ ajw ka;
    public static final /* enum */ ajw kb;
    public static final /* enum */ ajw kc;
    public static final /* enum */ ajw kd;
    public static final /* enum */ ajw ke;
    public static final /* enum */ ajw kf;
    public static final /* enum */ ajw kg;
    public static final /* enum */ ajw kh;
    public static final /* enum */ ajw ki;
    public static final /* enum */ ajw kj;
    public static final /* enum */ ajw kk;
    public static final /* enum */ ajw kl;
    public static final /* enum */ ajw km;
    public static final /* enum */ ajw kn;
    public static final /* enum */ ajw ko;
    public static final /* enum */ ajw kp;
    public static final /* enum */ ajw kq;
    public static final /* enum */ ajw kr;
    public static final /* enum */ ajw ks;
    public static final /* enum */ ajw kt;
    public static final /* enum */ ajw ku;
    public static final /* enum */ ajw kv;
    public static final /* enum */ ajw kw;
    public static final /* enum */ ajw kx;
    public static final /* enum */ ajw ky;
    public static final /* enum */ ajw kz;
    public static final /* enum */ ajw kA;
    public static final /* enum */ ajw kB;
    public static final /* enum */ ajw kC;
    public static final /* enum */ ajw kD;
    public static final /* enum */ ajw kE;
    public static final /* enum */ ajw kF;
    public static final /* enum */ ajw kG;
    public static final /* enum */ ajw kH;
    public static final /* enum */ ajw kI;
    public static final /* enum */ ajw kJ;
    public static final /* enum */ ajw kK;
    public static final /* enum */ ajw kL;
    public static final /* enum */ ajw kM;
    public static final /* enum */ ajw kN;
    public static final /* enum */ ajw kO;
    public static final /* enum */ ajw kP;
    public static final /* enum */ ajw kQ;
    public static final /* enum */ ajw kR;
    public static final /* enum */ ajw kS;
    public static final /* enum */ ajw kT;
    public static final /* enum */ ajw kU;
    public static final /* enum */ ajw kV;
    public static final /* enum */ ajw kW;
    public static final /* enum */ ajw kX;
    public static final /* enum */ ajw kY;
    public static final /* enum */ ajw kZ;
    public static final /* enum */ ajw la;
    public static final /* enum */ ajw lb;
    public static final /* enum */ ajw lc;
    public static final /* enum */ ajw ld;
    public static final /* enum */ ajw le;
    private final String var_java_lang_String_a;
    private final Array<String> var_com_badlogic_gdx_utils_Array_java_lang_String__a;
    private final Class<? extends Disposable> var_java_lang_Class___extends_com_badlogic_gdx_utils_Disposable__a;
    private static final /* synthetic */ ajw[] var_ajw_arr_a;

    public static ajw[] values() {
        return (ajw[])var_ajw_arr_a.clone();
    }

    public static ajw valueOf(String string) {
        return Enum.valueOf(ajw.class, string);
    }

    private ajw(String string2, Class<? extends Disposable> clazz, Array<String> ... arrayArray) {
        this.var_java_lang_String_a = string2;
        this.var_ajw_a = clazz;
        this.var_ajw_a = arrayArray != null && arrayArray.length > 0 ? arrayArray[0] : new Array();
    }

    public String a() {
        return this.var_java_lang_String_a;
    }

    public Class<? extends Disposable> a() {
        return this.var_ajw_a;
    }

    public String toString() {
        return "ScreenDependency mainPath=" + this.var_java_lang_String_a + "  Clazz=" + (Object)((Object)this.var_ajw_a);
    }

    static {
        var_ajw_a = new ajw("packed/screens/register/register_ui_core-v2.atlas", TextureAtlas.class, new ajx());
        b = new ajw("packed/screens/lobby/store_ui_core-v13.atlas", TextureAtlas.class, new aoe());
        c = new ajw("packed/screens/lobby/lobby_ui_core-v57.atlas", TextureAtlas.class, new asl());
        d = new ajw("packed/screens/login/login_ui_core_v1.atlas", TextureAtlas.class, new aun());
        e = new ajw("packed/screens/play/play_ui_core-v21.atlas", TextureAtlas.class, new auy());
        f = new ajw("packed/screens/charactercreation/character_creation_ui_core.atlas", TextureAtlas.class, new avj());
        g = new ajw("misc/cursors/cursors.atlas", TextureAtlas.class, new avu());
        h = new ajw("packed/ui/platforms/platforms.atlas", TextureAtlas.class, new awf());
        i = new ajw("packed/screens/lobby/BannerBackgrounds-v2.atlas", TextureAtlas.class, new awq());
        j = new ajw("packed/screens/play/arenas/snowy/snowy_arena_background.png", Texture.class, new Array[0]);
        k = new ajw("packed/screens/play/arenas/snowy/snowy_arena_core.atlas", TextureAtlas.class, new ajy());
        l = new ajw("packed/screens/play/arenas/snowy/snowy_arena_tmx4.tmx", TiledMap.class, new Array[0]);
        m = new ajw("packed/screens/play/arenas/dark/dark_arena_background.png", Texture.class, new Array[0]);
        n = new ajw("packed/screens/play/arenas/dark/dark_arena_background_night.png", Texture.class, new Array[0]);
        o = new ajw("packed/screens/play/arenas/dark/dark_arena_core.atlas", TextureAtlas.class, new akj());
        p = new ajw("packed/screens/play/arenas/dark/dark_arena_tmx4.tmx", TiledMap.class, new Array[0]);
        q = new ajw("packed/screens/play/arenas/desert/arena_background-1.png", Texture.class, new Array[0]);
        r = new ajw("packed/screens/play/arenas/desert/arena_background_dark-1.png", Texture.class, new Array[0]);
        s = new ajw("packed/screens/play/arenas/desert/desert_arena_core.atlas", TextureAtlas.class, new aku());
        t = new ajw("packed/screens/play/arenas/desert/desert_arena_tmx5.tmx", TiledMap.class, new Array[0]);
        u = new ajw("packed/screens/play/arenas/forest/forest_arena_background.png", Texture.class, new Array[0]);
        v = new ajw("packed/screens/play/arenas/forest/forest_arena_background_night.png", Texture.class, new Array[0]);
        w = new ajw("packed/screens/play/arenas/forest/forest_arena_core-2.atlas", TextureAtlas.class, new alf());
        x = new ajw("packed/screens/play/arenas/forest/forest_arena_tmx5.tmx", TiledMap.class, new Array[0]);
        y = new ajw("packed/screens/play/arenas/indoor/indoor_arena_background-2.png", Texture.class, new Array[0]);
        z = new ajw("packed/screens/play/arenas/indoor/indoor_arena_background_night-2.png", Texture.class, new Array[0]);
        A = new ajw("packed/screens/play/arenas/indoor/indoor_arena_core.atlas", TextureAtlas.class, new alq());
        B = new ajw("packed/screens/play/arenas/indoor/indoor_arena_tmx7.tmx", TiledMap.class, new Array[0]);
        C = new ajw("packed/models/assassin/outfit_1/dark/full.atlas", TextureAtlas.class, new amb());
        D = new ajw("packed/models/assassin/outfit_1/dark/idle.atlas", TextureAtlas.class, new amm());
        E = new ajw("packed/models/assassin/outfit_1/light/full.atlas", TextureAtlas.class, new amx());
        F = new ajw("packed/models/assassin/outfit_1/light/idle.atlas", TextureAtlas.class, new ani());
        G = new ajw("packed/models/assassin/outfit_2/dark/full.atlas", TextureAtlas.class, new ant());
        H = new ajw("packed/models/assassin/outfit_2/dark/idle.atlas", TextureAtlas.class, new aof());
        I = new ajw("packed/models/assassin/outfit_2/light/full.atlas", TextureAtlas.class, new aoq());
        J = new ajw("packed/models/assassin/outfit_2/light/idle.atlas", TextureAtlas.class, new apb());
        K = new ajw("packed/models/elder/outfit_1/dark/full.atlas", TextureAtlas.class, new apm());
        L = new ajw("packed/models/elder/outfit_1/dark/idle.atlas", TextureAtlas.class, new apx());
        M = new ajw("packed/models/elder/outfit_1/light/full.atlas", TextureAtlas.class, new aqi());
        N = new ajw("packed/models/elder/outfit_1/light/idle.atlas", TextureAtlas.class, new aqt());
        O = new ajw("packed/models/elder/outfit_2/dark/full.atlas", TextureAtlas.class, new are());
        P = new ajw("packed/models/elder/outfit_2/dark/idle.atlas", TextureAtlas.class, new arp());
        Q = new ajw("packed/models/elder/outfit_2/light/full.atlas", TextureAtlas.class, new asa());
        R = new ajw("packed/models/elder/outfit_2/light/idle.atlas", TextureAtlas.class, new asm());
        S = new ajw("packed/models/elder/wolf/dark/full.atlas", TextureAtlas.class, new asx());
        T = new ajw("packed/models/elder/wolf/light/full.atlas", TextureAtlas.class, new ati());
        U = new ajw("packed/models/elder/tiger/full.atlas", TextureAtlas.class, new att());
        V = new ajw("packed/models/elder/bear/full.atlas", TextureAtlas.class, new aue());
        W = new ajw("packed/models/elder/sheep/dark/full.atlas", TextureAtlas.class, new aui());
        X = new ajw("packed/models/elder/sheep/light/full.atlas", TextureAtlas.class, new auj());
        Y = new ajw("packed/models/paladin/outfit_1/dark/full.atlas", TextureAtlas.class, new auk());
        Z = new ajw("packed/models/paladin/outfit_1/dark/idle.atlas", TextureAtlas.class, new aul());
        aa = new ajw("packed/models/paladin/outfit_1/light/full.atlas", TextureAtlas.class, new aum());
        ab = new ajw("packed/models/paladin/outfit_1/light/idle.atlas", TextureAtlas.class, new auo());
        ac = new ajw("packed/models/paladin/outfit_2/dark/full.atlas", TextureAtlas.class, new aup());
        ad = new ajw("packed/models/paladin/outfit_2/dark/idle.atlas", TextureAtlas.class, new auq());
        ae = new ajw("packed/models/paladin/outfit_2/light/full.atlas", TextureAtlas.class, new aur());
        af = new ajw("packed/models/paladin/outfit_2/light/idle.atlas", TextureAtlas.class, new aus());
        ag = new ajw("packed/models/lich/outfit_1/dark/full.atlas", TextureAtlas.class, new aut());
        ah = new ajw("packed/models/lich/outfit_1/dark/idle.atlas", TextureAtlas.class, new auu());
        ai = new ajw("packed/models/lich/outfit_1/light/full.atlas", TextureAtlas.class, new auv());
        aj = new ajw("packed/models/lich/outfit_1/light/idle.atlas", TextureAtlas.class, new auw());
        ak = new ajw("packed/models/lich/outfit_2/dark/full.atlas", TextureAtlas.class, new aux_());
        al = new ajw("packed/models/lich/outfit_2/dark/idle.atlas", TextureAtlas.class, new auz());
        am = new ajw("packed/models/lich/outfit_2/light/full.atlas", TextureAtlas.class, new ava());
        an = new ajw("packed/models/lich/outfit_2/light/idle.atlas", TextureAtlas.class, new avb());
        ao = new ajw("packed/models/lich/outfit_3/dark/full.atlas", TextureAtlas.class, new avc());
        ap = new ajw("packed/models/lich/outfit_3/dark/idle.atlas", TextureAtlas.class, new avd());
        aq = new ajw("packed/models/lich/outfit_3/light/full.atlas", TextureAtlas.class, new ave());
        ar = new ajw("packed/models/lich/outfit_3/light/idle.atlas", TextureAtlas.class, new avf());
        as = new ajw("packed/models/scholar/outfit_1/dark/full.atlas", TextureAtlas.class, new avg());
        at = new ajw("packed/models/scholar/outfit_1/dark/idle.atlas", TextureAtlas.class, new avh());
        au = new ajw("packed/models/scholar/outfit_1/light/full.atlas", TextureAtlas.class, new avi());
        av = new ajw("packed/models/scholar/outfit_1/light/idle.atlas", TextureAtlas.class, new avk());
        aw = new ajw("packed/models/scholar/outfit_2/dark/full.atlas", TextureAtlas.class, new avl());
        ax = new ajw("packed/models/scholar/outfit_2/dark/idle.atlas", TextureAtlas.class, new avm());
        ay = new ajw("packed/models/scholar/outfit_2/light/full.atlas", TextureAtlas.class, new avn());
        az = new ajw("packed/models/scholar/outfit_2/light/idle.atlas", TextureAtlas.class, new avo());
        aA = new ajw("packed/models/scholar/outfit_3/dark/full.atlas", TextureAtlas.class, new avp());
        aB = new ajw("packed/models/scholar/outfit_3/dark/idle.atlas", TextureAtlas.class, new avq());
        aC = new ajw("packed/models/scholar/outfit_3/light/full.atlas", TextureAtlas.class, new avr());
        aD = new ajw("packed/models/scholar/outfit_3/light/idle.atlas", TextureAtlas.class, new avs());
        aE = new ajw("packed/models/nihilist/outfit_1/dark/full.atlas", TextureAtlas.class, new avt());
        aF = new ajw("packed/models/nihilist/outfit_1/dark/idle.atlas", TextureAtlas.class, new avv());
        aG = new ajw("packed/models/nihilist/outfit_1/light/full.atlas", TextureAtlas.class, new avw());
        aH = new ajw("packed/models/nihilist/outfit_1/light/idle.atlas", TextureAtlas.class, new avx());
        aI = new ajw("packed/models/nihilist/outfit_2/dark/full.atlas", TextureAtlas.class, new avy());
        aJ = new ajw("packed/models/nihilist/outfit_2/dark/idle.atlas", TextureAtlas.class, new avz());
        aK = new ajw("packed/models/nihilist/outfit_2/light/full.atlas", TextureAtlas.class, new awa());
        aL = new ajw("packed/models/nihilist/outfit_2/light/idle.atlas", TextureAtlas.class, new awb());
        aM = new ajw("packed/models/mystic/outfit_1/dark/full.atlas", TextureAtlas.class, new awc());
        aN = new ajw("packed/models/mystic/outfit_1/dark/idle.atlas", TextureAtlas.class, new awd());
        aO = new ajw("packed/models/mystic/outfit_1/light/full.atlas", TextureAtlas.class, new awe());
        aP = new ajw("packed/models/mystic/outfit_1/light/idle.atlas", TextureAtlas.class, new awg());
        aQ = new ajw("packed/models/mystic/outfit_2/dark/full.atlas", TextureAtlas.class, new awh());
        aR = new ajw("packed/models/mystic/outfit_2/dark/idle.atlas", TextureAtlas.class, new awi());
        aS = new ajw("packed/models/mystic/outfit_2/light/full.atlas", TextureAtlas.class, new awj());
        aT = new ajw("packed/models/mystic/outfit_2/light/idle.atlas", TextureAtlas.class, new awk());
        aU = new ajw("packed/models/ranger/outfit_1/dark/full.atlas", TextureAtlas.class, new awl());
        aV = new ajw("packed/models/ranger/outfit_1/dark/idle.atlas", TextureAtlas.class, new awm());
        aW = new ajw("packed/models/ranger/outfit_1/light/full.atlas", TextureAtlas.class, new awn());
        aX = new ajw("packed/models/ranger/outfit_1/light/idle.atlas", TextureAtlas.class, new awo());
        aY = new ajw("packed/models/ranger/outfit_2/dark/full.atlas", TextureAtlas.class, new awp());
        aZ = new ajw("packed/models/ranger/outfit_2/dark/idle.atlas", TextureAtlas.class, new awr());
        ba = new ajw("packed/models/ranger/outfit_2/light/full.atlas", TextureAtlas.class, new aws());
        bb = new ajw("packed/models/ranger/outfit_2/light/idle.atlas", TextureAtlas.class, new awt());
        bc = new ajw("packed/models/champion/outfit_1/dark/full.atlas", TextureAtlas.class, new awu());
        bd = new ajw("packed/models/champion/outfit_1/dark/idle.atlas", TextureAtlas.class, new awv());
        be = new ajw("packed/models/champion/outfit_1/light/full.atlas", TextureAtlas.class, new aww());
        bf = new ajw("packed/models/champion/outfit_1/light/idle.atlas", TextureAtlas.class, new awx());
        bg = new ajw("packed/models/champion/outfit_2/dark/full.atlas", TextureAtlas.class, new awy());
        bh = new ajw("packed/models/champion/outfit_2/dark/idle.atlas", TextureAtlas.class, new awz());
        bi = new ajw("packed/models/champion/outfit_2/light/full.atlas", TextureAtlas.class, new axa());
        bj = new ajw("packed/models/champion/outfit_2/light/idle.atlas", TextureAtlas.class, new ajz());
        bk = new ajw("packed/models/wizard/outfit_1/dark/full.atlas", TextureAtlas.class, new aka());
        bl = new ajw("packed/models/wizard/outfit_1/dark/idle.atlas", TextureAtlas.class, new akb());
        bm = new ajw("packed/models/wizard/outfit_1/light/full.atlas", TextureAtlas.class, new akc());
        bn = new ajw("packed/models/wizard/outfit_1/light/idle.atlas", TextureAtlas.class, new akd());
        bo = new ajw("packed/models/wizard/outfit_2/dark/full.atlas", TextureAtlas.class, new ake());
        bp = new ajw("packed/models/wizard/outfit_2/dark/idle.atlas", TextureAtlas.class, new akf());
        bq = new ajw("packed/models/wizard/outfit_2/light/full.atlas", TextureAtlas.class, new akg());
        br = new ajw("packed/models/wizard/outfit_2/light/idle.atlas", TextureAtlas.class, new akh());
        bs = new ajw("", TextureAtlas.class, new Array[0]);
        bt = new ajw("packed/spells/harm/Bleeding/Bleeding_on_tick.atlas", TextureAtlas.class, new aki());
        bu = new ajw("packed/spells/harm/Blind/Blind_on_tick.atlas", TextureAtlas.class, new akk());
        bv = new ajw("packed/spells/harm/Burning/Burning_on_tick.atlas", TextureAtlas.class, new akl());
        bw = new ajw("packed/spells/harm/Hobble/Hobble_on_tick.atlas", TextureAtlas.class, new akm());
        bx = new ajw("packed/spells/harm/Incapacitate/Incapacitate_on_tick.atlas", TextureAtlas.class, new akn());
        by = new ajw("packed/spells/harm/Infection/Infection_on_tick.atlas", TextureAtlas.class, new ako());
        bz = new ajw("packed/spells/harm/Interrupt/Interrupt_on_tick.atlas", TextureAtlas.class, new akp());
        bA = new ajw("packed/spells/harm/Poison/Poison_on_tick.atlas", TextureAtlas.class, new akq());
        bB = new ajw("packed/spells/harm/Shock/Shock_on_tick.atlas", TextureAtlas.class, new akr());
        bC = new ajw("packed/spells/harm/Silence/Silence_on_tick.atlas", TextureAtlas.class, new aks());
        bD = new ajw("packed/spells/harm/Silence/Silence.ogg", Sound.class, new Array[0]);
        bE = new ajw("packed/spells/harm/Stun/Stun_on_tick.atlas", TextureAtlas.class, new akt());
        bF = new ajw("packed/spells/harm/Stun/Stun.ogg", Sound.class, new Array[0]);
        bG = new ajw("packed/spells/harm/Fear/Fear_on_tick.atlas", TextureAtlas.class, new akv());
        bH = new ajw("packed/spells/harm/Fear/Fear.ogg", Sound.class, new Array[0]);
        bI = new ajw("packed/spells/assassin/Basic/Basic.atlas", TextureAtlas.class, new akw());
        bJ = new ajw("packed/spells/assassin/Basic/Basic.ogg", Sound.class, new Array[0]);
        bK = new ajw("packed/spells/assassin/Annihilate/Annihilate_on_tick.atlas", TextureAtlas.class, new akx());
        bL = new ajw("packed/spells/assassin/Annihilate/Annihilate.ogg", Sound.class, new Array[0]);
        bM = new ajw("packed/spells/assassin/Bandage/Bandage_on_tick.atlas", TextureAtlas.class, new aky());
        bN = new ajw("packed/spells/assassin/Bandage/Bandage.ogg", Sound.class, new Array[0]);
        bO = new ajw("packed/spells/assassin/Dash/Dash_on_tick.atlas", TextureAtlas.class, new akz());
        bP = new ajw("packed/spells/assassin/Dash/Dash.ogg", Sound.class, new Array[0]);
        bQ = new ajw("packed/spells/assassin/Daze/Daze_on_tick.atlas", TextureAtlas.class, new ala());
        bR = new ajw("packed/spells/assassin/Daze/Daze.ogg", Sound.class, new Array[0]);
        bS = new ajw("packed/spells/assassin/DustCloud/DustCloud_on_tick.atlas", TextureAtlas.class, new alb());
        bT = new ajw("packed/spells/assassin/DustCloud/DustCloud.ogg", Sound.class, new Array[0]);
        bU = new ajw("packed/spells/assassin/Envenom/Envenom.ogg", Sound.class, new Array[0]);
        bV = new ajw("packed/spells/assassin/MurderousInstincts/MurderousInstincts_on_tick.atlas", TextureAtlas.class, new alc());
        bW = new ajw("packed/spells/assassin/MurderousInstincts/MurderousInstincts.ogg", Sound.class, new Array[0]);
        bX = new ajw("packed/spells/assassin/Puncture/Puncture_on_tick.atlas", TextureAtlas.class, new ald());
        bY = new ajw("packed/spells/assassin/Puncture/Puncture.ogg", Sound.class, new Array[0]);
        bZ = new ajw("packed/spells/assassin/ShadowWalk/ShadowWalk_on_tick.atlas", TextureAtlas.class, new ale());
        ca = new ajw("packed/spells/assassin/ShadowWalk/ShadowWalk.ogg", Sound.class, new Array[0]);
        cb = new ajw("packed/spells/assassin/Shroud/Shroud_on_tick.atlas", TextureAtlas.class, new alg());
        cc = new ajw("packed/spells/assassin/Shroud/Shroud.ogg", Sound.class, new Array[0]);
        cd = new ajw("packed/spells/assassin/Slap/Slap_on_tick.atlas", TextureAtlas.class, new alh());
        ce = new ajw("packed/spells/assassin/Slap/Slap.ogg", Sound.class, new Array[0]);
        cf = new ajw("packed/spells/assassin/Slash/Slash_on_tick.atlas", TextureAtlas.class, new ali());
        cg = new ajw("packed/spells/assassin/Slash/Slash.ogg", Sound.class, new Array[0]);
        ch = new ajw("packed/spells/assassin/Stealth/Stealth_on_tick.atlas", TextureAtlas.class, new alj());
        ci = new ajw("packed/spells/assassin/Stealth/Stealth.ogg", Sound.class, new Array[0]);
        cj = new ajw("packed/spells/assassin/TempleStrike/TempleStrike_on_tick.atlas", TextureAtlas.class, new alk());
        ck = new ajw("packed/spells/assassin/TempleStrike/TempleStrike.ogg", Sound.class, new Array[0]);
        cl = new ajw("packed/spells/assassin/WhirlingKnives/WhirlingKnives_on_tick.atlas", TextureAtlas.class, new all());
        cm = new ajw("packed/spells/assassin/WhirlingKnives/WhirlingKnives.ogg", Sound.class, new Array[0]);
        cn = new ajw("packed/spells/champion/Basic/Basic.atlas", TextureAtlas.class, new alm());
        co = new ajw("packed/spells/champion/Basic/Basic.ogg", Sound.class, new Array[0]);
        cp = new ajw("packed/spells/champion/Charge/Charge.ogg", Sound.class, new Array[0]);
        cq = new ajw("packed/spells/champion/CripplingSlash/CripplingSlash_on_tick.atlas", TextureAtlas.class, new aln());
        cr = new ajw("packed/spells/champion/CripplingSlash/CripplingSlash.ogg", Sound.class, new Array[0]);
        cs = new ajw("packed/spells/champion/CrushingBlow/CrushingBlow_on_tick.atlas", TextureAtlas.class, new alo());
        ct = new ajw("packed/spells/champion/CrushingBlow/CrushingBlow.ogg", Sound.class, new Array[0]);
        cu = new ajw("packed/spells/champion/Decapitate/Decapitate_on_tick.atlas", TextureAtlas.class, new alp());
        cv = new ajw("packed/spells/champion/Decapitate/Decapitate.ogg", Sound.class, new Array[0]);
        cw = new ajw("packed/spells/champion/DisruptingBlade/DisruptingBlade_on_tick.atlas", TextureAtlas.class, new alr());
        cx = new ajw("packed/spells/champion/DisruptingBlade/DisruptingBlade.ogg", Sound.class, new Array[0]);
        cy = new ajw("packed/spells/champion/EnduringWarcry/EnduringWarcry_on_tick.atlas", TextureAtlas.class, new als());
        cz = new ajw("packed/spells/champion/EnduringWarcry/EnduringWarcry.ogg", Sound.class, new Array[0]);
        cA = new ajw("packed/spells/champion/EnduringWarcry/EnduringWarcryBuff_on_tick.atlas", TextureAtlas.class, new alt());
        cB = new ajw("packed/spells/champion/Enrage/Enrage_on_tick.atlas", TextureAtlas.class, new alu());
        cC = new ajw("packed/spells/champion/Enrage/Enrage.ogg", Sound.class, new Array[0]);
        cD = new ajw("packed/spells/champion/Intimidation/Intimidation_on_tick.atlas", TextureAtlas.class, new alv());
        cE = new ajw("packed/spells/champion/Lacerate/Lacerate_on_tick.atlas", TextureAtlas.class, new alw());
        cF = new ajw("packed/spells/champion/Lacerate/Lacerate.ogg", Sound.class, new Array[0]);
        cG = new ajw("packed/spells/champion/MasterOfTheSword/MasterOfTheSword_on_tick.atlas", TextureAtlas.class, new alx());
        cH = new ajw("packed/spells/champion/MasterOfTheSword/MasterOfTheSword.ogg", Sound.class, new Array[0]);
        cI = new ajw("packed/spells/champion/PiercingDagger/PiercingDagger.atlas", TextureAtlas.class, new aly());
        cJ = new ajw("packed/spells/champion/PiercingDagger/PiercingDagger.ogg", Sound.class, new Array[0]);
        cK = new ajw("packed/spells/champion/PiercingDagger/PiercingDaggerImpact.ogg", Sound.class, new Array[0]);
        cL = new ajw("packed/spells/champion/ResoundingWarcry/ResoundingWarcry_on_tick.atlas", TextureAtlas.class, new alz());
        cM = new ajw("packed/spells/champion/ResoundingWarcry/ResoundingWarcry.ogg", Sound.class, new Array[0]);
        cN = new ajw("packed/spells/champion/ResoundingWarcry/ResoundingWarcryDebuff_on_tick.atlas", TextureAtlas.class, new ama());
        cO = new ajw("packed/spells/champion/SlashingStrike/SlashingStrike_on_tick.atlas", TextureAtlas.class, new amc());
        cP = new ajw("packed/spells/champion/SlashingStrike/SlashingStrike.ogg", Sound.class, new Array[0]);
        cQ = new ajw("packed/spells/champion/Sprint/Sprint_on_tick.atlas", TextureAtlas.class, new amd());
        cR = new ajw("packed/spells/champion/Sprint/Sprint.ogg", Sound.class, new Array[0]);
        cS = new ajw("packed/spells/champion/Whirlwind/Whirlwind_on_tick.atlas", TextureAtlas.class, new ame());
        cT = new ajw("packed/spells/champion/Whirlwind/Whirlwind.ogg", Sound.class, new Array[0]);
        cU = new ajw("packed/spells/elder/Basic/Basic.atlas", TextureAtlas.class, new amf());
        cV = new ajw("packed/spells/elder/Basic/Basic.ogg", Sound.class, new Array[0]);
        cW = new ajw("packed/spells/elder/Basic/BasicImpact.atlas", TextureAtlas.class, new amg());
        cX = new ajw("packed/spells/elder/Basic/BasicImpact.ogg", Sound.class, new Array[0]);
        cY = new ajw("packed/spells/elder/Shapeshift/Bear_Charge3.ogg", Sound.class, new Array[0]);
        cZ = new ajw("packed/spells/elder/Shapeshift/Bear_Ironhide2.ogg", Sound.class, new Array[0]);
        da = new ajw("packed/spells/elder/Shapeshift/Bear_Smash2.ogg", Sound.class, new Array[0]);
        db = new ajw("packed/spells/elder/GraspingVines/GraspingVines_on_tick.atlas", TextureAtlas.class, new amh());
        dc = new ajw("packed/spells/elder/GraspingVines/GraspingVines.ogg", Sound.class, new Array[0]);
        dd = new ajw("packed/spells/elder/Inspiration/Inspiration_on_tick.atlas", TextureAtlas.class, new ami());
        de = new ajw("packed/spells/elder/Inspiration/Inspiration.ogg", Sound.class, new Array[0]);
        df = new ajw("packed/spells/elder/MendingSpirit/MendingSpirit_on_tick.atlas", TextureAtlas.class, new amj());
        dg = new ajw("packed/spells/elder/MendingSpirit/MendingSpirit.ogg", Sound.class, new Array[0]);
        dh = new ajw("packed/spells/elder/NaturesFury/NaturesFury_on_tick.atlas", TextureAtlas.class, new amk());
        di = new ajw("packed/spells/elder/NaturesFury/NaturesFury_on_impact.atlas", TextureAtlas.class, new aml());
        dj = new ajw("packed/spells/elder/NaturesFury/CorrosiveAsp.ogg", Sound.class, new Array[0]);
        dk = new ajw("packed/spells/elder/NaturesFury/CorrosiveAspImpact.ogg", Sound.class, new Array[0]);
        dl = new ajw("packed/spells/elder/Remedy/Remedy_on_tick.atlas", TextureAtlas.class, new amn());
        dm = new ajw("packed/spells/elder/Remedy/Remedy.ogg", Sound.class, new Array[0]);
        dn = new ajw("packed/spells/elder/Revitalize/Revitalize_on_tick.atlas", TextureAtlas.class, new amo());
        cfr_renamed_3 = new ajw("packed/spells/elder/Revitalize/Revitalize.ogg", Sound.class, new Array[0]);
        dp = new ajw("packed/spells/elder/Ritual/Ritual_on_tick.atlas", TextureAtlas.class, new amp());
        dq = new ajw("packed/spells/elder/SeedOfLife/SeedOfLife_on_tick.atlas", TextureAtlas.class, new amq());
        dr = new ajw("packed/spells/elder/SeedOfLife/SeedOfLife.ogg", Sound.class, new Array[0]);
        ds = new ajw("packed/spells/elder/Serenity/Serenity_on_tick.atlas", TextureAtlas.class, new amr());
        dt = new ajw("packed/spells/elder/Serenity/Serenity.ogg", Sound.class, new Array[0]);
        du = new ajw("packed/spells/elder/Shapeshift/Shapeshift_on_tick.atlas", TextureAtlas.class, new ams());
        dv = new ajw("packed/spells/elder/Shapeshift/Shapeshift.ogg", Sound.class, new Array[0]);
        dw = new ajw("packed/spells/elder/Shapeshift/ShapeshiftBear2.ogg", Sound.class, new Array[0]);
        dx = new ajw("packed/spells/elder/Soothe/Soothe_on_tick.atlas", TextureAtlas.class, new amt());
        dy = new ajw("packed/spells/elder/Soothe/Soothe.ogg", Sound.class, new Array[0]);
        dz = new ajw("packed/spells/elder/Symbiosis/Symbiosis_on_tick.atlas", TextureAtlas.class, new amu());
        dA = new ajw("packed/spells/elder/Symbiosis/Symbiosis.ogg", Sound.class, new Array[0]);
        dB = new ajw("packed/spells/elder/ToxicSpore/ToxicSpore_on_tick.atlas", TextureAtlas.class, new amv());
        dC = new ajw("packed/spells/elder/ToxicSpore/ToxicSpore.ogg", Sound.class, new Array[0]);
        dD = new ajw("packed/spells/elder/Windstorm/Windstorm_on_tick.atlas", TextureAtlas.class, new amw());
        dE = new ajw("packed/spells/elder/Windstorm/Windstorm.ogg", Sound.class, new Array[0]);
        dF = new ajw("packed/spells/lich/Basic/Basic.atlas", TextureAtlas.class, new amy());
        dG = new ajw("packed/spells/lich/Basic/Basic.ogg", Sound.class, new Array[0]);
        dH = new ajw("packed/spells/lich/Basic/BasicImpact.atlas", TextureAtlas.class, new amz());
        dI = new ajw("packed/spells/lich/Basic/BasicImpact.ogg", Sound.class, new Array[0]);
        dJ = new ajw("packed/spells/lich/AbyssalSpike/AbyssalSpike_on_tick.atlas", TextureAtlas.class, new ana());
        dK = new ajw("packed/spells/lich/AbyssalSpike/AbyssalSpike.ogg", Sound.class, new Array[0]);
        dL = new ajw("packed/spells/lich/AcidRain/AcidRain_on_tick.atlas", TextureAtlas.class, new anb());
        dM = new ajw("packed/spells/lich/AcidRain/AcidRain.ogg", Sound.class, new Array[0]);
        dN = new ajw("packed/spells/lich/BloodOfTheDying/BloodOfTheDying.ogg", Sound.class, new Array[0]);
        dO = new ajw("packed/spells/lich/Contagion/Contagion_on_tick.atlas", TextureAtlas.class, new anc());
        dP = new ajw("packed/spells/lich/DeathsGrasp/DeathsGrasp_on_tick.atlas", TextureAtlas.class, new and());
        dQ = new ajw("packed/spells/lich/DeathsGrasp/DeathsGrasp.ogg", Sound.class, new Array[0]);
        dR = new ajw("packed/spells/lich/Depravity/Depravity_on_tick.atlas", TextureAtlas.class, new ane());
        dS = new ajw("packed/spells/lich/Depravity/Depravity.ogg", Sound.class, new Array[0]);
        dT = new ajw("packed/spells/lich/Exhaustion/Exhaustion_on_tick.atlas", TextureAtlas.class, new anf());
        dU = new ajw("packed/spells/lich/Exhaustion/Exhaustion.ogg", Sound.class, new Array[0]);
        dV = new ajw("packed/spells/lich/Inflame/Inflame_on_tick.atlas", TextureAtlas.class, new ang());
        dW = new ajw("packed/spells/lich/Inflame/Inflame.ogg", Sound.class, new Array[0]);
        dX = new ajw("packed/spells/lich/Miasma/Miasma_on_tick.atlas", TextureAtlas.class, new anh());
        dY = new ajw("packed/spells/lich/Miasma/Miasma.ogg", Sound.class, new Array[0]);
        dZ = new ajw("packed/spells/lich/NetherBolt/NetherBolt.atlas", TextureAtlas.class, new anj());
        ea = new ajw("packed/spells/lich/NetherBolt/NetherBolt.ogg", Sound.class, new Array[0]);
        eb = new ajw("packed/spells/lich/NetherBolt/NetherBoltImpact.ogg", Sound.class, new Array[0]);
        ec = new ajw("packed/spells/lich/NetherBolt/NetherBoltImpact.atlas", TextureAtlas.class, new ank());
        ed = new ajw("packed/spells/lich/Parasite/Parasite_on_tick.atlas", TextureAtlas.class, new anl());
        ee = new ajw("packed/spells/lich/Parasite/Parasite.ogg", Sound.class, new Array[0]);
        ef = new ajw("packed/spells/lich/PoisonNova/PoisonNova_on_tick.atlas", TextureAtlas.class, new anm());
        eg = new ajw("packed/spells/lich/PoisonNova/PoisonNova.ogg", Sound.class, new Array[0]);
        eh = new ajw("packed/spells/lich/PoolOfAgony/PoolOfAgony_on_tick.atlas", TextureAtlas.class, new ann());
        ei = new ajw("packed/spells/lich/PoolOfSouls/PoolOfSouls_on_tick.atlas", TextureAtlas.class, new ano());
        ej = new ajw("packed/spells/lich/PoolOfSouls/PoolOfSouls.ogg", Sound.class, new Array[0]);
        ek = new ajw("packed/spells/lich/SacrificeSoul/SacrificeSoul_on_tick.atlas", TextureAtlas.class, new anp());
        el = new ajw("packed/spells/lich/SacrificeSoul/SacrificeSoul.ogg", Sound.class, new Array[0]);
        em = new ajw("packed/spells/lich/ShatterMagic/ShatterMagic_on_tick.atlas", TextureAtlas.class, new anq());
        en = new ajw("packed/spells/lich/ShatterMagic/ShatterMagic.ogg", Sound.class, new Array[0]);
        eo = new ajw("packed/spells/lich/Pestilence/Pestilence_on_tick.atlas", TextureAtlas.class, new anr());
        ep = new ajw("packed/spells/lich/Pestilence/Pestilence.ogg", Sound.class, new Array[0]);
        eq = new ajw("packed/spells/lich/Torment/Torment_on_tick.atlas", TextureAtlas.class, new ans());
        er = new ajw("packed/spells/lich/Torment/Torment.ogg", Sound.class, new Array[0]);
        es = new ajw("packed/spells/lich/UnderworldArmor/UnderworldArmor_on_tick.atlas", TextureAtlas.class, new anu());
        et = new ajw("packed/spells/lich/UnderworldArmor/UnderworldArmor.ogg", Sound.class, new Array[0]);
        eu = new ajw("packed/spells/mystic/Basic/Basic.atlas", TextureAtlas.class, new anv());
        ev = new ajw("packed/spells/mystic/Basic/Basic.ogg", Sound.class, new Array[0]);
        ew = new ajw("packed/spells/mystic/Basic/BasicImpact.atlas", TextureAtlas.class, new anw());
        ex = new ajw("packed/spells/mystic/Basic/BasicImpact.ogg", Sound.class, new Array[0]);
        ey = new ajw("packed/spells/mystic/Aegis/Aegis_on_tick.atlas", TextureAtlas.class, new anx());
        ez = new ajw("packed/spells/mystic/Aegis/Aegis.ogg", Sound.class, new Array[0]);
        eA = new ajw("packed/spells/mystic/AstralShock/AstralShock_on_tick.atlas", TextureAtlas.class, new any());
        eB = new ajw("packed/spells/mystic/AstralShock/AstralShock.ogg", Sound.class, new Array[0]);
        eC = new ajw("packed/spells/mystic/Blackout/Blackout_on_tick.atlas", TextureAtlas.class, new anz());
        eD = new ajw("packed/spells/mystic/Blackout/Blackout.ogg", Sound.class, new Array[0]);
        eE = new ajw("packed/spells/mystic/BlessingSunAndMoon/BlessingSunAndMoon_on_tick.atlas", TextureAtlas.class, new aoa());
        eF = new ajw("packed/spells/mystic/BlessingSunAndMoon/BlessingSunAndMoon.ogg", Sound.class, new Array[0]);
        eG = new ajw("packed/spells/mystic/Cleanse/Cleanse_on_tick.atlas", TextureAtlas.class, new aob());
        eH = new ajw("packed/spells/mystic/Cleanse/Cleanse.ogg", Sound.class, new Array[0]);
        eI = new ajw("packed/spells/mystic/CosmicInfusion/CosmicInfusion.ogg", Sound.class, new Array[0]);
        eJ = new ajw("packed/spells/mystic/Disenchant/Disenchant_on_tick.atlas", TextureAtlas.class, new aoc());
        eK = new ajw("packed/spells/mystic/Disenchant/Disenchant.ogg", Sound.class, new Array[0]);
        eL = new ajw("packed/spells/mystic/Divination/Divination_on_tick.atlas", TextureAtlas.class, new aod());
        eM = new ajw("packed/spells/mystic/Divination/Divination.ogg", Sound.class, new Array[0]);
        eN = new ajw("packed/spells/mystic/DreamOfProsperity/DreamOfProsperity_on_tick.atlas", TextureAtlas.class, new aog());
        eO = new ajw("packed/spells/mystic/DreamOfProsperity/DreamOfProsperity.ogg", Sound.class, new Array[0]);
        eP = new ajw("packed/spells/mystic/HealingVision/HealingVision_on_tick.atlas", TextureAtlas.class, new aoh());
        eQ = new ajw("packed/spells/mystic/HealingVision/HealingVision.ogg", Sound.class, new Array[0]);
        eR = new ajw("packed/spells/mystic/LifeStream/LifeStream_on_tick.atlas", TextureAtlas.class, new aoi());
        eS = new ajw("packed/spells/mystic/LifeStream/LifeStream.ogg", Sound.class, new Array[0]);
        eT = new ajw("packed/spells/mystic/LightsWrath/LightsWrath_on_tick.atlas", TextureAtlas.class, new aoj());
        eU = new ajw("packed/spells/mystic/LightsWrath/LightsWrath.ogg", Sound.class, new Array[0]);
        eV = new ajw("packed/spells/mystic/ManaTap/ManaTap_on_tick.atlas", TextureAtlas.class, new aok());
        eW = new ajw("packed/spells/mystic/ManaTap/ManaTap.ogg", Sound.class, new Array[0]);
        eX = new ajw("packed/spells/mystic/SpiritForm/SpiritForm_on_tick.atlas", TextureAtlas.class, new aol());
        eY = new ajw("packed/spells/mystic/SpiritForm/SpiritForm.ogg", Sound.class, new Array[0]);
        eZ = new ajw("packed/spells/mystic/TemporalBarrier/TemporalBarrier_on_tick.atlas", TextureAtlas.class, new aom());
        fa = new ajw("packed/spells/mystic/TemporalBarrier/TemporalBarrier.ogg", Sound.class, new Array[0]);
        fb = new ajw("packed/spells/nihilist/Basic/Basic.atlas", TextureAtlas.class, new aon());
        fc = new ajw("packed/spells/nihilist/Basic/Basic.ogg", Sound.class, new Array[0]);
        fd = new ajw("packed/spells/nihilist/Basic/BasicImpact.atlas", TextureAtlas.class, new aoo());
        fe = new ajw("packed/spells/nihilist/Basic/BasicImpact.ogg", Sound.class, new Array[0]);
        ff = new ajw("packed/spells/nihilist/Amalgamation/Amalgamation_on_tick.atlas", TextureAtlas.class, new aop());
        fg = new ajw("packed/spells/nihilist/Blink/Blink_on_tick.atlas", TextureAtlas.class, new aor());
        fh = new ajw("packed/spells/nihilist/Blink/Blink.ogg", Sound.class, new Array[0]);
        fi = new ajw("packed/spells/nihilist/ChaosWave/ChaosWave_on_tick.atlas", TextureAtlas.class, new aos());
        fj = new ajw("packed/spells/nihilist/ChaosWave/ChaosWave.ogg", Sound.class, new Array[0]);
        fk = new ajw("packed/spells/nihilist/ChaosWave/ChaosWave_on_impact.atlas", TextureAtlas.class, new aot());
        fl = new ajw("packed/spells/nihilist/ChaosWave/ChaosWaveImpact.ogg", Sound.class, new Array[0]);
        fm = new ajw("packed/spells/nihilist/DarkInoculation/DarkInoculation.ogg", Sound.class, new Array[0]);
        fn = new ajw("packed/spells/nihilist/Infuse/Infuse_on_tick.atlas", TextureAtlas.class, new aou());
        fo = new ajw("packed/spells/nihilist/Infuse/Infuse.ogg", Sound.class, new Array[0]);
        fp = new ajw("packed/spells/nihilist/Karma/Karma_on_tick.atlas", TextureAtlas.class, new aov());
        fq = new ajw("packed/spells/nihilist/Karma/Karma.ogg", Sound.class, new Array[0]);
        fr = new ajw("packed/spells/nihilist/LingeringDemise/LingeringDemise_on_tick.atlas", TextureAtlas.class, new aow());
        fs = new ajw("packed/spells/nihilist/LingeringDemise/LingeringDemise.ogg", Sound.class, new Array[0]);
        ft = new ajw("packed/spells/nihilist/MindLeech/MindLeech_on_tick.atlas", TextureAtlas.class, new aox());
        fu = new ajw("packed/spells/nihilist/MindLeech/MindLeech.ogg", Sound.class, new Array[0]);
        fv = new ajw("packed/spells/nihilist/OrbOfAbsolution/OrbOfAbsolution_on_tick.atlas", TextureAtlas.class, new aoy());
        fw = new ajw("packed/spells/nihilist/OrbOfAbsolution/OrbOfAbsolution.ogg", Sound.class, new Array[0]);
        fx = new ajw("packed/spells/nihilist/OrbOfReplenishment/OrbOfReplenishment_on_tick.atlas", TextureAtlas.class, new aoz());
        fy = new ajw("packed/spells/nihilist/OrbOfReplenishment/OrbOfReplenishment.ogg", Sound.class, new Array[0]);
        fz = new ajw("packed/spells/nihilist/OrbOfSmoke/OrbOfSmoke_on_tick.atlas", TextureAtlas.class, new apa());
        fA = new ajw("packed/spells/nihilist/OrbOfSmoke/OrbOfSmoke.ogg", Sound.class, new Array[0]);
        fB = new ajw("packed/spells/nihilist/OrbOfWisdom/OrbOfWisdom_on_tick.atlas", TextureAtlas.class, new apc());
        fC = new ajw("packed/spells/nihilist/OrbOfWisdom/OrbOfWisdom.ogg", Sound.class, new Array[0]);
        fD = new ajw("packed/spells/nihilist/Rockslide/Rockslide_on_tick.atlas", TextureAtlas.class, new apd());
        fE = new ajw("packed/spells/nihilist/Rockslide/Rockslide.ogg", Sound.class, new Array[0]);
        fF = new ajw("packed/spells/nihilist/ShadowAffinity/ShadowAffinity_on_tick.atlas", TextureAtlas.class, new ape());
        fG = new ajw("packed/spells/nihilist/ShadowAffinity/ShadowAffinity.ogg", Sound.class, new Array[0]);
        fH = new ajw("packed/spells/nihilist/SiphonMana/SiphonMana_on_tick.atlas", TextureAtlas.class, new apf());
        fI = new ajw("packed/spells/nihilist/SiphonMana/SiphonMana.ogg", Sound.class, new Array[0]);
        fJ = new ajw("packed/spells/nihilist/SpellBreaker/SpellBreaker_on_tick.atlas", TextureAtlas.class, new apg());
        fK = new ajw("packed/spells/nihilist/SpellBreaker/SpellBreaker.ogg", Sound.class, new Array[0]);
        fL = new ajw("packed/spells/paladin/Basic/Basic.atlas", TextureAtlas.class, new aph());
        fM = new ajw("packed/spells/paladin/Basic/Basic.ogg", Sound.class, new Array[0]);
        fN = new ajw("packed/spells/paladin/AngelicStrike/AngelicStrike_on_tick.atlas", TextureAtlas.class, new api());
        fO = new ajw("packed/spells/paladin/AngelicStrike/AngelicStrike.ogg", Sound.class, new Array[0]);
        fP = new ajw("packed/spells/paladin/BlazingSlash/BlazingSlash_on_tick.atlas", TextureAtlas.class, new apj());
        fQ = new ajw("packed/spells/paladin/BlazingSlash/BlazingSlash.ogg", Sound.class, new Array[0]);
        fR = new ajw("packed/spells/paladin/CelestialProtection/CelestialProtection_on_tick.atlas", TextureAtlas.class, new apk());
        fS = new ajw("packed/spells/paladin/CelestialProtection/CelestialProtection.ogg", Sound.class, new Array[0]);
        fT = new ajw("packed/spells/paladin/DivineLight/DivineLight_on_tick.atlas", TextureAtlas.class, new apl());
        fU = new ajw("packed/spells/paladin/DivineLight/DivineLight.ogg", Sound.class, new Array[0]);
        fV = new ajw("packed/spells/paladin/HeavensGuidance/HeavensGuidance_on_tick.atlas", TextureAtlas.class, new apn());
        fW = new ajw("packed/spells/paladin/HeavensGuidance/HeavensGuidance.ogg", Sound.class, new Array[0]);
        fX = new ajw("packed/spells/paladin/GlimmerOfLight/GlimmerOfLight.ogg", Sound.class, new Array[0]);
        fY = new ajw("packed/spells/paladin/HeavensStrike/HeavensStrike_on_tick.atlas", TextureAtlas.class, new apo());
        fZ = new ajw("packed/spells/paladin/HeavensStrike/HeavensStrike.ogg", Sound.class, new Array[0]);
        ga = new ajw("packed/spells/paladin/HolyNova/HolyNova_on_tick.atlas", TextureAtlas.class, new app());
        gb = new ajw("packed/spells/paladin/HolyNova/HolyNova.ogg", Sound.class, new Array[0]);
        gc = new ajw("packed/spells/paladin/InfernalStrike/InfernalStrike_on_tick.atlas", TextureAtlas.class, new apq());
        gd = new ajw("packed/spells/paladin/InfernalStrike/InfernalStrike.ogg", Sound.class, new Array[0]);
        ge = new ajw("packed/spells/paladin/Prudence/Prudence_on_tick.atlas", TextureAtlas.class, new apr());
        gf = new ajw("packed/spells/paladin/Prudence/Prudence.ogg", Sound.class, new Array[0]);
        gg = new ajw("packed/spells/paladin/Purify/Purify_on_tick.atlas", TextureAtlas.class, new aps());
        gh = new ajw("packed/spells/paladin/Purify/Purify.ogg", Sound.class, new Array[0]);
        gi = new ajw("packed/spells/paladin/Sanctuary/Sanctuary_on_tick.atlas", TextureAtlas.class, new apt());
        gj = new ajw("packed/spells/paladin/ShatteringSlash/ShatteringSlash_on_tick.atlas", TextureAtlas.class, new apu());
        gk = new ajw("packed/spells/paladin/ShatteringSlash/ShatteringSlash.ogg", Sound.class, new Array[0]);
        gl = new ajw("packed/spells/paladin/StreamOfLight/StreamOfLight_on_tick.atlas", TextureAtlas.class, new apv());
        gm = new ajw("packed/spells/paladin/StreamOfLight/StreamOfLight.ogg", Sound.class, new Array[0]);
        gn = new ajw("packed/spells/paladin/StreamOfLight/StreamOfLight_on_impact.atlas", TextureAtlas.class, new apw());
        go = new ajw("packed/spells/paladin/StreamOfLight/StreamOfLightImpact.ogg", Sound.class, new Array[0]);
        gp = new ajw("packed/spells/paladin/Valor/Valor_on_tick.atlas", TextureAtlas.class, new apy());
        gq = new ajw("packed/spells/paladin/Valor/Valor.ogg", Sound.class, new Array[0]);
        gr = new ajw("packed/spells/paladin/WrathOfHeaven/WrathOfHeaven_on_tick.atlas", TextureAtlas.class, new apz());
        gs = new ajw("packed/spells/paladin/WrathOfHeaven/WrathOfHeaven.ogg", Sound.class, new Array[0]);
        gt = new ajw("packed/spells/ranger/Basic/Basic.atlas", TextureAtlas.class, new aqa());
        gu = new ajw("packed/spells/ranger/Basic/Basic.ogg", Sound.class, new Array[0]);
        gv = new ajw("packed/spells/ranger/Basic/BasicImpact.atlas", TextureAtlas.class, new aqb());
        gw = new ajw("packed/spells/ranger/Basic/BasicImpact.ogg", Sound.class, new Array[0]);
        gx = new ajw("packed/spells/ranger/Precision/Precision_on_tick.atlas", TextureAtlas.class, new aqc());
        gy = new ajw("packed/spells/ranger/SilencingShot/SilencingShot_on_tick.atlas", TextureAtlas.class, new aqd());
        gz = new ajw("packed/spells/ranger/SilencingShot/SilencingShot.ogg", Sound.class, new Array[0]);
        gA = new ajw("packed/spells/ranger/SilencingShot/SilencingShot_on_impact.atlas", TextureAtlas.class, new aqe());
        gB = new ajw("packed/spells/ranger/SilencingShot/SilencingShotImpact.ogg", Sound.class, new Array[0]);
        gC = new ajw("packed/spells/ranger/AetherShot/AetherShot_on_tick.atlas", TextureAtlas.class, new aqf());
        gD = new ajw("packed/spells/ranger/AetherShot/AetherShot.ogg", Sound.class, new Array[0]);
        gE = new ajw("packed/spells/ranger/AetherShot/AetherShot_on_impact.atlas", TextureAtlas.class, new aqg());
        gF = new ajw("packed/spells/ranger/AetherShot/AetherShotImpact.ogg", Sound.class, new Array[0]);
        gG = new ajw("packed/spells/ranger/HobblingArrow/HobblingArrow_on_tick.atlas", TextureAtlas.class, new aqh());
        gH = new ajw("packed/spells/ranger/HobblingArrow/QuickShot.ogg", Sound.class, new Array[0]);
        gI = new ajw("packed/spells/ranger/HobblingArrow/HobblingArrow_on_impact.atlas", TextureAtlas.class, new aqj());
        gJ = new ajw("packed/spells/ranger/HobblingArrow/QuickShotImpact.ogg", Sound.class, new Array[0]);
        gK = new ajw("packed/spells/ranger/HeadShot/HeadShot_on_tick.atlas", TextureAtlas.class, new aqk());
        gL = new ajw("packed/spells/ranger/HeadShot/HeadShot.ogg", Sound.class, new Array[0]);
        gM = new ajw("packed/spells/ranger/HeadShot/HeadShot_on_impact.atlas", TextureAtlas.class, new aql());
        gN = new ajw("packed/spells/ranger/HeadShot/HeadShotImpact.ogg", Sound.class, new Array[0]);
        gO = new ajw("packed/spells/ranger/LightningArrow/LightningArrow_on_tick.atlas", TextureAtlas.class, new aqm());
        gP = new ajw("packed/spells/ranger/LightningArrow/LightningArrow.ogg", Sound.class, new Array[0]);
        gQ = new ajw("packed/spells/ranger/LightningArrow/LightningArrow_on_impact.atlas", TextureAtlas.class, new aqn());
        gR = new ajw("packed/spells/ranger/LightningArrow/LightningArrowImpact.ogg", Sound.class, new Array[0]);
        gS = new ajw("packed/spells/ranger/NightmareShot/NightmareShot_on_tick.atlas", TextureAtlas.class, new aqo());
        gT = new ajw("packed/spells/ranger/NightmareShot/NightmareShot.ogg", Sound.class, new Array[0]);
        gU = new ajw("packed/spells/ranger/NightmareShot/NightmareShot_on_impact.atlas", TextureAtlas.class, new aqp());
        gV = new ajw("packed/spells/ranger/NightmareShot/NightmareShotImpact.ogg", Sound.class, new Array[0]);
        gW = new ajw("packed/spells/ranger/ElementalArrow/ElementalArrow_on_tick.atlas", TextureAtlas.class, new aqq());
        gX = new ajw("packed/spells/ranger/ElementalArrow/ElementalArrow.ogg", Sound.class, new Array[0]);
        gY = new ajw("packed/spells/ranger/ElementalArrow/ElementalArrow_on_impact.atlas", TextureAtlas.class, new aqr());
        gZ = new ajw("packed/spells/ranger/ElementalArrow/ElementalArrowImpact.ogg", Sound.class, new Array[0]);
        ha = new ajw("packed/spells/ranger/RainOfArrows/RainOfArrows_on_tick.atlas", TextureAtlas.class, new aqs());
        hb = new ajw("packed/spells/ranger/RainOfArrows/RainOfArrows.ogg", Sound.class, new Array[0]);
        hc = new ajw("packed/spells/ranger/AntidotePotion/AntidotePotion_on_tick.atlas", TextureAtlas.class, new aqu());
        hd = new ajw("packed/spells/ranger/RejuvinationPotion/RejuvinationPotion_on_tick.atlas", TextureAtlas.class, new aqv());
        he = new ajw("packed/spells/ranger/RejuvinationPotion/RejuvenationPotion.ogg", Sound.class, new Array[0]);
        hf = new ajw("packed/spells/ranger/MarkOfDeath/MarkOfDeath_on_tick.atlas", TextureAtlas.class, new aqw());
        hg = new ajw("packed/spells/ranger/PoisonousShot/PoisonousShot_on_tick.atlas", TextureAtlas.class, new aqx());
        hh = new ajw("packed/spells/ranger/PoisonousShot/PoisonousShot.ogg", Sound.class, new Array[0]);
        hi = new ajw("packed/spells/ranger/PoisonousShot/PoisonousShot_on_impact.atlas", TextureAtlas.class, new aqy());
        hj = new ajw("packed/spells/ranger/PoisonousShot/PoisonousShotImpact.ogg", Sound.class, new Array[0]);
        hk = new ajw("packed/spells/ranger/Quicksand/Quicksand_on_tick.atlas", TextureAtlas.class, new aqz());
        hl = new ajw("packed/spells/ranger/Quicksand/Quicksand.ogg", Sound.class, new Array[0]);
        hm = new ajw("packed/spells/ranger/Vigor/Vigor_on_tick.atlas", TextureAtlas.class, new ara());
        hn = new ajw("packed/spells/ranger/Vigor/Vigor.ogg", Sound.class, new Array[0]);
        ho = new ajw("packed/spells/scholar/Basic/Basic.atlas", TextureAtlas.class, new arb());
        hp = new ajw("packed/spells/scholar/Basic/Basic.ogg", Sound.class, new Array[0]);
        hq = new ajw("packed/spells/scholar/Basic/BasicImpact.atlas", TextureAtlas.class, new arc());
        hr = new ajw("packed/spells/scholar/Basic/BasicImpact.ogg", Sound.class, new Array[0]);
        hs = new ajw("packed/spells/scholar/Armageddon/Armageddon_on_tick.atlas", TextureAtlas.class, new ard());
        ht = new ajw("packed/spells/scholar/Armageddon/Armageddon.ogg", Sound.class, new Array[0]);
        hu = new ajw("packed/spells/scholar/EtherealBindings/EtherealBindings_on_tick.atlas", TextureAtlas.class, new arf());
        hv = new ajw("packed/spells/scholar/EtherealBindings/EtherealBindings.ogg", Sound.class, new Array[0]);
        hw = new ajw("packed/spells/scholar/GospelOfDefiance/GospelOfDefiance_on_tick.atlas", TextureAtlas.class, new arg());
        hx = new ajw("packed/spells/scholar/GospelOfDefiance/GospelOfDefiance.ogg", Sound.class, new Array[0]);
        hy = new ajw("packed/spells/scholar/GospelOfHarmony/GospelOfHarmony_on_tick.atlas", TextureAtlas.class, new arh());
        hz = new ajw("packed/spells/scholar/GospelOfHarmony/GospelOfHarmony.ogg", Sound.class, new Array[0]);
        hA = new ajw("packed/spells/scholar/GospelOfOnslaught/GospelOfOnslaught_on_tick.atlas", TextureAtlas.class, new ari());
        hB = new ajw("packed/spells/scholar/GospelOfOnslaught/GospelOfOnslaught.ogg", Sound.class, new Array[0]);
        hC = new ajw("packed/spells/scholar/GospelOfPurity/GospelOfPurity_on_tick.atlas", TextureAtlas.class, new arj());
        hD = new ajw("packed/spells/scholar/GospelOfPurity/GospelOfPurity.ogg", Sound.class, new Array[0]);
        hE = new ajw("packed/spells/scholar/Immortality/Immortality_on_tick.atlas", TextureAtlas.class, new ark());
        hF = new ajw("packed/spells/scholar/Immortality/Immortality.ogg", Sound.class, new Array[0]);
        hG = new ajw("packed/spells/scholar/Judgment/Judgment_on_tick.atlas", TextureAtlas.class, new arl());
        hH = new ajw("packed/spells/scholar/Judgment/Judgment.ogg", Sound.class, new Array[0]);
        hI = new ajw("packed/spells/scholar/LifeBurst/LifeBurst_on_tick.atlas", TextureAtlas.class, new arm());
        hJ = new ajw("packed/spells/scholar/LifeBurst/LifeBurst.ogg", Sound.class, new Array[0]);
        hK = new ajw("packed/spells/scholar/Mesmerize/Mesmerize_on_tick.atlas", TextureAtlas.class, new arn());
        hL = new ajw("packed/spells/scholar/Mesmerize/Mesmerize.ogg", Sound.class, new Array[0]);
        hM = new ajw("packed/spells/scholar/Portal/Portal_on_tick.atlas", TextureAtlas.class, new aro());
        hN = new ajw("packed/spells/scholar/Portal/Portal.ogg", Sound.class, new Array[0]);
        hO = new ajw("packed/spells/scholar/RiteOfPassage/RiteOfPassage_on_tick.atlas", TextureAtlas.class, new arq());
        hP = new ajw("packed/spells/scholar/RiteOfPassage/RiteOfPassage.ogg", Sound.class, new Array[0]);
        hQ = new ajw("packed/spells/scholar/Silence/Silence_on_tick.atlas", TextureAtlas.class, new arr());
        hR = new ajw("packed/spells/scholar/Silence/Silence.ogg", Sound.class, new Array[0]);
        hS = new ajw("packed/spells/scholar/TransferLife/TransferLife_on_tick.atlas", TextureAtlas.class, new ars());
        hT = new ajw("packed/spells/scholar/TransferLife/TransferLife.ogg", Sound.class, new Array[0]);
        hU = new ajw("packed/spells/scholar/Truth/Truth_on_tick.atlas", TextureAtlas.class, new art());
        hV = new ajw("packed/spells/wizard/AganothsDescent/AganothsDescent_on_tick.atlas", TextureAtlas.class, new aru());
        hW = new ajw("packed/spells/wizard/AganothsDescent/AganothsDescent.ogg", Sound.class, new Array[0]);
        hX = new ajw("packed/spells/wizard/Basic/Basic.atlas", TextureAtlas.class, new arv());
        hY = new ajw("packed/spells/wizard/Basic/Basic.ogg", Sound.class, new Array[0]);
        hZ = new ajw("packed/spells/wizard/Basic/BasicImpact.atlas", TextureAtlas.class, new arw());
        ia = new ajw("packed/spells/wizard/Basic/BasicImpact.ogg", Sound.class, new Array[0]);
        ib = new ajw("packed/spells/wizard/Combust/Combust_on_tick.atlas", TextureAtlas.class, new arx());
        ic = new ajw("packed/spells/wizard/Combust/Combust.ogg", Sound.class, new Array[0]);
        id = new ajw("packed/spells/wizard/Counterspell/Counterspell_on_tick.atlas", TextureAtlas.class, new ary());
        ie = new ajw("packed/spells/wizard/Counterspell/Counterspell.ogg", Sound.class, new Array[0]);
        cfr_renamed_6 = new ajw("packed/spells/wizard/ChillingArmor/ChillingArmor_on_tick.atlas", TextureAtlas.class, new arz());
        ig = new ajw("packed/spells/wizard/ChillingArmor/ChillingArmor.ogg", Sound.class, new Array[0]);
        ih = new ajw("packed/spells/wizard/FlashFreeze/FlashFreezeDebuff_on_tick.atlas", TextureAtlas.class, new asb());
        ii = new ajw("packed/spells/wizard/Crystallize/Crystallize.ogg", Sound.class, new Array[0]);
        ij = new ajw("packed/spells/wizard/EyeOfTheStorm/EyeOfTheStorm_on_tick.atlas", TextureAtlas.class, new asc());
        ik = new ajw("packed/spells/wizard/EyeOfTheStorm/EyeOfTheStorm.ogg", Sound.class, new Array[0]);
        il = new ajw("packed/spells/wizard/Fireball/Fireball_on_tick.atlas", TextureAtlas.class, new asd());
        im = new ajw("packed/spells/wizard/Fireball/Fireball_on_impact.atlas", TextureAtlas.class, new ase());
        in = new ajw("packed/spells/wizard/Fireball/Fireball.ogg", Sound.class, new Array[0]);
        io = new ajw("packed/spells/wizard/Fireball/FireballImpact.ogg", Sound.class, new Array[0]);
        ip = new ajw("packed/spells/wizard/Frostbolt/Frostbolt_on_tick.atlas", TextureAtlas.class, new asf());
        iq = new ajw("packed/spells/wizard/Frostbolt/Frostbolt.ogg", Sound.class, new Array[0]);
        ir = new ajw("packed/spells/wizard/Frostbolt/Frostbolt_on_impact.atlas", TextureAtlas.class, new asg());
        is = new ajw("packed/spells/wizard/Frostbolt/FrostboltImpact.ogg", Sound.class, new Array[0]);
        it = new ajw("packed/spells/wizard/FlashFreeze/FlashFreeze_on_tick.atlas", TextureAtlas.class, new ash());
        iu = new ajw("packed/spells/wizard/FlashFreeze/FlashFreeze.ogg", Sound.class, new Array[0]);
        iv = new ajw("packed/spells/wizard/FlashFreeze/FlashFreezeDebuff.ogg", Sound.class, new Array[0]);
        iw = new ajw("packed/spells/wizard/Geyser/Geyser_on_tick.atlas", TextureAtlas.class, new asi());
        ix = new ajw("packed/spells/wizard/Geyser/Geyser.ogg", Sound.class, new Array[0]);
        iy = new ajw("packed/spells/wizard/IceSpikes/IceSpikes_on_tick.atlas", TextureAtlas.class, new asj());
        iz = new ajw("packed/spells/wizard/IceSpikes/IceSpikes.ogg", Sound.class, new Array[0]);
        iA = new ajw("packed/spells/wizard/LightningStrike/LightningStrike_on_tick.atlas", TextureAtlas.class, new ask());
        iB = new ajw("packed/spells/wizard/LightningStrike/LightningStrike.ogg", Sound.class, new Array[0]);
        iC = new ajw("packed/spells/wizard/MagicMissiles/MagicMissiles.atlas", TextureAtlas.class, new asn());
        iD = new ajw("packed/spells/wizard/MagicMissiles/MagicMissiles.ogg", Sound.class, new Array[0]);
        iE = new ajw("packed/spells/wizard/MagicMissiles/MagicMissilesImpact.atlas", TextureAtlas.class, new aso());
        iF = new ajw("packed/spells/wizard/MasterOfMagic/MasterOfMagic_on_tick.atlas", TextureAtlas.class, new asp());
        iG = new ajw("packed/spells/wizard/MasterOfMagic/MasterOfMagic.ogg", Sound.class, new Array[0]);
        iH = new ajw("packed/spells/wizard/Meteor/Meteor_on_tick.atlas", TextureAtlas.class, new asq());
        iI = new ajw("packed/spells/wizard/Meteor/Meteor.ogg", Sound.class, new Array[0]);
        iJ = new ajw("packed/spells/wizard/RunicShield/RunicShield_on_tick.atlas", TextureAtlas.class, new asr());
        iK = new ajw("packed/spells/wizard/RunicShield/RunicShield.ogg", Sound.class, new Array[0]);
        iL = new ajw("packed/spells/wizard/Sheepify/Sheepify.ogg", Sound.class, new Array[0]);
        iM = new ajw("packed/spells/wizard/ShockNova/ShockNova_on_tick.atlas", TextureAtlas.class, new ass());
        iN = new ajw("packed/spells/wizard/ShockNova/ShockNova.ogg", Sound.class, new Array[0]);
        iO = new ajw("packed/spells/wizard/Teleport/Teleport_on_tick.atlas", TextureAtlas.class, new ast());
        iP = new ajw("packed/spells/wizard/Teleport/Teleport.ogg", Sound.class, new Array[0]);
        iQ = new ajw("packed/spells/wizard/ThundersWrath/ThundersWrath_on_tick.atlas", TextureAtlas.class, new asu());
        iR = new ajw("packed/spells/wizard/ThundersWrath/ThundersWrath.ogg", Sound.class, new Array[0]);
        iS = new ajw("packed/spells/wizard/VolcanicEruption/VolcanicEruption.atlas", TextureAtlas.class, new asv());
        iT = new ajw("packed/spells/wizard/VolcanicEruption/VolcanicEruption-2.ogg", Sound.class, new Array[0]);
        iU = new ajw("misc/sound/click10.ogg", Sound.class, new Array[0]);
        iV = new ajw("misc/sound/spell_fail_7.ogg", Sound.class, new Array[0]);
        iW = new ajw("packed/items/ItemIcons-11.atlas", TextureAtlas.class, new asw());
        iX = new ajw("packed/items/CommonBag-1.atlas", TextureAtlas.class, new asy());
        iY = new ajw("packed/items/UncommonBag-1.atlas", TextureAtlas.class, new asz());
        iZ = new ajw("packed/items/RareBag-1.atlas", TextureAtlas.class, new ata());
        ja = new ajw("packed/items/EpicBag-1.atlas", TextureAtlas.class, new atb());
        jb = new ajw("packed/items/LegendaryBag-1.atlas", TextureAtlas.class, new atc());
        jc = new ajw("packed/icons/SpellIcons-10.atlas", TextureAtlas.class, new atd());
        jd = new ajw("packed/icons/ClassIcons-v4.atlas", TextureAtlas.class, new ate());
        je = new ajw("packed/icons/flags.atlas", TextureAtlas.class, new atf());
        jf = new ajw("packed/ui/effects/GCD_Default.atlas", TextureAtlas.class, new atg());
        jg = new ajw("packed/ui/effects/GCD_Flash.atlas", TextureAtlas.class, new ath());
        jh = new ajw("packed/ui/effects/GCD_Red.atlas", TextureAtlas.class, new atj());
        ji = new ajw("packed/ui/effects/GCD_Glow.atlas", TextureAtlas.class, new atk());
        jj = new ajw("packed/ui/effects/Activation_RED.atlas", TextureAtlas.class, new atl());
        jk = new ajw("packed/ui/effects/Activation_GREEN.atlas", TextureAtlas.class, new atm());
        jl = new ajw("packed/profile/ProfileBackgrounds.atlas", TextureAtlas.class, new atn());
        jm = new ajw("packed/profile/ProfileBorders.atlas", TextureAtlas.class, new ato());
        jn = new ajw("packed/profile/effects/BlackSmoke.atlas", TextureAtlas.class, new atp());
        jo = new ajw("packed/profile/effects/Bubbles.atlas", TextureAtlas.class, new atq());
        jp = new ajw("packed/profile/effects/Clouds.atlas", TextureAtlas.class, new atr());
        jq = new ajw("packed/profile/effects/Clouds2.atlas", TextureAtlas.class, new ats());
        jr = new ajw("packed/profile/effects/Hearts.atlas", TextureAtlas.class, new atu());
        js = new ajw("packed/profile/effects/Lightning.atlas", TextureAtlas.class, new atv());
        jt = new ajw("packed/profile/effects/Lightning2.atlas", TextureAtlas.class, new atw());
        ju = new ajw("packed/profile/effects/PhoenixRed.atlas", TextureAtlas.class, new atx());
        jv = new ajw("packed/profile/effects/Rain.atlas", TextureAtlas.class, new aty());
        jw = new ajw("packed/profile/effects/Rainbow.atlas", TextureAtlas.class, new atz());
        jx = new ajw("packed/profile/effects/Snow.atlas", TextureAtlas.class, new aua());
        jy = new ajw("packed/profile/effects/Stars.atlas", TextureAtlas.class, new aub());
        jz = new ajw("packed/profile/effects/Tornado.atlas", TextureAtlas.class, new auc());
        jA = new ajw("packed/profile/effects/WhiteSmoke.atlas", TextureAtlas.class, new aud());
        jB = new ajw("packed/profile/effects/Wisps.atlas", TextureAtlas.class, new auf());
        jC = new ajw("unpacked/screens/splash_launch12.png", Texture.class, new Array[0]);
        jD = new ajw("unpacked/screens/BlackForest2.png", Texture.class, new Array[0]);
        jE = new ajw("unpacked/screens/KingsAscent2.png", Texture.class, new Array[0]);
        jF = new ajw("unpacked/screens/TheUnderworld2.png", Texture.class, new Array[0]);
        jG = new ajw("unpacked/screens/Kazaar2.png", Texture.class, new Array[0]);
        jH = new ajw("unpacked/screens/Magisterium2.png", Texture.class, new Array[0]);
        jI = new ajw("packed/spells/assassin/cast.ogg", Sound.class, new Array[0]);
        jJ = new ajw("packed/spells/elder/cast.ogg", Sound.class, new Array[0]);
        jK = new ajw("packed/spells/lich/cast.ogg", Sound.class, new Array[0]);
        jL = new ajw("packed/spells/mystic/cast.ogg", Sound.class, new Array[0]);
        jM = new ajw("packed/spells/nihilist/cast.ogg", Sound.class, new Array[0]);
        jN = new ajw("packed/spells/paladin/cast.ogg", Sound.class, new Array[0]);
        jO = new ajw("packed/spells/ranger/attack1.ogg", Sound.class, new Array[0]);
        jP = new ajw("packed/spells/ranger/cast1.ogg", Sound.class, new Array[0]);
        jQ = new ajw("packed/spells/scholar/cast.ogg", Sound.class, new Array[0]);
        jR = new ajw("packed/spells/wizard/cast.ogg", Sound.class, new Array[0]);
        jS = new ajw("misc/sound/spell_drop_op32.ogg", Sound.class, new Array[0]);
        jT = new ajw("misc/sound/UI_spell_drag.ogg", Sound.class, new Array[0]);
        jU = new ajw("misc/sound/gold1.ogg", Sound.class, new Array[0]);
        jV = new ajw("misc/sound/gold2.ogg", Sound.class, new Array[0]);
        jW = new ajw("misc/sound/gold3.ogg", Sound.class, new Array[0]);
        jX = new ajw("misc/sound/items/trinket_drop_1.ogg", Sound.class, new Array[0]);
        jY = new ajw("misc/sound/items/inventory_open.ogg", Sound.class, new Array[0]);
        jZ = new ajw("misc/sound/items/item_drag_5.ogg", Sound.class, new Array[0]);
        ka = new ajw("misc/sound/items/bag_whoosh_11.ogg", Sound.class, new Array[0]);
        kb = new ajw("misc/sound/items/Ring.ogg", Sound.class, new Array[0]);
        kc = new ajw("misc/sound/items/amulet_drop_16.ogg", Sound.class, new Array[0]);
        kd = new ajw("misc/sound/items/trinket_drop_3.ogg", Sound.class, new Array[0]);
        ke = new ajw("misc/sound/items/cloth_drop.ogg", Sound.class, new Array[0]);
        kf = new ajw("misc/sound/items/leather_drop.ogg", Sound.class, new Array[0]);
        kg = new ajw("misc/sound/items/plate_drop.ogg", Sound.class, new Array[0]);
        kh = new ajw("misc/sound/items/bow_drop_5.ogg", Sound.class, new Array[0]);
        ki = new ajw("misc/sound/items/book_drop_3.ogg", Sound.class, new Array[0]);
        kj = new ajw("misc/sound/items/dagger_drop_2.ogg", Sound.class, new Array[0]);
        kk = new ajw("misc/sound/items/orb_drop_9.ogg", Sound.class, new Array[0]);
        kl = new ajw("misc/sound/items/sword_drop_6.ogg", Sound.class, new Array[0]);
        km = new ajw("misc/sound/items/2h_sword_drop_6.ogg", Sound.class, new Array[0]);
        kn = new ajw("misc/sound/items/staff_drop_2.ogg", Sound.class, new Array[0]);
        ko = new ajw("misc/sound/items/wand_drop_3.ogg", Sound.class, new Array[0]);
        kp = new ajw("misc/sound/items/essence_use_2.ogg", Sound.class, new Array[0]);
        kq = new ajw("misc/sound/items/rare_drop.ogg", Sound.class, new Array[0]);
        kr = new ajw("misc/sound/items/epic_drop.ogg", Sound.class, new Array[0]);
        ks = new ajw("misc/sound/items/legendary_drop.ogg", Sound.class, new Array[0]);
        kt = new ajw("misc/sound/spell_drop_op18.ogg", Sound.class, new Array[0]);
        ku = new ajw("misc/sound/UI_party_invite.ogg", Sound.class, new Array[0]);
        kv = new ajw("misc/sound/UI_message_receive.ogg", Sound.class, new Array[0]);
        kw = new ajw("misc/sound/UI_find_game.ogg", Sound.class, new Array[0]);
        kx = new ajw("misc/sound/UI_find_game_cancel.ogg", Sound.class, new Array[0]);
        ky = new ajw("misc/sound/UI_GM_announcement.ogg", Sound.class, new Array[0]);
        kz = new ajw("misc/sound/Unlock_Gold_7.ogg", Sound.class, new Array[0]);
        kA = new ajw("misc/sound/drop_spell_op12.ogg", Sound.class, new Array[0]);
        kB = new ajw("misc/sound/UI_Queue.ogg", Sound.class, new Array[0]);
        kC = new ajw("misc/sound/UI_text_focus_4.ogg", Sound.class, new Array[0]);
        kD = new ajw("misc/sound/UI_target.ogg", Sound.class, new Array[0]);
        kE = new ajw("misc/sound/UI_untarget.ogg", Sound.class, new Array[0]);
        kF = new ajw("misc/sound/login_click_op1.ogg", Sound.class, new Array[0]);
        kG = new ajw("misc/sound/UI_login_fail_op1.ogg", Sound.class, new Array[0]);
        kH = new ajw("misc/sound/UI_login_success_op3.ogg", Sound.class, new Array[0]);
        kI = new ajw("misc/sound/UI_click_tab_op4.ogg", Sound.class, new Array[0]);
        kJ = new ajw("misc/sound/UI_click.ogg", Sound.class, new Array[0]);
        kK = new ajw("misc/sound/click1.ogg", Sound.class, new Array[0]);
        kL = new ajw("misc/sound/click.ogg", Sound.class, new Array[0]);
        kM = new ajw("packed/screens/play/arenas/Fight_Countdown_3.ogg", Sound.class, new Array[0]);
        kN = new ajw("misc/sound/sudden_death.ogg", Sound.class, new Array[0]);
        kO = new ajw("packed/screens/play/arenas/dark/dark_music.ogg", Sound.class, new Array[0]);
        kP = new ajw("packed/screens/play/arenas/dark/dark_ambient.ogg", Sound.class, new Array[0]);
        kQ = new ajw("packed/screens/play/arenas/snowy/snowy_music.ogg", Sound.class, new Array[0]);
        kR = new ajw("packed/screens/play/arenas/snowy/snowy_ambient.ogg", Sound.class, new Array[0]);
        kS = new ajw("packed/screens/play/arenas/forest/forest_music.ogg", Sound.class, new Array[0]);
        kT = new ajw("packed/screens/play/arenas/forest/forest_ambient.ogg", Sound.class, new Array[0]);
        kU = new ajw("packed/screens/play/arenas/desert/desert_ambient.ogg", Sound.class, new Array[0]);
        kV = new ajw("packed/screens/play/arenas/indoor/indoor_ambient.ogg", Sound.class, new Array[0]);
        kW = new ajw("misc/sound/VIC2.ogg", Sound.class, new Array[0]);
        kX = new ajw("misc/sound/DEF4.ogg", Sound.class, new Array[0]);
        kY = new ajw("misc/sound/BGLOOP.ogg", Sound.class, new Array[0]);
        kZ = new ajw("misc/sound/DEF3.ogg", Sound.class, new Array[0]);
        la = new ajw("packed/items/trinkets/TrinketOfResolve_on_tick.atlas", TextureAtlas.class, new aug());
        lb = new ajw("packed/items/trinkets/TrinketOfResolve2.ogg", Sound.class, new Array[0]);
        lc = new ajw("misc/sound/whisper_op4.ogg", Sound.class, new Array[0]);
        ld = new ajw("packed/spells/misc/Meditate/Meditate_on_tick.atlas", TextureAtlas.class, new auh());
        le = new ajw("packed/spells/misc/Meditate/Meditate.ogg", Sound.class, new Array[0]);
        var_ajw_arr_a = new ajw[]{var_ajw_a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, aA, aB, aC, aD, aE, aF, aG, aH, aI, aJ, aK, aL, aM, aN, aO, aP, aQ, aR, aS, aT, aU, aV, aW, aX, aY, aZ, ba, bb, bc, bd, be, bf, bg, bh, bi, bj, bk, bl, bm, bn, bo, bp, bq, br, bs, bt, bu, bv, bw, bx, by, bz, bA, bB, bC, bD, bE, bF, bG, bH, bI, bJ, bK, bL, bM, bN, bO, bP, bQ, bR, bS, bT, bU, bV, bW, bX, bY, bZ, ca, cb, cc, cd, ce, cf, cg, ch, ci, cj, ck, cl, cm, cn, co, cp, cq, cr, cs, ct, cu, cv, cw, cx, cy, cz, cA, cB, cC, cD, cE, cF, cG, cH, cI, cJ, cK, cL, cM, cN, cO, cP, cQ, cR, cS, cT, cU, cV, cW, cX, cY, cZ, da, db, dc, dd, de, df, dg, dh, di, dj, dk, dl, dm, dn, cfr_renamed_3, dp, dq, dr, ds, dt, du, dv, dw, dx, dy, dz, dA, dB, dC, dD, dE, dF, dG, dH, dI, dJ, dK, dL, dM, dN, dO, dP, dQ, dR, dS, dT, dU, dV, dW, dX, dY, dZ, ea, eb, ec, ed, ee, ef, eg, eh, ei, ej, ek, el, em, en, eo, ep, eq, er, es, et, eu, ev, ew, ex, ey, ez, eA, eB, eC, eD, eE, eF, eG, eH, eI, eJ, eK, eL, eM, eN, eO, eP, eQ, eR, eS, eT, eU, eV, eW, eX, eY, eZ, fa, fb, fc, fd, fe, ff, fg, fh, fi, fj, fk, fl, fm, fn, fo, fp, fq, fr, fs, ft, fu, fv, fw, fx, fy, fz, fA, fB, fC, fD, fE, fF, fG, fH, fI, fJ, fK, fL, fM, fN, fO, fP, fQ, fR, fS, fT, fU, fV, fW, fX, fY, fZ, ga, gb, gc, gd, ge, gf, gg, gh, gi, gj, gk, gl, gm, gn, go, gp, gq, gr, gs, gt, gu, gv, gw, gx, gy, gz, gA, gB, gC, gD, gE, gF, gG, gH, gI, gJ, gK, gL, gM, gN, gO, gP, gQ, gR, gS, gT, gU, gV, gW, gX, gY, gZ, ha, hb, hc, hd, he, hf, hg, hh, hi, hj, hk, hl, hm, hn, ho, hp, hq, hr, hs, ht, hu, hv, hw, hx, hy, hz, hA, hB, hC, hD, hE, hF, hG, hH, hI, hJ, hK, hL, hM, hN, hO, hP, hQ, hR, hS, hT, hU, hV, hW, hX, hY, hZ, ia, ib, ic, id, ie, cfr_renamed_6, ig, ih, ii, ij, ik, il, im, in, io, ip, iq, ir, is, it, iu, iv, iw, ix, iy, iz, iA, iB, iC, iD, iE, iF, iG, iH, iI, iJ, iK, iL, iM, iN, iO, iP, iQ, iR, iS, iT, iU, iV, iW, iX, iY, iZ, ja, jb, jc, jd, je, jf, jg, jh, ji, jj, jk, jl, jm, jn, jo, jp, jq, jr, js, jt, ju, jv, jw, jx, jy, jz, jA, jB, jC, jD, jE, jF, jG, jH, jI, jJ, jK, jL, jM, jN, jO, jP, jQ, jR, jS, jT, jU, jV, jW, jX, jY, jZ, ka, kb, kc, kd, ke, kf, kg, kh, ki, kj, kk, kl, km, kn, ko, kp, kq, kr, ks, kt, ku, kv, kw, kx, ky, kz, kA, kB, kC, kD, kE, kF, kG, kH, kI, kJ, kK, kL, kM, kN, kO, kP, kQ, kR, kS, kT, kU, kV, kW, kX, kY, kZ, la, lb, lc, ld, le};
    }
}

