/*
 * Decompiled with CFR 0.152.
 */
public final class zh
extends Enum<zh> {
    public static final /* enum */ zh var_zh_a;
    public static final /* enum */ zh b;
    public static final /* enum */ zh c;
    public static final /* enum */ zh d;
    public static final /* enum */ zh e;
    public static final /* enum */ zh f;
    public static final /* enum */ zh g;
    public static final /* enum */ zh h;
    public static final /* enum */ zh i;
    public static final /* enum */ zh j;
    public static final /* enum */ zh k;
    public static final /* enum */ zh l;
    public static final /* enum */ zh m;
    public static final /* enum */ zh n;
    public static final /* enum */ zh o;
    public static final /* enum */ zh p;
    public static final /* enum */ zh q;
    public static final /* enum */ zh r;
    public static final /* enum */ zh s;
    public static final /* enum */ zh t;
    public static final /* enum */ zh u;
    public static final /* enum */ zh v;
    public static final /* enum */ zh w;
    public static final /* enum */ zh x;
    public static final /* enum */ zh y;
    public static final /* enum */ zh z;
    public static final /* enum */ zh A;
    public static final /* enum */ zh B;
    public static final /* enum */ zh C;
    public static final /* enum */ zh D;
    public static final /* enum */ zh E;
    public static final /* enum */ zh F;
    public static final /* enum */ zh G;
    public static final /* enum */ zh H;
    public static final /* enum */ zh I;
    public static final /* enum */ zh J;
    public static final /* enum */ zh K;
    public static final /* enum */ zh L;
    public static final /* enum */ zh M;
    public static final /* enum */ zh N;
    public static final /* enum */ zh O;
    public static final /* enum */ zh P;
    public static final /* enum */ zh Q;
    public static final /* enum */ zh R;
    public static final /* enum */ zh S;
    public static final /* enum */ zh T;
    public static final /* enum */ zh U;
    public static final /* enum */ zh V;
    public static final /* enum */ zh W;
    public static final /* enum */ zh X;
    public static final /* enum */ zh Y;
    public static final /* enum */ zh Z;
    public static final /* enum */ zh aa;
    public static final /* enum */ zh ab;
    public static final /* enum */ zh ac;
    public static final /* enum */ zh ad;
    public static final /* enum */ zh ae;
    public static final /* enum */ zh af;
    public static final /* enum */ zh ag;
    public static final /* enum */ zh ah;
    public static final /* enum */ zh ai;
    public static final /* enum */ zh aj;
    public static final /* enum */ zh ak;
    public static final /* enum */ zh al;
    public static final /* enum */ zh am;
    public static final /* enum */ zh an;
    public static final /* enum */ zh ao;
    public static final /* enum */ zh ap;
    public static final /* enum */ zh aq;
    public static final /* enum */ zh ar;
    public static final /* enum */ zh as;
    public static final /* enum */ zh at;
    public static final /* enum */ zh au;
    public static final /* enum */ zh av;
    public static final /* enum */ zh aw;
    public static final /* enum */ zh ax;
    public static final /* enum */ zh ay;
    public static final /* enum */ zh az;
    public static final /* enum */ zh aA;
    public static final /* enum */ zh aB;
    public static final /* enum */ zh aC;
    public static final /* enum */ zh aD;
    public static final /* enum */ zh aE;
    public static final /* enum */ zh aF;
    public static final /* enum */ zh aG;
    public static final /* enum */ zh aH;
    public static final /* enum */ zh aI;
    public static final /* enum */ zh aJ;
    public static final /* enum */ zh aK;
    public static final /* enum */ zh aL;
    public static final /* enum */ zh aM;
    public static final /* enum */ zh aN;
    public static final /* enum */ zh aO;
    public static final /* enum */ zh aP;
    public static final /* enum */ zh aQ;
    public static final /* enum */ zh aR;
    public static final /* enum */ zh aS;
    public static final /* enum */ zh aT;
    public static final /* enum */ zh aU;
    public static final /* enum */ zh aV;
    public static final /* enum */ zh aW;
    public static final /* enum */ zh aX;
    public static final /* enum */ zh aY;
    public static final /* enum */ zh aZ;
    public static final /* enum */ zh ba;
    public static final /* enum */ zh bb;
    public static final /* enum */ zh bc;
    public static final /* enum */ zh bd;
    public static final /* enum */ zh be;
    public static final /* enum */ zh bf;
    public static final /* enum */ zh bg;
    public static final /* enum */ zh bh;
    public static final /* enum */ zh bi;
    public static final /* enum */ zh bj;
    public static final /* enum */ zh bk;
    public static final /* enum */ zh bl;
    public static final /* enum */ zh bm;
    public static final /* enum */ zh bn;
    public static final /* enum */ zh bo;
    public static final /* enum */ zh bp;
    public static final /* enum */ zh bq;
    public static final /* enum */ zh br;
    public static final /* enum */ zh bs;
    public static final /* enum */ zh bt;
    public static final /* enum */ zh bu;
    public static final /* enum */ zh bv;
    public static final /* enum */ zh bw;
    public static final /* enum */ zh bx;
    public static final /* enum */ zh by;
    public static final /* enum */ zh bz;
    public static final /* enum */ zh bA;
    public static final /* enum */ zh bB;
    public static final /* enum */ zh bC;
    public static final /* enum */ zh bD;
    public static final /* enum */ zh bE;
    public static final /* enum */ zh bF;
    public static final /* enum */ zh bG;
    public static final /* enum */ zh bH;
    public static final /* enum */ zh bI;
    public static final /* enum */ zh bJ;
    public static final /* enum */ zh bK;
    public static final /* enum */ zh bL;
    public static final /* enum */ zh bM;
    public static final /* enum */ zh bN;
    public static final /* enum */ zh bO;
    public static final /* enum */ zh bP;
    public static final /* enum */ zh bQ;
    public static final /* enum */ zh bR;
    public static final /* enum */ zh bS;
    public static final /* enum */ zh bT;
    public static final /* enum */ zh bU;
    public static final /* enum */ zh bV;
    public static final /* enum */ zh bW;
    public static final /* enum */ zh bX;
    public static final /* enum */ zh bY;
    public static final /* enum */ zh bZ;
    public static final /* enum */ zh ca;
    public static final /* enum */ zh cb;
    public static final /* enum */ zh cc;
    public static final /* enum */ zh cd;
    public static final /* enum */ zh ce;
    public static final /* enum */ zh cf;
    public static final /* enum */ zh cg;
    public static final /* enum */ zh ch;
    public static final /* enum */ zh ci;
    public static final /* enum */ zh cj;
    public static final /* enum */ zh ck;
    public static final /* enum */ zh cl;
    public static final /* enum */ zh cm;
    public static final /* enum */ zh cn;
    public static final /* enum */ zh co;
    public static final /* enum */ zh cp;
    public static final /* enum */ zh cq;
    public static final /* enum */ zh cr;
    public static final /* enum */ zh cs;
    public static final /* enum */ zh ct;
    public static final /* enum */ zh cu;
    public static final /* enum */ zh cv;
    public static final /* enum */ zh cw;
    public static final /* enum */ zh cx;
    public static final /* enum */ zh cy;
    public static final /* enum */ zh cz;
    public static final /* enum */ zh cA;
    public static final /* enum */ zh cB;
    public static final /* enum */ zh cC;
    public static final /* enum */ zh cD;
    public static final /* enum */ zh cE;
    public static final /* enum */ zh cF;
    public static final /* enum */ zh cG;
    public static final /* enum */ zh cH;
    public static final /* enum */ zh cI;
    public static final /* enum */ zh cJ;
    public static final /* enum */ zh cK;
    public static final /* enum */ zh cL;
    public static final /* enum */ zh cM;
    public static final /* enum */ zh cN;
    public static final /* enum */ zh cO;
    public static final /* enum */ zh cP;
    public static final /* enum */ zh cQ;
    public static final /* enum */ zh cR;
    public static final /* enum */ zh cS;
    public static final /* enum */ zh cT;
    public static final /* enum */ zh cU;
    public static final /* enum */ zh cV;
    public static final /* enum */ zh cW;
    public static final /* enum */ zh cX;
    public static final /* enum */ zh cY;
    public static final /* enum */ zh cZ;
    public static final /* enum */ zh da;
    public static final /* enum */ zh db;
    public static final /* enum */ zh dc;
    public static final /* enum */ zh dd;
    public static final /* enum */ zh de;
    public static final /* enum */ zh df;
    public static final /* enum */ zh dg;
    public static final /* enum */ zh dh;
    public static final /* enum */ zh di;
    public static final /* enum */ zh dj;
    public static final /* enum */ zh dk;
    public static final /* enum */ zh dl;
    public static final /* enum */ zh dm;
    public static final /* enum */ zh dn;
    public static final /* enum */ zh cfr_renamed_3;
    public static final /* enum */ zh dp;
    public static final /* enum */ zh dq;
    public static final /* enum */ zh dr;
    public static final /* enum */ zh ds;
    public static final /* enum */ zh dt;
    public static final /* enum */ zh du;
    public static final /* enum */ zh dv;
    public static final /* enum */ zh dw;
    public static final /* enum */ zh dx;
    public static final /* enum */ zh dy;
    public static final /* enum */ zh dz;
    public static final /* enum */ zh dA;
    public static final /* enum */ zh dB;
    public static final /* enum */ zh dC;
    public static final /* enum */ zh dD;
    public static final /* enum */ zh dE;
    public static final /* enum */ zh dF;
    public static final /* enum */ zh dG;
    public static final /* enum */ zh dH;
    public static final /* enum */ zh dI;
    public static final /* enum */ zh dJ;
    public static final /* enum */ zh dK;
    public static final /* enum */ zh dL;
    public static final /* enum */ zh dM;
    public static final /* enum */ zh dN;
    public static final /* enum */ zh dO;
    public static final /* enum */ zh dP;
    public static final /* enum */ zh dQ;
    public static final /* enum */ zh dR;
    public static final /* enum */ zh dS;
    public static final /* enum */ zh dT;
    public static final /* enum */ zh dU;
    public static final /* enum */ zh dV;
    public static final /* enum */ zh dW;
    public static final /* enum */ zh dX;
    public static final /* enum */ zh dY;
    private String var_java_lang_String_a;
    private static final /* synthetic */ zh[] var_zh_arr_a;

    public static zh[] values() {
        return (zh[])var_zh_arr_a.clone();
    }

    public static zh valueOf(String string) {
        return Enum.valueOf(zh.class, string);
    }

    private zh(String string2) {
        this.var_java_lang_String_a = string2;
    }

    public String a() {
        return this.var_java_lang_String_a;
    }

    static {
        var_zh_a = new zh("Abkhazia");
        b = new zh("Afghanistan");
        c = new zh("Aland");
        d = new zh("Albania");
        e = new zh("Algeria");
        f = new zh("American Samoa");
        g = new zh("Andorra");
        h = new zh("Angola");
        i = new zh("Anguilla");
        j = new zh("Antarctica");
        k = new zh("Antigua and Barbuda");
        l = new zh("Argentina");
        m = new zh("Armenia");
        n = new zh("Aruba");
        o = new zh("Australia");
        p = new zh("Austria");
        q = new zh("Azerbaijan");
        r = new zh("Bahamas");
        s = new zh("Bahrain");
        t = new zh("Bangladesh");
        u = new zh("Barbados");
        v = new zh("Basque Country");
        w = new zh("Belarus");
        x = new zh("Belgium");
        y = new zh("Belize");
        z = new zh("Benin");
        A = new zh("Bermuda");
        B = new zh("Bhutan");
        C = new zh("Bolivia");
        D = new zh("Bosnia and Herzegovina");
        E = new zh("Botswana");
        F = new zh("Brazil");
        G = new zh("British Antarctic Territory");
        H = new zh("British Virgin Islands");
        I = new zh("Brunei");
        J = new zh("Bulgaria");
        K = new zh("Burkina Faso");
        L = new zh("Burundi");
        M = new zh("Cambodia");
        N = new zh("Cameroon");
        O = new zh("Canada");
        P = new zh("Canary Islands");
        Q = new zh("Cape Verde");
        R = new zh("Catalonia");
        S = new zh("Cayman Islands");
        T = new zh("Central African Republic");
        U = new zh("Chad");
        V = new zh("Chile");
        W = new zh("China");
        X = new zh("Christmas Island");
        Y = new zh("Cocos Keeling Islands");
        Z = new zh("Colombia");
        aa = new zh("Commonwealth");
        ab = new zh("Comoros");
        ac = new zh("Cook Islands");
        ad = new zh("Costa Rica");
        ae = new zh("Cote dIvoire");
        af = new zh("Croatia");
        ag = new zh("Cuba");
        ah = new zh("Curacao");
        ai = new zh("Cyprus");
        aj = new zh("Czech Republic");
        ak = new zh("Democratic Republic of the Congo");
        al = new zh("Denmark");
        am = new zh("Djibouti");
        an = new zh("Dominica");
        ao = new zh("Dominican Republic");
        ap = new zh("East Timor");
        aq = new zh("Ecuador");
        ar = new zh("Egypt");
        as = new zh("El Salvador");
        at = new zh("England");
        au = new zh("Equatorial Guinea");
        av = new zh("Eritrea");
        aw = new zh("Estonia");
        ax = new zh("Ethiopia");
        ay = new zh("European Union");
        az = new zh("Falkland Islands");
        aA = new zh("Faroes");
        aB = new zh("Fiji");
        aC = new zh("Finland");
        aD = new zh("France");
        aE = new zh("French Polynesia");
        aF = new zh("French Southern Territories");
        aG = new zh("Gabon");
        aH = new zh("Gambia");
        aI = new zh("Georgia");
        aJ = new zh("Germany");
        aK = new zh("Ghana");
        aL = new zh("Gibraltar");
        aM = new zh("Greece");
        aN = new zh("Greenland");
        aO = new zh("Grenada");
        aP = new zh("Guam");
        aQ = new zh("Guatemala");
        aR = new zh("Guernsey");
        aS = new zh("Guinea Bissau");
        aT = new zh("Guinea");
        aU = new zh("Guyana");
        aV = new zh("Haiti");
        aW = new zh("Honduras");
        aX = new zh("Hong Kong");
        aY = new zh("Hungary");
        aZ = new zh("Iceland");
        ba = new zh("India");
        bb = new zh("Indonesia");
        bc = new zh("Iran");
        bd = new zh("Iraq");
        be = new zh("Ireland");
        bf = new zh("Isle of Man");
        bg = new zh("Israel");
        bh = new zh("Italy");
        bi = new zh("Jamaica");
        bj = new zh("Japan");
        bk = new zh("Jersey");
        bl = new zh("Jordan");
        bm = new zh("Kazakhstan");
        bn = new zh("Kenya");
        bo = new zh("Kiribati");
        bp = new zh("Kosovo");
        bq = new zh("Kuwait");
        br = new zh("Kyrgyzstan");
        bs = new zh("Laos");
        bt = new zh("Latvia");
        bu = new zh("Lebanon");
        bv = new zh("Lesotho");
        bw = new zh("Liberia");
        bx = new zh("Libya");
        by = new zh("Liechtenstein");
        bz = new zh("Lithuania");
        bA = new zh("Luxembourg");
        bB = new zh("Macau");
        bC = new zh("Macedonia");
        bD = new zh("Madagascar");
        bE = new zh("Malawi");
        bF = new zh("Malaysia");
        bG = new zh("Maldives");
        bH = new zh("Mali");
        bI = new zh("Malta");
        bJ = new zh("Marshall Islands");
        bK = new zh("Martinique");
        bL = new zh("Mauritania");
        bM = new zh("Mauritius");
        bN = new zh("Mayotte");
        bO = new zh("Mexico");
        bP = new zh("Micronesia");
        bQ = new zh("Moldova");
        bR = new zh("Monaco");
        bS = new zh("Mongolia");
        bT = new zh("Montenegro");
        bU = new zh("Montserrat");
        bV = new zh("Morocco");
        bW = new zh("Mozambique");
        bX = new zh("Myanmar");
        bY = new zh("Nagorno Karabakh");
        bZ = new zh("Namibia");
        ca = new zh("NATO");
        cb = new zh("Nauru");
        cc = new zh("Nepal");
        cd = new zh("Netherlands Antilles");
        ce = new zh("Netherlands");
        cf = new zh("New Caledonia");
        cg = new zh("New Zealand");
        ch = new zh("Nicaragua");
        ci = new zh("Niger");
        cj = new zh("Nigeria");
        ck = new zh("Niue");
        cl = new zh("Norfolk Island");
        cm = new zh("North Korea");
        cn = new zh("Northern Cyprus");
        co = new zh("Northern Mariana Islands");
        cp = new zh("Norway");
        cq = new zh("Olympics");
        cr = new zh("Oman");
        cs = new zh("Pakistan");
        ct = new zh("Palau");
        cu = new zh("Palestine");
        cv = new zh("Panama");
        cw = new zh("Papua New Guinea");
        cx = new zh("Paraguay");
        cy = new zh("Peru");
        cz = new zh("Philippines");
        cA = new zh("Pitcairn Islands");
        cB = new zh("Poland");
        cC = new zh("Portugal");
        cD = new zh("Puerto Rico");
        cE = new zh("Qatar");
        cF = new zh("Red Cross");
        cG = new zh("Republic of the Congo");
        cH = new zh("Reunion");
        cI = new zh("Romania");
        cJ = new zh("Russia");
        cK = new zh("Rwanda");
        cL = new zh("Saint Barthelemy");
        cM = new zh("Saint Helena");
        cN = new zh("Saint Kitts and Nevis");
        cO = new zh("Saint Lucia");
        cP = new zh("Saint Martin");
        cQ = new zh("Samoa");
        cR = new zh("San Marino");
        cS = new zh("Sao Tome and Principe");
        cT = new zh("Saudi Arabia");
        cU = new zh("Scotland");
        cV = new zh("Senegal");
        cW = new zh("Serbia");
        cX = new zh("Seychelles");
        cY = new zh("Sierra Leone");
        cZ = new zh("Singapore");
        da = new zh("Sint Maarten");
        db = new zh("Slovakia");
        dc = new zh("Slovenia");
        dd = new zh("Solomon Islands");
        de = new zh("Somalia");
        df = new zh("Somaliland");
        dg = new zh("South Africa");
        dh = new zh("South Korea");
        di = new zh("South Ossetia");
        dj = new zh("South Sudan");
        dk = new zh("Spain");
        dl = new zh("Sri Lanka");
        dm = new zh("Sudan");
        dn = new zh("Suriname");
        cfr_renamed_3 = new zh("Swaziland");
        dp = new zh("Sweden");
        dq = new zh("Switzerland");
        dr = new zh("Syria");
        ds = new zh("Taiwan");
        dt = new zh("Tajikistan");
        du = new zh("Tanzania");
        dv = new zh("Thailand");
        dw = new zh("Togo");
        dx = new zh("Tokelau");
        dy = new zh("Tonga");
        dz = new zh("Trinidad and Tobago");
        dA = new zh("Tunisia");
        dB = new zh("Turkey");
        dC = new zh("Turkmenistan");
        dD = new zh("Turks and Caicos Islands");
        dE = new zh("Tuvalu");
        dF = new zh("Uganda");
        dG = new zh("Ukraine");
        dH = new zh("United Arab Emirates");
        dI = new zh("United Kingdom");
        dJ = new zh("United Nations");
        dK = new zh("United States");
        dL = new zh("Unknown");
        dM = new zh("Uruguay");
        dN = new zh("US Virgin Islands");
        dO = new zh("Uzbekistan");
        dP = new zh("Vanuatu");
        dQ = new zh("Vatican City");
        dR = new zh("Venezuela");
        dS = new zh("Vietnam");
        dT = new zh("Wales");
        dU = new zh("Wallis And Futuna");
        dV = new zh("Western Sahara");
        dW = new zh("Yemen");
        dX = new zh("Zambia");
        dY = new zh("Zimbabwe");
        var_zh_arr_a = new zh[]{var_zh_a, b, c, d, e, f, g, h, i, j, k, l, m, n, o, p, q, r, s, t, u, v, w, x, y, z, A, B, C, D, E, F, G, H, I, J, K, L, M, N, O, P, Q, R, S, T, U, V, W, X, Y, Z, aa, ab, ac, ad, ae, af, ag, ah, ai, aj, ak, al, am, an, ao, ap, aq, ar, as, at, au, av, aw, ax, ay, az, aA, aB, aC, aD, aE, aF, aG, aH, aI, aJ, aK, aL, aM, aN, aO, aP, aQ, aR, aS, aT, aU, aV, aW, aX, aY, aZ, ba, bb, bc, bd, be, bf, bg, bh, bi, bj, bk, bl, bm, bn, bo, bp, bq, br, bs, bt, bu, bv, bw, bx, by, bz, bA, bB, bC, bD, bE, bF, bG, bH, bI, bJ, bK, bL, bM, bN, bO, bP, bQ, bR, bS, bT, bU, bV, bW, bX, bY, bZ, ca, cb, cc, cd, ce, cf, cg, ch, ci, cj, ck, cl, cm, cn, co, cp, cq, cr, cs, ct, cu, cv, cw, cx, cy, cz, cA, cB, cC, cD, cE, cF, cG, cH, cI, cJ, cK, cL, cM, cN, cO, cP, cQ, cR, cS, cT, cU, cV, cW, cX, cY, cZ, da, db, dc, dd, de, df, dg, dh, di, dj, dk, dl, dm, dn, cfr_renamed_3, dp, dq, dr, ds, dt, du, dv, dw, dx, dy, dz, dA, dB, dC, dD, dE, dF, dG, dH, dI, dJ, dK, dL, dM, dN, dO, dP, dQ, dR, dS, dT, dU, dV, dW, dX, dY};
    }
}

