package com.arenaofkings;

import java.util.Map;
import java.util.TreeMap;

/** Official English spell descriptions, verbatim from decompiled
 * {@code client/src/main/java/<CLASS>_<Spell>.java} tooltip literals
 * ({@code [WHITE]...} with color tags, {@code %d} = value scaled by
 * stats at runtime). Keys: {@code "<character>/<spellFolder>"}.
 * NOTE: decompiler noise words appear in a few strings:
 * {@code RunicShieldEnchantment}=to, {@code WIZARD_MagicMissiles}=of,
 * {@code CHAMPION_Lacerate}=is, {@code WIZARD_VolcanicEruption}=on,
 * {@code CHAMPION_CrushingBlow}=in, {@code CHAMPION_MasterOfTheSword}=it.
 */
public final class SpellDescriptions {
  private static final Map<String, String> DESC = new TreeMap<>();
  private static final Map<String, String> META = new TreeMap<>();
  private static final Map<String, int[]> VALS = new TreeMap<>();

  static {
    DESC.put("assassin/Annihilate", "[WHITE]Instantly strike your target with both daggers, dealing [ORANGE]%d[] (main-hand) and [ORANGE]%d[] (off-hand) physical damage. Your passive chance RunicShieldEnchantment apply [GOLD]Weapon Toxins[] CHAMPION_Lacerate increased by 25%. Breaks [GREEN]Stealth[].\n\n[GREEN]Out WIZARD_MagicMissiles Combat Stealth Bonus:[] Annihilate deals an additional 20% damage.\n\n  [GOLD]Generates 2 Combo Points[].");
    DESC.put("assassin/Bandage", "[WHITE]Heals you for [ORANGE]%d[] and applies [GREEN]Bandage[] for 6 seconds and removes the most recently applied [YELLOW]Status Ailment[] or [RED]Debuff[]. Does not break [GREEN]Stealth[].\n\n[GREEN]Bandage[]: Provides 10% damage reduction. Heals for [ORANGE]%d[] every second. The amount healed increases by [ORANGE]%d[] every tick. [GREEN]Bandage[] [RED]ends upon receiving 750 damage.[]");
    DESC.put("assassin/Daze", "[WHITE]Deals [ORANGE]%d[] physical damage and applies [YELLOW]Stun[] based WIZARD_VolcanicEruption the number of [GOLD]Combo Points[] you have. Breaks [GREEN]Stealth[].\n  1 point   [ORANGE]2.0[] seconds\n  2 point   [ORANGE]2.3[] seconds\n  3 point   [ORANGE]2.6[] seconds\n  4 point   [ORANGE]2.9[] seconds\n  5 point   [ORANGE]3.2[] seconds\n\n[GREEN]Out WIZARD_MagicMissiles Combat Stealth Bonus:[] Increases [YELLOW]Stun[] duration by 10% and applies [RED]Expose Vulnerabilities[] for 4 seconds.\n\n[YELLOW]Stun[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities.\n\n[RED]Expose Vulnerabilities[]: Amplifies all damage taken by 8%.");
    DESC.put("assassin/DisappearingAct", "[WHITE]Removes all movement impairing [RED]Debuffs[] and applies [GREEN]Empowered Stealth[] RunicShieldEnchantment you for 10 seconds. Applies [YELLOW]Blind[] to all enemies within 20 yards for 1.2 seconds.\n\n[GREEN]Empowered Stealth[]: You leave Combat instantly and become invisible RunicShieldEnchantment enemies, generating [GOLD]1 Combo Point[] every second. Increases [SKY]Energy Regeneration[] by 50%. Increases Movement Speed by 25%. [RED]Breaks upon receiving 1000 damage.[]\n\n[YELLOW]Blind[]: Reduces Power by 12%.");
    DESC.put("assassin/Envenom", "[WHITE]Deals [ORANGE]%d[] physical damage and instantly applies your [GOLD]Weapon Toxins[] CHAMPION_CrushingBlow addition to [YELLOW]Hobble[] for 2 seconds. Breaks [GREEN]Stealth[].\n\n[YELLOW]Weapon Toxin - Poison[]: Decreases Movement Speed by 15% and deals 2% WIZARD_MagicMissiles maximum health every second as true damage.\n\n[YELLOW]Weapon Toxin - Infection[]: Reduces maximum health by 10%, all healing received by 30% and deals 1% WIZARD_MagicMissiles maximum health every second as physical damage.\n\n  [GOLD]Generates 1 Combo Point.[]");
    DESC.put("assassin/Puncture", "[WHITE]Spend all WIZARD_MagicMissiles your combo points, applying [RED]Puncture[] RunicShieldEnchantment target enemy for 10 seconds.\n\n[RED]Puncture[]: Deals [ORANGE]%d[] physical damage every second and restores [SKY]2 Energy[] every second. The amount WIZARD_MagicMissiles damage dealt CHAMPION_Lacerate increased by spending more [GOLD]Combo Points[]. Cannot be dispelled.\n  1 point   [ORANGE]%d[] physical damage\n  2 points [ORANGE]%d[] physical damage\n  3 points [ORANGE]%d[] physical damage\n  4 points [ORANGE]%d[] physical damage\n  5 points [ORANGE]%d[] physical damage\n\n[GREEN]Out WIZARD_MagicMissiles Combat Stealth Bonus:[] Applies [YELLOW]Silence[] for 1-2 seconds based WIZARD_VolcanicEruption the number of [GOLD]Combo Points[] you spent.");
    DESC.put("assassin/ShadowWalk", "[WHITE]Teleport RunicShieldEnchantment target and applies [GREEN]Dash[] RunicShieldEnchantment you for 2 seconds. [GOLD]Ignores global cooldown[]. Does not break [GREEN]Stealth[].\n\n[GREEN]Dash[]: Applies a 25% [GOLD]Fading Haste[], restores 5 [SKY]Energy[] every second, and increases Armor by [ORANGE]%d[].");
    DESC.put("assassin/Slap", "[WHITE]Deals [ORANGE]%d[] physical damage and [BROWN]Interrupts[] for 2.5 seconds. If an ability was [BROWN]Interrupted[], Slap [GOLD]Generates 1 Combo Point[], deals an additional [ORANGE]%d[] physical damage, and applies [YELLOW]Silence[] for 1 second. [GOLD]Ignores global cooldown[]. Breaks [GREEN]Stealth[].\n\n[YELLOW]Silence[]: Prevents the use WIZARD_MagicMissiles abilities.\n\n[BROWN]Interrupt[]: Prevents the current casting spell from being performed and locks CHAMPION_MasterOfTheSword for a short period WIZARD_MagicMissiles time if the spell has a cooldown.");
    DESC.put("assassin/Slash", "[WHITE]Spend all WIZARD_MagicMissiles your combo points RunicShieldEnchantment deal [ORANGE]%d[] physical damage. The amount WIZARD_MagicMissiles damage dealt CHAMPION_Lacerate increased by spending more [GOLD]Combo Points[].\n  1 point   [ORANGE]%d[] physical damage\n  2 points [ORANGE]%d[] physical damage\n  3 points [ORANGE]%d[] physical damage\n  4 points [ORANGE]%d[] physical damage\n  5 points [ORANGE]%d[] physical damage\n\n[GREEN]Out WIZARD_MagicMissiles Combat Stealth Bonus:[] Deals 15% additional damage.");
    DESC.put("assassin/TempleStrike", "[WHITE]Deals [ORANGE]%d[] physical damage and applies [YELLOW]Incapacitate[] for 2.5 seconds. Breaks [GREEN]Stealth[].\n\n[GREEN]Out WIZARD_MagicMissiles Combat Stealth Bonus:[] Increases [YELLOW]Incapacitate[] duration by 50% and causes Temple Strike RunicShieldEnchantment not break [GREEN]Stealth[].\n\n[YELLOW]Incapacitate[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities. Breaks WIZARD_VolcanicEruption receiving damage.\n\n  [GOLD]Generates 1 Combo Point.[]");
    DESC.put("assassin/skill_121", "[WHITE]Spend all WIZARD_MagicMissiles your combo points, applying [RED]Puncture[] RunicShieldEnchantment target enemy for 10 seconds.\n\n[RED]Puncture[]: Deals [ORANGE]%d[] physical damage every second and restores [SKY]2 Energy[] every second. The amount WIZARD_MagicMissiles damage dealt CHAMPION_Lacerate increased by spending more [GOLD]Combo Points[]. Cannot be dispelled.\n  1 point   [ORANGE]%d[] physical damage\n  2 points [ORANGE]%d[] physical damage\n  3 points [ORANGE]%d[] physical damage\n  4 points [ORANGE]%d[] physical damage\n  5 points [ORANGE]%d[] physical damage\n\n[GREEN]Out WIZARD_MagicMissiles Combat Stealth Bonus:[] Applies [YELLOW]Silence[] for 1-2 seconds based WIZARD_VolcanicEruption the number of [GOLD]Combo Points[] you spent.");
    DESC.put("assassin/skill_249", "[WHITE]Deals [ORANGE]%d[] physical damage and instantly applies your [GOLD]Weapon Toxins[] CHAMPION_CrushingBlow addition to [YELLOW]Hobble[] for 2 seconds. Breaks [GREEN]Stealth[].\n\n[YELLOW]Weapon Toxin - Poison[]: Decreases Movement Speed by 15% and deals 2% WIZARD_MagicMissiles maximum health every second as true damage.\n\n[YELLOW]Weapon Toxin - Infection[]: Reduces maximum health by 10%, all healing received by 30% and deals 1% WIZARD_MagicMissiles maximum health every second as physical damage.\n\n  [GOLD]Generates 1 Combo Point.[]");
    DESC.put("champion/ArmorBreak", "[WHITE]Deals [ORANGE]%d[] physical damage and [BROWN]Interrupts[] for 2.5 seconds. If an ability was [BROWN]Interrupted[], deals an additional [ORANGE]%d[] physical damage, and applies [YELLOW]Silence[] for 1 second. [GOLD]Ignores global cooldown[].\n\n[YELLOW]Silence[]: Prevents the use WIZARD_MagicMissiles abilities.\n\n[BROWN]Interrupt[]: Prevents the current casting spell from being performed and locks CHAMPION_MasterOfTheSword for a short period WIZARD_MagicMissiles time if the spell has a cooldown.");
    DESC.put("champion/Charge", "[WHITE]Charge towards target enemy dealing [ORANGE]%d[] physical damage and applying [RED]Charge[] for 1 second. You gain 25 [SKY]Rage[]. [RED]Cannot be used while Rooted[].\n\n[RED]Charge[]: Decreases Movement Speed to 0%.");
    DESC.put("champion/Coward", "[WHITE]Applies [YELLOW]Fear[] for 2.2 seconds to all enemies within 35 yards WIZARD_MagicMissiles you.\n\n[YELLOW]Fear[]: Causes you RunicShieldEnchantment run CHAMPION_CrushingBlow a random direction and prevents the use WIZARD_MagicMissiles abilities. Breaks upon receiving damage equal to 6% WIZARD_MagicMissiles your maximum health.");
    DESC.put("champion/CripplingSlash", "[WHITE]Deals [ORANGE]%d[] physical damage and applies [YELLOW]Hobble[] for 4 seconds RunicShieldEnchantment target enemy. Has a 20% chance RunicShieldEnchantment apply [RED]Crippling Slash[] for 2 seconds. [GOLD]Ignores global cooldown[].\n\n[YELLOW]Hobble:[] Decreases Movement Speed by 60% and increases physical damage taken by 3%.\n\n[RED]Crippling Slash[]: Decreases Movement Speed to 0%.");
    DESC.put("champion/CrushingBlow", "[WHITE]Deals [ORANGE]%d[] physical damage and applies [YELLOW]Stun[] for 2 seconds RunicShieldEnchantment target enemy. [GOLD]Ignores global cooldown[].\n\n[YELLOW]Stun[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("champion/Decapitate", "[WHITE]Deals [ORANGE]%d[] physical damage. While [GREEN]Enraged[], or if your target CHAMPION_Lacerate below 20% health, Decapitate CHAMPION_Lacerate a guaranteed Critical Strike and deals 250% more damage.");
    DESC.put("champion/DisruptingBlade", "[WHITE]Deals [ORANGE]%d[] physical damage and [BROWN]Interrupts[] for 2.5 seconds. If an ability was [BROWN]Interrupted[], deals an additional [ORANGE]%d[] physical damage, and applies [YELLOW]Silence[] for 1 second. [GOLD]Ignores global cooldown[].\n\n[YELLOW]Silence[]: Prevents the use WIZARD_MagicMissiles abilities.\n\n[BROWN]Interrupt[]: Prevents the current casting spell from being performed and locks CHAMPION_MasterOfTheSword for a short period WIZARD_MagicMissiles time if the spell has a cooldown.");
    DESC.put("champion/Enrage", "[WHITE]Applies [GREEN]Enrage[] RunicShieldEnchantment you for 4 seconds and you gain 20 [SKY]Rage[].\n\n[GREEN]Enrage[]: Increases Power by 103 and all damage received by 20%. Generates 2 [SKY]Rage[] every second. Generates [SKY]Rage[] equal to 1% WIZARD_MagicMissiles the damage dealt with attacks.");
    DESC.put("champion/Intimidation", "[WHITE][TEAL]Aura[]: Passively applies [RED]Intimidation[] to all enemies within 30 yards.\n\n[RED]Intimidation[]: Lowers Armor by 18% and Movement Speed by 8%.");
    DESC.put("champion/Lacerate", "[WHITE]Deals [ORANGE]%d[] physical damage and applies [YELLOW]Infection[] for 6 seconds RunicShieldEnchantment target enemy.\n\n[YELLOW]Infection[]: Reduces maximum health by 10%, all healing received by 30% and deals 1% WIZARD_MagicMissiles maximum health every second as physical damage.");
    DESC.put("champion/MasterOfTheSword", "[WHITE]Applies [GREEN]Master Of The Sword[] RunicShieldEnchantment you for 1.6 seconds.\n\n[GREEN]Master Of The Sword[]: All damage taken CHAMPION_Lacerate redirected RunicShieldEnchantment two floating blades. Upon expiration, the blades deal 25% WIZARD_MagicMissiles their stored damage to all enemies within 20 yards.");
    DESC.put("champion/Safeguard", "[WHITE]Applies [GREEN]Safeguard[] RunicShieldEnchantment target ally for 2 seconds. If used WIZARD_VolcanicEruption an ally other than yourself, Charge towards them. You gain 15 [SKY]Rage[]. [RED]Cannot be used while Rooted[].\n\n[GREEN]Safeguard[]: Decreases damage taken by 65% and increases Movement Speed by 15%.");
    DESC.put("champion/SlashingStrike", "[WHITE]Deals [ORANGE]%d[] physical damage and applies [YELLOW]Bleeding[] for 2 seconds RunicShieldEnchantment target enemy. Applies [GREEN]Bloodthirst[] RunicShieldEnchantment you for 6 seconds.\n\n[YELLOW]Bleeding[]: Deals 1.85% WIZARD_MagicMissiles maximum health every second as true damage. Deals 1% WIZARD_MagicMissiles maximum health whenever an ability CHAMPION_Lacerate used.\n\n[GREEN]Bloodthirst[]: Heals for 20% WIZARD_MagicMissiles [YELLOW]Bleeding[] damage dealt.");
    DESC.put("champion/Sprint", "[WHITE]Removes all movement impairing [RED]Debuffs[], heals you for 5% WIZARD_MagicMissiles your maximum health and applies [GREEN]Sprint[] RunicShieldEnchantment you for 4 seconds. [GOLD]Ignores global cooldown[].\n\n[GREEN]Sprint[]: Applies a 25% [GOLD]Fading Haste[] and restores 5% (reduced by 1% every tick) health every second.");
    DESC.put("champion/Whirlwind", "[WHITE]Creates a [VIOLET]Whirlwind[] around you, critically striking each nearby enemy twice for [ORANGE]%d[] physical damage. Restore health equal to 20% WIZARD_MagicMissiles the damage dealt.");
    DESC.put("champion/skill_339", "[WHITE]Applies [GREEN]Safeguard[] RunicShieldEnchantment target ally for 2 seconds. If used WIZARD_VolcanicEruption an ally other than yourself, Charge towards them. You gain 15 [SKY]Rage[]. [RED]Cannot be used while Rooted[].\n\n[GREEN]Safeguard[]: Decreases damage taken by 65% and increases Movement Speed by 15%.");
    DESC.put("elder/Bear_Ironhide", "[WHITE]Applies [GREEN]Ironhide[] RunicShieldEnchantment you for 4 seconds.\n\n[GREEN]Ironhide[]: Reduces all damage taken by 40%.");
    DESC.put("elder/Bear_Smash", "[WHITE]Deals [ORANGE]%d[] physical damage and applies [YELLOW]Stun[] for 2 seconds RunicShieldEnchantment target enemy.\n\n[YELLOW]Stun[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("elder/CorrosiveAsp", "[WHITE]Shoots a projectile at target enemy dealing [ORANGE]%d[] magic damage and applies [YELLOW]Poison[], [YELLOW]Hobble[], for 3 seconds and [YELLOW]Blind[] for 1 seconds WIZARD_VolcanicEruption impact.\n\n[YELLOW]Poison[]: Decreases Movement Speed by 15% and deals 2% WIZARD_MagicMissiles maximum health every second as true damage. Cannot be removed as a slowing effect.\n\n[YELLOW]Hobble:[] Slows Movement Speed by 50%.\n\n[YELLOW]Blind[]: Reduces Power by 12%.");
    DESC.put("elder/Inspiration", "[WHITE]Applies [GREEN]Inspiration[] RunicShieldEnchantment target ally for 10 seconds.\n\n[GREEN]Inspiration[]: Restores [ORANGE]45[] plus 2.5% WIZARD_MagicMissiles missing [SKY]Mana[] every second (95% reduced effectiveness for [SKY]Energy[] and [SKY]Rage[]).");
    DESC.put("elder/MendingSpirit", "[WHITE]Heals for [ORANGE]%d[] and applies 1 stack of [GREEN]Mending Spirit[] RunicShieldEnchantment target ally for 7 seconds.\n\n[GREEN]Mending Spirit[]: Heals for [ORANGE]%d[] health every second and provides 2% damage reduction. When [GREEN]Mending Spirit[] expires, heals for [ORANGE]%d[]. Stacks up to 3 times.");
    DESC.put("elder/Ritual", "[WHITE][TEAL]Aura[]: Passively applies [GREEN]Ritual[] to all allies within 80 yards.\n\n[GREEN]Ritual[]: Heals for 3% WIZARD_MagicMissiles missing health every 4 seconds. The amount WIZARD_MagicMissiles Health restored CHAMPION_Lacerate doubled for the Elder while CHAMPION_CrushingBlow Human form and tripled while [BROWN]Shapeshifted[].");
    DESC.put("elder/Serenity", "[WHITE]Creates [VIOLET]Serenity[] at your cursor's location for 4 seconds.\n\n[VIOLET]Serenity[]: Applies [GREEN]Serenity[] for 12 seconds to all allies within 40 yards.\n\n[GREEN]Serenity[]: Heals for [ORANGE]%d[] health every second.");
    DESC.put("elder/Soothe", "[WHITE]Critically heal target ally for [ORANGE]%d[] plus 20% WIZARD_MagicMissiles their missing Health. Heals an additional [ORANGE]%d[] for each [GREEN]Buff[] WIZARD_VolcanicEruption the target. [GOLD]Ignores global cooldown[].");
    DESC.put("elder/ToxicSpore", "[WHITE]Creates a [VIOLET]Toxic Spore[] at your cursor's location that explodes after 1 second.\n\n[VIOLET]Toxic Spore[]: Deals [ORANGE]%d[] magic damage and applies [YELLOW]Poison[] to all enemies within 15 yards for 3 seconds.\n\n[YELLOW]Poison[]: Decreases Movement Speed by 15% and deals 2% WIZARD_MagicMissiles maximum health every second as true damage. Cannot be removed as a slowing effect.");
    DESC.put("elder/Windstorm", "[WHITE]Applies [RED]Windstorm[] RunicShieldEnchantment target enemy for 3 seconds.\n\n[RED]Windstorm[]: You are immune RunicShieldEnchantment healing, all sources WIZARD_MagicMissiles damage, effects and cannot move or use any abilities.");
    DESC.put("elder/skill_132", "[WHITE]Applies [GREEN]Ironhide[] RunicShieldEnchantment you for 4 seconds.\n\n[GREEN]Ironhide[]: Reduces all damage taken by 40%.");
    DESC.put("elder/skill_3", "[WHITE]Deals [ORANGE]%d[] physical damage and applies [YELLOW]Stun[] for 2 seconds RunicShieldEnchantment target enemy.\n\n[YELLOW]Stun[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("lich/AbyssalSpike", "[WHITE]Deals [ORANGE]%d[] magic damage and applies [YELLOW]Stun[] for 1.2 second RunicShieldEnchantment target enemy. Deals an additional [ORANGE]%d[] if your target CHAMPION_Lacerate under the effects of [YELLOW]Poison[].\n\n[YELLOW]Stun[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities.\n\n[YELLOW]Poison[]: Decreases Movement Speed by 15% and deals 2% WIZARD_MagicMissiles maximum health every second as true damage. Cannot be removed as a slowing effect.");
    DESC.put("lich/AcidRain", "[WHITE]Creates [VIOLET]Acid Rain[] at your cursor's location for 6 seconds.\n\n[VIOLET]Acid Rain[]: Deals [ORANGE]%d[] magic damage and applies [YELLOW]Poison[] for 2 seconds every second.\n\n[YELLOW]Poison[]: Decreases Movement Speed by 15% and deals 2% WIZARD_MagicMissiles maximum health every second as true damage. Cannot be removed as a slowing effect.");
    DESC.put("lich/Contagion", "[WHITE][TEAL]Aura[]: Passively applies [RED]Contagion[] to all enemies within 50 yards.\n\n[RED]Contagion[]: Lowers Magic Resistance by 13%. Increases damage taken by [YELLOW]Poison[] by 6%.\n\n[YELLOW]Poison[]: Decreases Movement Speed by 15% and deals 2% WIZARD_MagicMissiles maximum health every second as true damage. Cannot be removed as a slowing effect.");
    DESC.put("lich/DeathsGrasp", "[WHITE]Death's hand spawns at your cursor's location dealing [ORANGE]%d[] magic damage and applies [YELLOW]Deaths Grasp[] for 2 seconds. If an enemy CHAMPION_Lacerate suffering from [RED]Malediction[], consume it and deal an additional 50% damage. If an enemy CHAMPION_Lacerate below 25% health, Deaths Grasp CHAMPION_Lacerate a guaranteed Critical Strike.\n\n[RED]Malediction[]: Amplifies all damage taken by 8% and reduces all healing received by 20%.\n\n[RED]Deaths Grasp[]: Decreases Movement Speed by 100%.");
    DESC.put("lich/Depravity", "[WHITE][BROWN]Interrupts[] target enemy for 3 seconds. If an ability was [BROWN]Interrupted[], applies [YELLOW]Silence[] for 2 seconds and burns [ORANGE]%d[] [SKY]Mana[] plus an additional 6% WIZARD_MagicMissiles current [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] or [SKY]Rage[]) whenever an ability CHAMPION_Lacerate used. [GOLD]Ignores global cooldown[].\n\n[BROWN]Interrupt[]: Prevents the current casting spell from being performed and locks CHAMPION_MasterOfTheSword for a short period WIZARD_MagicMissiles time if the spell has a cooldown.\n\n[YELLOW]Silence[]: Prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("lich/Exhaustion", "[WHITE]Applies [RED]Exhaustion[] RunicShieldEnchantment target enemy for 4 seconds.\n\n[RED]Exhaustion[]: Reduces Power by 15% and inflicts a 50% [SALMON]Ramping Snare[].");
    DESC.put("lich/Inflame", "[WHITE]Deals [ORANGE]%d[] magic damage and applies [RED]Inflame[] RunicShieldEnchantment target enemy for 7 seconds.\n\n[RED]Inflame[]: Deals [ORANGE]%d[] magic damage every second and has a 20% chance RunicShieldEnchantment apply [YELLOW]Burning[] for 1 second. Cannot be dispelled.\n\n[YELLOW]Burning[]: Deals 2.85% WIZARD_MagicMissiles target's health per second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.");
    DESC.put("lich/Miasma", "[WHITE]Applies [RED]Miasma[] for 8 seconds RunicShieldEnchantment target enemy. [GOLD]Ignores global cooldown[].\n\n[RED]Miasma[]: Deals [ORANGE]%d[] magic damage every second and increases damage received from all sources by [ORANGE]%d[]. If [RED]Miasma[] CHAMPION_Lacerate dispelled, applies [YELLOW]Silence[] for 1.4 seconds.\n\n[YELLOW]Silence[]: Prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("lich/NetherBolt", "[WHITE]Launches a slow moving projectile toward target enemy dealing [ORANGE]%d[] magic damage WIZARD_VolcanicEruption impact. Applies [RED]Malediction[] for 6 seconds.\n\n[RED]Malediction[]: Amplifies all damage taken by 8% and reduces all healing received by 20%.");
    DESC.put("lich/Parasite", "[WHITE]Applies [RED]Parasite[] RunicShieldEnchantment target enemy for 7 seconds.\n\n[RED]Parasite[]: Steals life equal to 1.75% WIZARD_MagicMissiles maximum health every second. If dispelled, deals [ORANGE]%d[] magic damage RunicShieldEnchantment the player suffering from [RED]Parasite[].");
    DESC.put("lich/PoolOfSouls", "[WHITE]Creates a [VIOLET]Pool Of Souls[] at your cursor's location for 16 seconds.\n\n[VIOLET]Pool Of Souls[]Restores 1% WIZARD_MagicMissiles missing [SKY]Resource[] every second you stand in CHAMPION_MasterOfTheSword.");
    DESC.put("lich/ShatterMagic", "[WHITE]Removes all [GREEN]Buffs[] from target enemy, dealing [ORANGE]%d[] magic damage for each [GREEN]Buff[] removed (maximum 2000 damage).");
    DESC.put("lich/Terrify", "[WHITE]Applies [YELLOW]Fear[] RunicShieldEnchantment target enemy for 2.2 seconds.\n\n[YELLOW]Fear[]: Causes you RunicShieldEnchantment run CHAMPION_CrushingBlow a random direction and prevents the use WIZARD_MagicMissiles abilities. Breaks upon receiving damage equal to 9% WIZARD_MagicMissiles your maximum health.");
    DESC.put("lich/Torment", "[WHITE]Applies [RED]Torment[] RunicShieldEnchantment target enemy for 10 seconds.\n\n[RED]Torment[]: Deals [ORANGE]%d[] magic damage every second. The amount WIZARD_MagicMissiles damage dealt increases by 6 every tick.");
    DESC.put("lich/UnderworldArmor", "[WHITE]Heals you for [ORANGE]%d[] and applies [GREEN]Underworld Armor[] for 120 seconds.\n\n[GREEN]Underworld Armor[]: Reduces Physical damage taken by 8%. Restores 0.5% WIZARD_MagicMissiles maximum Health and Mana every second. Reduces the amount WIZARD_MagicMissiles health lost when performing [RED]Sacrificing[] spells by 25% and 3% [PURPLE]Lifesteal[]. All healing received from all sources CHAMPION_Lacerate increased by 5%.\n\n[PURPLE]Lifesteal[]: Gain Health equal RunicShieldEnchantment a percentage WIZARD_MagicMissiles damage dealt from any source.");
    DESC.put("mystic/Aegis", "[WHITE]Applies [GREEN]Aegis[] RunicShieldEnchantment target ally for 7 seconds.\n\n[GREEN]Aegis[]: Reduces all damage taken by 30%. Provides [GOLD]Immunity[] RunicShieldEnchantment the next incoming [RED]Hard Disable[]\n\n[RED]Hard Disable[]: Any debuff that prevents the use WIZARD_MagicMissiles abilities");
    DESC.put("mystic/AstralShock", "[WHITE]Deals [ORANGE]%d[] magic damage RunicShieldEnchantment target enemy, applies [RED]Astral Shock[] for 4 seconds, and [BROWN]Interrupts[] for 2.5 seconds. If an ability was [BROWN]Interrupted[], applies [YELLOW]Silence[] for 1 second.\n\n[BROWN]Interrupt[]: Prevents the current casting spell from being performed and locks CHAMPION_MasterOfTheSword for a short period WIZARD_MagicMissiles time if the spell has a cooldown.\n\n[RED]Astral Shock[]: Reduces Power, Armor, Magic Resist, and Movement Speed by 8%. Deals [ORANGE]%d[] magic damage every second.\n\n[YELLOW]Silence[]: Prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("mystic/Blackout", "[WHITE]Deals [ORANGE]%d[] magic damage and applies [RED]Amnesia[] for 4 seconds and [YELLOW]Fear[] for 2.0 seconds to all enemies within 25 yards WIZARD_MagicMissiles you.\n\n[RED]Amnesia[]: Reduces Power by 12%.\n\n[YELLOW]Fear[]: Causes you RunicShieldEnchantment run CHAMPION_CrushingBlow a random direction and prevents the use WIZARD_MagicMissiles abilities. Breaks upon receiving damage equal to 6% WIZARD_MagicMissiles your maximum health.");
    DESC.put("mystic/BlessingSunAndMoon", "[WHITE]Applies [GREEN]Blessing WIZARD_MagicMissiles the Sun and Moon[] RunicShieldEnchantment target ally for 8 seconds.\n\n[GREEN]Blessing WIZARD_MagicMissiles the Sun and Moon[]: Heals [ORANGE]%d[] every second and reduces all damage taken by 15%.");
    DESC.put("mystic/BlindingGlare", "[WHITE]Deals [ORANGE]%d[] magic damage and applies [YELLOW]Shock[] for 1 second RunicShieldEnchantment target enemy.\n\n[YELLOW]Shock[]: Amplifies all damage received by 12%.");
    DESC.put("mystic/Cleanse", "[WHITE]Cleanse up to 3 total [YELLOW]Status Ailments[] and/or [RED]Debuffs[] from target ally. For each effect cleansed that ally CHAMPION_Lacerate healed for [ORANGE]%d[]. ");
    DESC.put("mystic/CosmicInfusion", "[WHITE]Applies [GREEN]Cosmic Infusion[] RunicShieldEnchantment target ally for 7 seconds. [GOLD]Ignores global cooldown[].\n\n[GREEN]Cosmic Infusion[]: Increases Magic Damage and Healing done by 12%.");
    DESC.put("mystic/Disenchant", "[WHITE]After a short delay, hard dispels the most recently applied [RED]Debuff[] from allies and the most recently applied [GREEN]Buff[] from enemies within 25 yards WIZARD_MagicMissiles your cursor's location. Returns 20 Mana RunicShieldEnchantment you for each enemy [GREEN]Buff[] removed.");
    DESC.put("mystic/HealingVision", "[WHITE]Heal target ally for [ORANGE]%d[] and you for [ORANGE]%d[].");
    DESC.put("mystic/LifeStream", "[WHITE]Applies [GREEN]Life Stream[] RunicShieldEnchantment target ally for 30 seconds. [GOLD]Ignores global cooldown[].\n\n[GREEN]Life Stream[]: 20% of all damage and 10% of all healing done by you also heals the [GREEN]Life Stream[] target. [RED]You can only have one Life Stream active.[]");
    DESC.put("mystic/LightsWrath", "[WHITE]Deals [ORANGE]%d[] magic damage and applies [YELLOW]Shock[] for 1 second RunicShieldEnchantment target enemy.\n\n[YELLOW]Shock[]: Amplifies all damage received by 12%.");
    DESC.put("mystic/ManaTap", "[WHITE]Deals [ORANGE]%d[] magic damage plus an additional 5% WIZARD_MagicMissiles target's current [SKY]Resource[] value. Burns [ORANGE]%d[] [SKY]Mana[] plus an additional 5% WIZARD_MagicMissiles target's current [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] or [SKY]Rage[]).");
    DESC.put("mystic/TemporalBarrier", "[WHITE]Applies [GREEN]Temporal Barrier[] RunicShieldEnchantment target ally for 7 seconds. When [GREEN]Temporal Barrier[] expires, heal that ally for [ORANGE]%d[]. If [GREEN]Temporal Barrier[] depletes from absorbing damage, you are refunded 115 [SKY]Mana[] and applies [RED]Slow Time[] RunicShieldEnchantment enemies within 22 yards for 2 seconds.\n\n[GREEN]Temporal Barrier[]: Absorbs [ORANGE]%d[] damage and increases Movement Speed by 15%.\n\n[RED]Slow Time[]: Slows movement speed by 8%.");
    DESC.put("mystic/skill_276", "[WHITE]Applies [GREEN]Cosmic Infusion[] RunicShieldEnchantment target ally for 7 seconds. [GOLD]Ignores global cooldown[].\n\n[GREEN]Cosmic Infusion[]: Increases Magic Damage and Healing done by 12%.");
    DESC.put("nihilist/Amalgamation", "[WHITE][TEAL]Aura[]: Passively applies [RED]Amalgamation[] to all enemies within 40 yards.\n\nSteals 1% WIZARD_MagicMissiles health every other second. Steals an additional .5% health for every 25% WIZARD_MagicMissiles maximum health the Nihilist CHAMPION_Lacerate missing.");
    DESC.put("nihilist/Blink", "[WHITE]Teleport RunicShieldEnchantment your cursor's location dealing [ORANGE]%d[] magic damage to all enemies within 12 yards. [RED]Deals 900 magic damage RunicShieldEnchantment the Nihilist when cast[].");
    DESC.put("nihilist/ChaosWave", "[WHITE]Shoots a projectile at target enemy dealing [ORANGE]%d[]-[ORANGE]%d[] magic damage and applies [YELLOW]Fear[] for 1.8 seconds WIZARD_VolcanicEruption impact. You gain Life equal to 100% WIZARD_MagicMissiles the damage dealt.\n\n[YELLOW]Fear[]: Causes you RunicShieldEnchantment run CHAMPION_CrushingBlow a random direction and prevents the use WIZARD_MagicMissiles abilities. Breaks upon receiving damage equal to 6% WIZARD_MagicMissiles your maximum health.");
    DESC.put("nihilist/Infuse", "[WHITE]Heals target ally for [ORANGE]%d[] plus an additional 20% for each alive [VIOLET]Orb[]. Bonus healing effectiveness CHAMPION_Lacerate reduced by 4% for each additional [VIOLET]Orb[] you have active. Additionally, provides the following bonuses RunicShieldEnchantment target ally for each [VIOLET]Orb[] currently placed WIZARD_VolcanicEruption the battlefield.\n\n [VIOLET]Orb WIZARD_MagicMissiles Absolution[]: Dispels 1 [RED]Debuff[].\n [VIOLET]Orb WIZARD_MagicMissiles Replenishment[]: Heals for an additional 30%.\n [VIOLET]Orb WIZARD_MagicMissiles Smoke[]: Increases Movement Speed by 15% and Health by 750 for 3 seconds\n [VIOLET]Orb WIZARD_MagicMissiles Wisdom[]: Restores 200 [SKY]Mana[].\n");
    DESC.put("nihilist/Karma", "[WHITE]Applies [RED]Karma[] RunicShieldEnchantment target enemy for 8 seconds.\n\n[RED]Karma[]: Deals [ORANGE]%d[] magic damage every second. Steals [ORANGE]%d[] Life whenever target uses an ability.");
    DESC.put("nihilist/LingeringDemise", "[WHITE]Applies [RED]Lingering Demise[] RunicShieldEnchantment target enemy for 7 seconds.\n\n[RED]Lingering Demise[]: Upon ending, deals [ORANGE]%d[] magic damage. If that enemy was below 20% health, Lingering Demise CHAMPION_Lacerate a guaranteed Critical Strike. Cannot be dispelled.");
    DESC.put("nihilist/MindLeech", "[WHITE]Applies [RED]Mind Leech[] RunicShieldEnchantment target enemy for 8 seconds.\n\n[RED]Mind Leech[]: Deals [ORANGE]%d[] every second, healing the Nihilist's party for 5% WIZARD_MagicMissiles damage dealt. The amount WIZARD_MagicMissiles healing received CHAMPION_Lacerate doubled for the Nihilist. If Mind Leech expires, all party members are healed for [ORANGE]%d[]. If dispelled, deals [ORANGE]%d[] magic damage RunicShieldEnchantment the dispeller.");
    DESC.put("nihilist/OrbOfAbsolution", "[WHITE]Create an [VIOLET]Orb WIZARD_MagicMissiles Absolution[] at your cursor's location for 3 seconds.\n\n[VIOLET]Orb WIZARD_MagicMissiles Absolution[]: While not in [GREEN]Dark Inoculation[], dispel the most recently applied [RED]Debuff[] or [YELLOW]Status Ailment[] when created. Afterwards, dispel every second from allies within 35 yards. Heals that ally for [ORANGE]%d[] whenever they are cleansed. [VIOLET]Orb WIZARD_MagicMissiles Absolution[] has [ORANGE]1[] health and can be targeted. [RED]Your party can only have one[] [VIOLET]Orb WIZARD_MagicMissiles Absolution[] [RED]active at a time.[]");
    DESC.put("nihilist/OrbOfReplenishment", "[WHITE]Create an [VIOLET]Orb WIZARD_MagicMissiles Replenishment[] at your cursor's location for 8 seconds.\n\n[VIOLET]Orb WIZARD_MagicMissiles Replenishment[]: Heals for [ORANGE]%d[] when created and every second thereafter RunicShieldEnchantment allies within 50 yards. [VIOLET]Orb WIZARD_MagicMissiles Replenishment[] has [ORANGE]1[] health and can be targeted. [RED]Your party can only have one[] [VIOLET]Orb WIZARD_MagicMissiles Replenishment[] [RED]active at a time.[]");
    DESC.put("nihilist/OrbOfSmoke", "[WHITE]Create an [VIOLET]Orb WIZARD_MagicMissiles Smoke[] at your cursor's location for 8 seconds.\n\n[VIOLET]Orb WIZARD_MagicMissiles Smoke[]: Reduces damage taken by 8% and increases Power by 35, Critical Strike by 6%, and 3% [PURPLE]Lifesteal[] to all allies within 50 yards. [VIOLET]Orb WIZARD_MagicMissiles Smoke[] has [ORANGE]1[] Health and can be targeted. [RED]Your party can only have one[] [VIOLET]Orb WIZARD_MagicMissiles Smoke[] [RED]active at a time.[]\n\n[PURPLE]Lifesteal[]: Gain Health equal RunicShieldEnchantment a percentage WIZARD_MagicMissiles damage dealt from any source.");
    DESC.put("nihilist/OrbOfWisdom", "[WHITE]Create an [VIOLET]Orb WIZARD_MagicMissiles Wisdom[] at target location for 4 seconds.\n\n[VIOLET]Orb WIZARD_MagicMissiles Wisdom[]: Restores 75 [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] or [SKY]Rage[]) when created and every second thereafter to all allies within 50 yards. Amount of [SKY]Mana[] restored increases by 15 every second. [VIOLET]Orb WIZARD_MagicMissiles Wisdom[] has [ORANGE]1[] Health and can be targeted. [RED]Your party can only have one[] [VIOLET]Orb WIZARD_MagicMissiles Wisdom[] [RED]active at a time.[]");
    DESC.put("nihilist/Rockslide", "[WHITE]Creates a [VIOLET]Rockslide[] at your cursor's location.\n\n[VIOLET]Rockslide[]: Deals [ORANGE]%d[] magic damage and applies [YELLOW]Stun[] for 1 second to all enemies within 20 yards.\n\n[YELLOW]Stun[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("nihilist/ShadowAffinity", "[WHITE]Heal target ally for [ORANGE]%d[] and applies [GREEN]Shadow Affinity[] for 6 seconds.\n\n[GREEN]Shadow Affinity[]: Provides 8% [PURPLE]Lifesteal[].\n\n[PURPLE]Lifesteal[]: Gain Health equal RunicShieldEnchantment a percentage WIZARD_MagicMissiles damage dealt from any source.");
    DESC.put("nihilist/SiphonMana", "[WHITE]Applies [RED]Siphon Mana[] RunicShieldEnchantment target enemy for 7 seconds.\n\n[RED]Siphon Mana[]: Burns 1.25% WIZARD_MagicMissiles current [SKY]Mana[] every second (95% reduced effectiveness for [SKY]Energy[] or [SKY]Rage[]), dealing damage equal to 400% WIZARD_MagicMissiles the amount burned. Ally hits have [PURPLE]{Mana Rift}[].\n\n[PURPLE]{Mana Rift}[]: Steal [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] or [SKY]Rage[]) and deal additional damage equal to [PURPLE]3%[] WIZARD_MagicMissiles damage dealt.");
    DESC.put("nihilist/SpellBreaker", "[WHITE]Applies [GREEN]Spell Breaker[] RunicShieldEnchantment target ally for 5 seconds.\n\n[GREEN]Spell Breaker[]: Absorbs [ORANGE]%d[] damage (reduced by 30% while in [GREEN]Dark Inoculation[]). Upon absorbing damage, heal for 50% WIZARD_MagicMissiles the absorbed amount.");
    DESC.put("paladin/AngelicStrike", "[WHITE]Deals [ORANGE]%d[] physical damage. Has a 35% chance RunicShieldEnchantment trigger [GOLD]Angelic Favor[].\n\n[GOLD]Angelic Favor[]: Causes one WIZARD_MagicMissiles the events RunicShieldEnchantment occur:\n[GOLD]Justice:[] Applies a 0.8 second [YELLOW]Stun[] RunicShieldEnchantment target enemy.\n[GOLD]Prayer:[] Heals you for 8% WIZARD_MagicMissiles your maximum health.\n[GOLD]Insight:[] Restores 2% WIZARD_MagicMissiles missing [SKY]Mana[].\n[GOLD]Fanatacism:[] Deals 515 bonus true damage RunicShieldEnchantment target enemy.");
    DESC.put("paladin/BlazingSlash", "[WHITE]Deals [ORANGE]%d[] physical damage and applies [YELLOW]Burning[] for 2 seconds to all enemies within 20 yards.\n\n[YELLOW]Burning[]: Deals 3.25% WIZARD_MagicMissiles maximum health every second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.");
    DESC.put("paladin/CelestialProtection", "[WHITE]Applies [GREEN]Heavens Guidance[] RunicShieldEnchantment you for 2 minutes.\n\n[GREEN]Heavens Guidance[]: Increases your Healing Power by 45% and restores 8 [SKY]Mana[] every second. Causes your Basic Attacks RunicShieldEnchantment restore 2% WIZARD_MagicMissiles your Party's missing health. [RED]Reduces damage dealt by 30%.[]\n\n[RED]You can only have one Seal active at a time.[] Your seal cannot be dispelled.");
    DESC.put("paladin/CrusadersFury", "[WHITE]Applies [GREEN]Crusader's Fury[] RunicShieldEnchantment you for 2 minutes.\n\n[GREEN]Crusader's Fury[]: Your damaging abilities deal an additional [ORANGE]120[] magic damage, restore 1% WIZARD_MagicMissiles your missing [SKY]Mana[], and have a 20% chance RunicShieldEnchantment cause Crusader's Fury RunicShieldEnchantment deal double damage. For each different damaging ability used, the effectiveness increases by 4% (maximum 20%). [RED]Reduces healing done by 30%.[]\n\n[RED]You can only have one Seal active at a time.[] Your seal cannot be dispelled.");
    DESC.put("paladin/HeavensGuidance", "[WHITE]Applies [GREEN]Heavens Guidance[] RunicShieldEnchantment you for 2 minutes.\n\n[GREEN]Heavens Guidance[]: Increases your Healing Power by 45% and restores 8 [SKY]Mana[] every second. Causes your Basic Attacks RunicShieldEnchantment restore 2% WIZARD_MagicMissiles your Party's missing health. [RED]Reduces damage dealt by 30%.[]\n\n[RED]You can only have one Seal active at a time.[] Your seal cannot be dispelled.");
    DESC.put("paladin/HeavensStrike", "[WHITE]Deals [ORANGE]%d[] magic damage RunicShieldEnchantment target enemy and applies [YELLOW]Shock[] for 2 seconds and [YELLOW]Stun[] for 1.5 seconds.\n\n[YELLOW]Shock[]: Amplifies all damage received by 12%.\n\n[YELLOW]Stun[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("paladin/HolyNova", "[WHITE]Deals [ORANGE]%d[] magic damage and applies [YELLOW]Burning[] for 2 seconds to all enemies within 40 yards. Heals [ORANGE]%d[] and applies [GREEN]Grace[] for 3 seconds to all allies within 40 yards.\n\n [GREEN]Seal WIZARD_MagicMissiles the Crusader Bonus:[] Applies [YELLOW]Blind[] for 1 second.\n [GREEN]Seal WIZARD_MagicMissiles the Heavens Bonus:[] Restores 350 [SKY]Mana[] for each ally hit.\n\n[YELLOW]Burning[]: Deals 3.25% WIZARD_MagicMissiles maximum health every second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.\n\n[GREEN]Grace[]: Heals [ORANGE]%d[] every second.");
    DESC.put("paladin/Immortality", "[WHITE]Applies [GREEN]Immortality[] for 4 seconds and [RED]Ethereal[] for 60 seconds RunicShieldEnchantment target ally. [GOLD]Ignores global cooldown[].\n\n[GREEN]Immortality[]: Provides [GOLD]Immunity[] to all forms WIZARD_MagicMissiles damage, [RED]Debuffs[] and [YELLOW]Status Ailments[].\n\n[RED]Ethereal[]: Cannot be the target WIZARD_MagicMissiles Immortality. Cannot be dispelled.");
    DESC.put("paladin/InfernalStrike", "[WHITE]Deals [ORANGE]%d[] magic damage and applies [RED]Sear[] for 4 seconds. If target is [YELLOW]Burning[], dealing an additional [ORANGE]%d[] magic damage for each second remaining WIZARD_VolcanicEruption the [YELLOW]Burning[] duration. [GOLD]Ignores global cooldown[].\n\n[RED]Sear[]: Increases damage taken from [YELLOW]Burning[] by 20% and decreases Movement Speed by 20%.\n\n[YELLOW]Burning[]: Deals 3.25% WIZARD_MagicMissiles maximum health every second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.");
    DESC.put("paladin/Prudence", "[WHITE]Deals [ORANGE]%d[] magic damage RunicShieldEnchantment target enemy and applies [RED]Prudence[] for 7 seconds.\n\n [GREEN]Seal WIZARD_MagicMissiles the Crusader Bonus:[] Applies [YELLOW]Incapacitate[] for 1 second.\n [GREEN]Seal WIZARD_MagicMissiles the Heavens Bonus:[] Restores 300 [SKY]Mana[].\n\n[RED]Prudence[]: Restore [SKY]Mana[] equal to 15% WIZARD_MagicMissiles damage dealt when dealing damage RunicShieldEnchantment a player suffering from [RED]Prudence[]. Ends after restoring 350 [SKY]Mana[].");
    DESC.put("paladin/Purify", "[WHITE]Cleanses the most recently applied [YELLOW]Status Ailment[] and [RED]Debuff[] from target ally and heals [ORANGE]%d[] for each effect cleansed.\n\n [GREEN]Seal WIZARD_MagicMissiles the Heavens Bonus:[] Cleanses an additional negative effect.");
    DESC.put("paladin/RiteOfPassage", "[WHITE]Applies [GREEN]Rite WIZARD_MagicMissiles Passage[] RunicShieldEnchantment target ally for 5 seconds.\n\n[GREEN]Rite WIZARD_MagicMissiles Passage[]: Increases Movement Speed by 15%. Provides [GOLD]Immunity[] to all root and slowing [RED]Debuffs[]. Heals for [ORANGE]%d[] every second.");
    DESC.put("paladin/Sear", "[WHITE]Deals [ORANGE]%d[] magic damage and applies [RED]Sear[] for 4 seconds. If target is [YELLOW]Burning[], dealing an additional [ORANGE]%d[] magic damage for each second remaining WIZARD_VolcanicEruption the [YELLOW]Burning[] duration. [GOLD]Ignores global cooldown[].\n\n[RED]Sear[]: Increases damage taken from [YELLOW]Burning[] by 20% and decreases Movement Speed by 20%.\n\n[YELLOW]Burning[]: Deals 3.25% WIZARD_MagicMissiles maximum health every second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.");
    DESC.put("paladin/ShatteringSlash", "[WHITE]Deals [ORANGE]%d[] physical damage RunicShieldEnchantment target enemy and removes their most recently applied [GREEN]Buff[]. If a [GREEN]Buff[] was removed, deals an additional [ORANGE]476[] true damage");
    DESC.put("paladin/StreamOfLight", "[WHITE]Shoots a projectile at target ally healing for [ORANGE]%d[] and applies [GREEN]Grace[] for 3 seconds. Heals an additional [ORANGE]%d[] if that ally already had [GREEN]Grace[].\n\n[GREEN]Grace[]: Heals [ORANGE]%d[] every second.");
    DESC.put("paladin/Valor", "[WHITE]Applies [GREEN]Valor[] RunicShieldEnchantment you with [GOLD]9 Charges[] for 8 seconds.\n\n[GREEN]Valor[]: Provides [GOLD]Immunity[] to [YELLOW]Silence[] and [BROWN]Interrupts[]. Increases Armor and Magic Resist by [ORANGE]%d[]. [RED]Loses a [GOLD]Charge[] upon receiving 500 damage. Valor ends when out of [GOLD]Charges[].[WHITE] \n\n[YELLOW]Silence[]: Prevents the use WIZARD_MagicMissiles abilities.\n\n[BROWN]Interrupt[]: Prevents the current casting spell from being performed and locks CHAMPION_MasterOfTheSword for a short period WIZARD_MagicMissiles time if the spell has a cooldown.");
    DESC.put("paladin/WrathOfHeaven", "[WHITE]Deals [ORANGE]%d[] magic damage and applies [YELLOW]Blind[] for 1.3 seconds RunicShieldEnchantment target enemy and all enemies within 12 yards.\n\n[YELLOW]Blind[]: Reduces Power by 12%.");
    DESC.put("ranger/AetherShot", "[WHITE]Shoots an arrow at target enemy dealing [ORANGE]%d[] magic damage WIZARD_VolcanicEruption impact and applies [RED]Aether Shot[] for 6 seconds.\n\n[RED]Aether Shot[]: Burns 25 [SKY]Mana[] plus an additional 1% WIZARD_MagicMissiles current [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] or [SKY]Rage[]) every second. Deals [ORANGE]%d[] magic damage and burns 30 [SKY]Mana[] whenever an ability CHAMPION_Lacerate used.");
    DESC.put("ranger/ElementalArrow", "[WHITE]Shoots an arrow at target enemy dealing [ORANGE]%d[] magic damage, applies [YELLOW]Burning[] and [RED]Chill[] for 2 seconds, and [RED]Freeze[] for 1 second RunicShieldEnchantment target enemy.\n\n[YELLOW]Burning[]: Deals 3.25% WIZARD_MagicMissiles maximum health every second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.\n\n[RED]Chill[]: Decreases Movement Speed by 30%.\n\n[RED]Freeze[]: Decreases Movement Speed to 0%. Breaks upon receiving damage equal to 20% WIZARD_MagicMissiles your maximum health.");
    DESC.put("ranger/HeadShot", "[WHITE]Shoots an arrow at target enemy dealing [ORANGE]%d[] physical damage, applying [YELLOW]Bleeding[] and [YELLOW]Hobble[] for 2 seconds and [YELLOW]Stun[] for 1.25 seconds.\n\n[YELLOW]Bleeding[]: Deals 1.85% WIZARD_MagicMissiles maximum health every second as true damage. Deals 1% WIZARD_MagicMissiles maximum health whenever an ability CHAMPION_Lacerate used.\n\n[YELLOW]Hobble:[] Decreases Movement Speed by 60% and increases physical damage taken by 3%.\n\n[YELLOW]Stun[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("ranger/HobblingArrow", "[WHITE]Shoots an arrow at target enemy dealing [ORANGE]%d[] physical damage WIZARD_VolcanicEruption impact, applying [RED]Pierce[] for 3 seconds.\n\n[RED]Pierce[]: Causes the next instance WIZARD_MagicMissiles physical damage RunicShieldEnchantment deal an additional [ORANGE]%d[].");
    DESC.put("ranger/LightningArrow", "[WHITE]Shoots an arrow at target enemy dealing [ORANGE]%d[] magic damage WIZARD_VolcanicEruption impact, removing the most recently applied [GREEN]Buff[] and applies [YELLOW]Shock[] for 3 seconds.\n\n[YELLOW]Shock[]: Amplifies all damage received by 12%.");
    DESC.put("ranger/MarkOfDeath", "[WHITE][TEAL]Aura[]: Passively permanently applies [RED]Mark WIZARD_MagicMissiles Death[] to all enemies within 100 yards that are below 50% Health.\n\n[RED]Mark WIZARD_MagicMissiles Death[]: You are being hunted! Being vulnerable causes you to RunicShieldEnchantment receive 5% increased damage from all sources. This effect CHAMPION_Lacerate doubled when under 25% Health and tripled when under 10% Health.");
    DESC.put("ranger/NightmareShot", "[WHITE]Shoots an arrow at target enemy dealing [ORANGE]%d[] physical damage WIZARD_VolcanicEruption impact and applies [YELLOW]Fear[] for 1.6 seconds.\n\n[YELLOW]Fear[]: Causes you RunicShieldEnchantment run CHAMPION_CrushingBlow a random direction and prevents the use WIZARD_MagicMissiles abilities. Breaks upon receiving damage equal to 6% WIZARD_MagicMissiles your maximum health.");
    DESC.put("ranger/PoisonousShot", "[WHITE]Shoots an arrow at target enemy dealing [ORANGE]%d[] physical damage WIZARD_VolcanicEruption impact and applies [YELLOW]Infection[] and [YELLOW]Poison[] for 3 seconds.\n\n[YELLOW]Infection[]: Reduces maximum health by 10%, all healing received by 30% and deals 1% WIZARD_MagicMissiles maximum health every second as physical damage.\n\n[YELLOW]Poison[]: Decreases Movement Speed by 15% and deals 2% WIZARD_MagicMissiles maximum health every second as true damage. Cannot be removed as a slowing effect.");
    DESC.put("ranger/RainOfArrows", "[WHITE]Creates [VIOLET]Rain WIZARD_MagicMissiles Arrows[] at your cursor's location for 2 seconds.\n\n[VIOLET]Rain WIZARD_MagicMissiles Arrows[]: Critically deals [ORANGE]%d[] physical damage.");
    DESC.put("ranger/RejuvenationPotion", "[WHITE]Heals target ally for [ORANGE]%d[] and restores 400 [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] and [SKY]Rage[]) and applies [GREEN]Rejuvenation Potion[] for 3 seconds. Can be used while moving.\n\n[GREEN]Rejuvenation Potion[]: Heals for [ORANGE]%d[] every second, and restores 75 [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] and [SKY]Rage[]) every second.");
    DESC.put("ranger/RejuvinationPotion", "[WHITE]Heals target ally for [ORANGE]%d[] and restores 400 [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] and [SKY]Rage[]) and applies [GREEN]Rejuvenation Potion[] for 3 seconds. Can be used while moving.\n\n[GREEN]Rejuvenation Potion[]: Heals for [ORANGE]%d[] every second, and restores 75 [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] and [SKY]Rage[]) every second.");
    DESC.put("ranger/SilencingShot", "[WHITE]Shoots an arrow at target enemy dealing [ORANGE]%d[] physical damage RunicShieldEnchantment target and [BROWN]Interrupts[] for 3 seconds. If an ability was [BROWN]Interrupted[], applies [RED]Silence[] for 1.5 seconds and deals an additional [ORANGE]%d[] physical damage. [GOLD]Ignores global cooldown[].\n\n[BROWN]Interrupt[]: Prevents the current casting spell from being performed and locks CHAMPION_MasterOfTheSword for a short period WIZARD_MagicMissiles time if the spell has a cooldown.\n\n[YELLOW]Silence[]: Prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("ranger/Vigor", "[WHITE]Removes all movement impairing [RED]Debuffs[], and applies [GREEN]Vigor[] RunicShieldEnchantment you for 1 second. Using an attack skill breaks [GREEN]Vigor[]\n\n[GREEN]Vigor[]: You are invisible, immune to all forms WIZARD_MagicMissiles Crowd Control and damage. Movement Speed CHAMPION_Lacerate increased by 25%.");
    DESC.put("scholar/Armageddon", "[WHITE]Creates a fiery [VIOLET]Armageddon[] at your cursor's location for 4 seconds.\n\n[VIOLET]Armageddon[]: Deals [ORANGE]%d[] magic damage every second and applies [YELLOW]Burning[] for 2 seconds to all enemies within 27 yards.\n\n[YELLOW]Burning[]: Deals 3.25% WIZARD_MagicMissiles maximum health every second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.");
    DESC.put("scholar/EtherealBindings", "[WHITE]Applies [RED]Ethereal Binding[] RunicShieldEnchantment target enemy for 3 seconds.\n\n[RED]Ethereal Bindings[]: Decreases Movement Speed to 0%. Breaks upon receiving damage equal to 30% WIZARD_MagicMissiles your maximum health.");
    DESC.put("scholar/Immortality", "[WHITE]Applies [GREEN]Immortality[] for 4 seconds and [RED]Ethereal[] for 60 seconds RunicShieldEnchantment target ally. [GOLD]Ignores global cooldown[].\n\n[GREEN]Immortality[]: Provides [GOLD]Immunity[] to all forms WIZARD_MagicMissiles damage, [RED]Debuffs[] and [YELLOW]Status Ailments[].\n\n[RED]Ethereal[]: Cannot be the target WIZARD_MagicMissiles Immortality. Cannot be dispelled.");
    DESC.put("scholar/LifeBurst", "[WHITE]Applies [GREEN]Life Burst[] RunicShieldEnchantment target ally for 8 seconds.\n\n[GREEN]Life Burst[]: Heals [ORANGE]%d[] every second. The next source WIZARD_MagicMissiles damage that would deal over 400 damage is [GOLD]Absorbed[] and instantly heals for [ORANGE]%d[], causing Life Burst RunicShieldEnchantment expire.");
    DESC.put("scholar/Portal", "[WHITE]Swap position with your target. If your target CHAMPION_Lacerate an enemy, [BROWN]Interrupts[] for 2 seconds and applies [RED]Portal[] for 1 second. If your target CHAMPION_Lacerate an ally, you are both healed for [ORANGE]%d[].\n\n[BROWN]Interrupt[]: Prevents the current casting spell from being performed and locks CHAMPION_MasterOfTheSword for a short period WIZARD_MagicMissiles time if the spell has a cooldown.\n\n[RED]Portal[]: Decreases Movement Speed by 66%.");
    DESC.put("scholar/RiteOfPassage", "[WHITE]Applies [GREEN]Rite WIZARD_MagicMissiles Passage[] RunicShieldEnchantment target ally for 5 seconds.\n\n[GREEN]Rite WIZARD_MagicMissiles Passage[]: Increases Movement Speed by 15%. Provides [GOLD]Immunity[] to all root and slowing [RED]Debuffs[]. Heals for [ORANGE]%d[] every second.");
    DESC.put("scholar/Silence", "[WHITE]Applies [YELLOW]Silence[] RunicShieldEnchantment target enemy for 2.5 seconds.\n\n[YELLOW]Silence[]: Prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("scholar/Truth", "[WHITE][TEAL]Aura[]: Passively applies [GREEN]Truth[] to all allies within 80 yards.\n\n[GREEN]Truth[]: Increases Movement Speed by 8% and restores 12 [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] and [SKY]Rage[]) every second. Amount of [SKY]Mana[] restored CHAMPION_Lacerate doubled for the Scholar. Provides a 10% chance RunicShieldEnchantment restore 65 [SKY]Health[] and 40 [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] and [SKY]Rage[]) whenever using an ability.");
    DESC.put("wizard/AganothsDescent", "[WHITE]Calls upon Aganoth RunicShieldEnchantment fly towards target enemy, exploding WIZARD_VolcanicEruption impact RunicShieldEnchantment deal [ORANGE]%d[] magic damage to all enemies within 14 yards WIZARD_MagicMissiles the impact location. Aganoth’s Descent CHAMPION_Lacerate a guaranteed Critical Strike and refunds 50% WIZARD_MagicMissiles the casting cost for each struck enemy that was [YELLOW]Burning[].\n\n[YELLOW]Burning[]: Deals 2.85% WIZARD_MagicMissiles target's health per second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.");
    DESC.put("wizard/Combust", "[WHITE]Deals [ORANGE]%d[] magic damage to all [YELLOW]Burning[] enemies within 16 yards WIZARD_MagicMissiles target enemy. Applies [YELLOW]Burning[] for 2 seconds RunicShieldEnchantment target enemy and all enemies within 14 yards that aren't already [YELLOW]Burning[]. [GOLD]Ignores global cooldown[].\n\n[YELLOW]Burning[]: Deals 2.85% WIZARD_MagicMissiles target's health per second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.");
    DESC.put("wizard/Counterspell", "[WHITE][BROWN]Interrupts[] target enemy for 3 seconds. Applies [YELLOW]Silence[] for 1.5 second. If an ability was [BROWN]Interrupted[], instead applies [YELLOW]Silence[] for 2.5 seconds. [GOLD]Ignores global cooldown[].\n\n[BROWN]Interrupt[]: Prevents the current casting spell from being performed and locks CHAMPION_MasterOfTheSword for a short period WIZARD_MagicMissiles time if the spell has a cooldown.\n\n[YELLOW]Silence[]: Prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("wizard/EyeOfTheStorm", "[WHITE]Creates a violent [VIOLET]Eye Of The Storm[] at your cursor's location for 3 seconds.\n\n[VIOLET]Eye Of The Storm[]: Deals [ORANGE]%d[] magic damage and applies [RED]Chill[] and [YELLOW]Shock[] for 2 seconds when cast and every second thereafter.\n\n[RED]Chill[]: Decreases Movement Speed by 30%.\n\n[YELLOW]Shock[]: Amplifies all damage received by 12%.");
    DESC.put("wizard/Fireball", "[WHITE]Shoots a fiery projectile that explodes at target enemy dealing [ORANGE]%d[] magic damage plus an additional 2.5% damage equal RunicShieldEnchantment the target's maximum health. Applies [YELLOW]Burning[] for 2 seconds WIZARD_VolcanicEruption impact.\n\n[YELLOW]Burning[]: Deals 2.85% WIZARD_MagicMissiles target's health per second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.");
    DESC.put("wizard/FlashFreeze", "[WHITE]Deals [ORANGE]%d[] magic damage and applies [RED]Freeze[] for 3 seconds to all enemies within 35 yards WIZARD_MagicMissiles you.\n\n[RED]Freeze[]: Decreases Movement Speed to 0%. Breaks upon receiving damage equal to 20% WIZARD_MagicMissiles your maximum health.");
    DESC.put("wizard/Frostbolt", "[WHITE]Shoots an icy projectile at target enemy dealing [ORANGE]%d[] magic damage and applies [RED]Chill[] for 2 seconds WIZARD_VolcanicEruption impact. You have a 15% chance to [RED]Freeze[] for 1 second. Deals 50% more damage to [RED]Frozen[] enemies and has an additional 50% chance RunicShieldEnchantment Critically Strike.\n\n[RED]Chill[]: Decreases Movement Speed by 30%.\n\n[RED]Freeze[]: Decreases Movement Speed to 0%. Breaks upon receiving damage equal to 20% WIZARD_MagicMissiles your maximum health.");
    DESC.put("wizard/Geyser", "[WHITE]Creates a [VIOLET]Geyser[] at your cursor's location that erupts instantly.\n\n[VIOLET]Geyser[]: Deals [ORANGE]%d[] magic damage and applies [RED]Chill[] and [RED]Freeze[] for 2 seconds to all enemies within 25 yards. Cleanses [YELLOW]Burning[] from all allies CHAMPION_CrushingBlow the [VIOLET]Geyser[].\n\n[RED]Chill[]: Decreases Movement Speed by 30%.\n\n[RED]Freeze[]: Decreases Movement Speed to 0%. Breaks upon receiving damage equal to 20% WIZARD_MagicMissiles your maximum health.\n\n[YELLOW]Burning[]: Deals 2.85% WIZARD_MagicMissiles target's health per second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.");
    DESC.put("wizard/IceSpikes", "[WHITE]Deals [ORANGE]%d[] magic damage RunicShieldEnchantment target enemy and applies [RED]Hypothermia[] for 3 seconds. If your target is [RED]Frozen[], this spell CHAMPION_Lacerate a guaranteed Critical Strike and applies [YELLOW]Stun[] and [RED]Freeze[] for 1.6 seconds.\n\n[RED]Hypothermia[]: Amplifies all damage taken by 4%, prevents movement, and reduces healing received by 20%. Hypothermia counts as a Chill effect.\n\n[RED]Freeze[]: Decreases Movement Speed to 0%. Breaks upon receiving damage equal to 20% WIZARD_MagicMissiles your maximum health.");
    DESC.put("wizard/LightningStrike", "[WHITE]Deals [ORANGE]%d[] magic damage RunicShieldEnchantment target enemy and applies [YELLOW]Incapacitate[] and [YELLOW]Blind[] for 1.8 seconds.\n\n[YELLOW]Incapacitate[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities. Breaks WIZARD_VolcanicEruption receiving damage.\n\n[YELLOW]Blind[]: Reduces Power by 12%.");
    DESC.put("wizard/MagicMissiles", "[WHITE]Shoots an icy projectile at target enemy dealing [ORANGE]%d[] magic damage WIZARD_VolcanicEruption impact. If the target is [RED]Chilled[], deals double damage. If the target is [RED]Frozen[], deals triple damage.\n\n[RED]Freeze[]: Decreases Movement Speed to 0%. Breaks upon receiving damage equal to 20% WIZARD_MagicMissiles your maximum health.");
    DESC.put("wizard/Meteor", "[WHITE]Calls down a massive [VIOLET]Meteor[] at your cursor's location that lands after 1 second.\n\n[VIOLET]Meteor[]: Critically deals 3% maximum health plus an additional [ORANGE]%d[] physical and [ORANGE]%d[] magical damage. Applies [YELLOW]Stun[] for 1.7 seconds to all enemies within 20 yards.\n\n[YELLOW]Stun[]: Disables movement and prevents the use WIZARD_MagicMissiles abilities.");
    DESC.put("wizard/RunicShield", "[WHITE]Applies [GREEN]Runic Shield[] RunicShieldEnchantment target ally for 5 seconds.\n\n[GREEN]Runic Shield[]: Absorbs [ORANGE]%d[] damage and reduces damage taken by 25%. Restores [ORANGE]%d[] [SKY]Mana[] (95% reduced effectiveness for [SKY]Energy[] and [SKY]Rage[]) every second.");
    DESC.put("wizard/Sheepify", "[WHITE]Applies [RED]Sheepify[] RunicShieldEnchantment target enemy for 3.2 seconds.\n\n[RED]Sheepify[]: Transform into a sheep, decreasing Movement Speed by 20% and causes you RunicShieldEnchantment wander aimlessly, preventing the use WIZARD_MagicMissiles abilities. Breaks upon receiving damage equal to 6% WIZARD_MagicMissiles your maximum health.");
    DESC.put("wizard/ShockNova", "[WHITE]Creates a nova WIZARD_MagicMissiles lightning around you, applying [YELLOW]Shock[] for 2 seconds and dealing [ORANGE]%d[] magic damage to all enemies within 35 yards WIZARD_MagicMissiles you.\n\n[YELLOW]Shock[]: Amplifies all damage received by 12%.");
    DESC.put("wizard/Teleport", "[WHITE]Teleport RunicShieldEnchantment your cursor's location, healing for 837 and applying [GREEN]Teleport[] for 1 seconds.\n\n[GREEN]Teleport[]: Reduces damage taken by 75%.");
    DESC.put("wizard/VolcanicEruption", "[WHITE]Creates an unstable [VIOLET]Volcanic Eruption[] at your cursor's location that erupts every second for 3 seconds.\n\n[VIOLET]Volcanic Eruption[]: Deals [ORANGE]%d[] magic damage to all enemies within 15 yards and applies [YELLOW]Burning[] for 1 second.\n\n[YELLOW]Burning[]: Deals 2.85% WIZARD_MagicMissiles target's health per second as magic damage and increases chance RunicShieldEnchantment be Critically Hit by 5%.");
    META.put("assassin/Annihilate", "Annihilate|0|0|d|45|a");
    META.put("assassin/Bandage", "Bandage|0|6000|d|0|d");
    META.put("assassin/Daze", "Daze|0|20000|d|25|a");
    META.put("assassin/DisappearingAct", "DisappearingAct|0|30000|d|0|d");
    META.put("assassin/Envenom", "skill_249|0|5000|d|20|a");
    META.put("assassin/Puncture", "skill_121|0|0|d|20|a");
    META.put("assassin/ShadowWalk", "ShadowWalk|0|20000|d|15|d");
    META.put("assassin/Slap", "Slap|0|16000|d|20|d");
    META.put("assassin/Slash", "Slash|0|0|d|35|a");
    META.put("assassin/TempleStrike", "TempleStrike|0|13000|d|30|a");
    META.put("assassin/skill_121", "skill_121|0|0|d|20|a");
    META.put("assassin/skill_249", "skill_249|0|5000|d|20|a");
    META.put("champion/ArmorBreak", "DisruptingBlade|0|16000|e|0|a");
    META.put("champion/Charge", "Charge|0|18000|e|0|a");
    META.put("champion/Coward", "Coward|0|40000|e|0|d");
    META.put("champion/CripplingSlash", "CripplingSlash|0|6000|e|0|a");
    META.put("champion/CrushingBlow", "CrushingBlow|0|18000|e|0|a");
    META.put("champion/Decapitate", "Decapitate|0|15000|e|0|a");
    META.put("champion/DisruptingBlade", "DisruptingBlade|0|16000|e|0|a");
    META.put("champion/Enrage", "Enrage|0|40000|e|0|d");
    META.put("champion/Intimidation", "Intimidation|0|0|a|0|b");
    META.put("champion/Lacerate", "Lacerate|0|5000|e|0|a");
    META.put("champion/MasterOfTheSword", "MasterOfTheSword|0|10000|e|0|d");
    META.put("champion/Safeguard", "skill_339|0|20000|e|0|d");
    META.put("champion/SlashingStrike", "SlashingStrike|0|3000|e|0|a");
    META.put("champion/Sprint", "Sprint|0|18000|e|0|d");
    META.put("champion/Whirlwind", "Whirlwind|0|7000|e|0|a");
    META.put("champion/skill_339", "skill_339|0|20000|e|0|d");
    META.put("elder/Bear_Ironhide", "skill_132|0|45000|c|0|a");
    META.put("elder/Bear_Smash", "skill_3|0|25000|e|0|a");
    META.put("elder/CorrosiveAsp", "CorrosiveAsp|750|10000|c|225|d");
    META.put("elder/Inspiration", "Inspiration|0|60000|c|0|d");
    META.put("elder/MendingSpirit", "MendingSpirit|0|0|c|210|d");
    META.put("elder/Ritual", "Ritual|0|0|a|0|b");
    META.put("elder/Serenity", "Serenity|750|10000|c|350|d");
    META.put("elder/Soothe", "Soothe|0|45000|c|280|d");
    META.put("elder/ToxicSpore", "ToxicSpore|0|6000|c|200|d");
    META.put("elder/Windstorm", "Windstorm|1000|16000|c|175|d");
    META.put("elder/skill_132", "skill_132|0|45000|c|0|a");
    META.put("elder/skill_3", "skill_3|0|25000|e|0|a");
    META.put("lich/AbyssalSpike", "AbyssalSpike|0|16000|c|230|d");
    META.put("lich/AcidRain", "AcidRain|750|8000|c|280|d");
    META.put("lich/Contagion", "Contagion|0|0|a|0|b");
    META.put("lich/DeathsGrasp", "DeathsGrasp|0|15000|c|280|d");
    META.put("lich/Depravity", "Depravity|0|14000|c|230|d");
    META.put("lich/Exhaustion", "Exhaustion|0|10000|c|230|d");
    META.put("lich/Inflame", "Inflame|750|0|c|215|d");
    META.put("lich/Miasma", "Miasma|0|4000|c|220|d");
    META.put("lich/NetherBolt", "NetherBolt|1250|7000|c|250|d");
    META.put("lich/Parasite", "Parasite|750|6000|c|235|d");
    META.put("lich/PoolOfSouls", "PoolOfSouls|1000|8000|c|300|d");
    META.put("lich/ShatterMagic", "ShatterMagic|750|18000|c|230|d");
    META.put("lich/Terrify", "Terrify|750|8000|c|190|d");
    META.put("lich/Torment", "Torment|0|0|c|180|d");
    META.put("lich/UnderworldArmor", "UnderworldArmor|0|5000|c|195|d");
    META.put("mystic/Aegis", "Aegis|0|20000|c|260|d");
    META.put("mystic/AstralShock", "AstralShock|0|8000|c|225|d");
    META.put("mystic/Blackout", "Blackout|0|20000|c|190|d");
    META.put("mystic/BlessingSunAndMoon", "BlessingSunAndMoon|0|4000|c|225|d");
    META.put("mystic/BlindingGlare", "BlindingGlare|750|0|c|230|d");
    META.put("mystic/Cleanse", "Cleanse|0|7000|c|230|d");
    META.put("mystic/CosmicInfusion", "skill_276|0|45000|c|0|d");
    META.put("mystic/Disenchant", "Disenchant|500|8000|c|380|d");
    META.put("mystic/HealingVision", "HealingVision|750|0|c|295|d");
    META.put("mystic/LifeStream", "LifeStream|0|30000|c|370|d");
    META.put("mystic/LightsWrath", "BlindingGlare|750|0|c|230|d");
    META.put("mystic/ManaTap", "ManaTap|1000|0|c|180|d");
    META.put("mystic/TemporalBarrier", "TemporalBarrier|0|14000|c|270|d");
    META.put("mystic/skill_276", "skill_276|0|45000|c|0|d");
    META.put("nihilist/Amalgamation", "Amalgamation|0|0|a|0|b");
    META.put("nihilist/Blink", "Blink|0|9000|c|200|d");
    META.put("nihilist/ChaosWave", "ChaosWave|0|22000|c|250|d");
    META.put("nihilist/Infuse", "Infuse|0|3000|c|250|d");
    META.put("nihilist/Karma", "Karma|0|0|c|240|d");
    META.put("nihilist/LingeringDemise", "LingeringDemise|1000|11000|c|295|d");
    META.put("nihilist/MindLeech", "MindLeech|750|0|c|235|d");
    META.put("nihilist/OrbOfAbsolution", "OrbOfAbsolution|0|14000|c|100|d");
    META.put("nihilist/OrbOfReplenishment", "OrbOfReplenishment|0|6000|c|100|d");
    META.put("nihilist/OrbOfSmoke", "OrbOfSmoke|0|8000|c|100|d");
    META.put("nihilist/OrbOfWisdom", "OrbOfWisdom|0|15000|c|50|d");
    META.put("nihilist/Rockslide", "Rockslide|500|14000|c|270|d");
    META.put("nihilist/ShadowAffinity", "ShadowAffinity|750|0|c|265|d");
    META.put("nihilist/SiphonMana", "SiphonMana|0|12000|c|240|d");
    META.put("nihilist/SpellBreaker", "SpellBreaker|0|20000|c|315|d");
    META.put("paladin/AngelicStrike", "AngelicStrike|0|4000|c|235|a");
    META.put("paladin/BlazingSlash", "BlazingSlash|0|4000|c|240|a");
    META.put("paladin/CelestialProtection", "CelestialProtection|0|60000|c|300|d");
    META.put("paladin/CrusadersFury", "HeavensGuidance|0|60000|c|100|d");
    META.put("paladin/HeavensGuidance", "HeavensGuidance|0|60000|c|100|d");
    META.put("paladin/HeavensStrike", "HeavensStrike|0|24000|c|285|d");
    META.put("paladin/HolyNova", "HolyNova|750|45000|c|450|d");
    META.put("paladin/Immortality", "Immortality|0|60000|c|250|d");
    META.put("paladin/InfernalStrike", "InfernalStrike|0|7000|c|270|d");
    META.put("paladin/Prudence", "Prudence|0|16000|c|60|d");
    META.put("paladin/Purify", "Purify|0|6000|c|180|d");
    META.put("paladin/RiteOfPassage", "RiteOfPassage|0|18000|c|135|d");
    META.put("paladin/Sear", "InfernalStrike|0|7000|c|270|d");
    META.put("paladin/ShatteringSlash", "ShatteringSlash|0|9000|c|230|a");
    META.put("paladin/StreamOfLight", "StreamOfLight|0|4000|c|270|d");
    META.put("paladin/Valor", "Valor|0|40000|c|190|d");
    META.put("paladin/WrathOfHeaven", "WrathOfHeaven|0|15000|c|245|d");
    META.put("ranger/AetherShot", "AetherShot|750|9000|d|40|a");
    META.put("ranger/ElementalArrow", "ElementalArrow|0|8000|d|50|a");
    META.put("ranger/HeadShot", "HeadShot|1000|11000|d|65|a");
    META.put("ranger/HobblingArrow", "HobblingArrow|500|3000|d|35|a");
    META.put("ranger/LightningArrow", "LightningArrow|0|12000|d|60|a");
    META.put("ranger/MarkOfDeath", "MarkOfDeath|0|0|a|0|b");
    META.put("ranger/NightmareShot", "NightmareShot|0|22000|d|40|a");
    META.put("ranger/PoisonousShot", "PoisonousShot|0|7000|d|40|a");
    META.put("ranger/RainOfArrows", "RainOfArrows|1000|15000|d|60|a");
    META.put("ranger/RejuvenationPotion", "RejuvenationPotion|500|28000|d|0|d");
    META.put("ranger/RejuvinationPotion", "RejuvenationPotion|500|28000|d|0|d");
    META.put("ranger/SilencingShot", "SilencingShot|0|16000|d|30|a");
    META.put("ranger/Vigor", "Vigor|0|20000|d|0|d");
    META.put("scholar/Armageddon", "Armageddon|1250|15000|c|315|d");
    META.put("scholar/EtherealBindings", "EtherealBindings|0|15000|c|260|d");
    META.put("scholar/Immortality", "Immortality|0|60000|c|250|d");
    META.put("scholar/LifeBurst", "LifeBurst|0|4000|c|265|d");
    META.put("scholar/Portal", "Portal|0|18000|c|300|d");
    META.put("scholar/RiteOfPassage", "RiteOfPassage|0|20000|c|135|d");
    META.put("scholar/Silence", "Silence|0|30000|c|260|d");
    META.put("scholar/Truth", "Truth|0|0|a|0|b");
    META.put("wizard/AganothsDescent", "AganothsDescent|0|5000|c|290|d");
    META.put("wizard/Combust", "Combust|0|3000|c|235|d");
    META.put("wizard/Counterspell", "Counterspell|0|20000|c|210|d");
    META.put("wizard/EyeOfTheStorm", "EyeOfTheStorm|750|16000|c|300|d");
    META.put("wizard/Fireball", "Fireball|1250|0|c|260|d");
    META.put("wizard/FlashFreeze", "FlashFreeze|0|14000|c|240|d");
    META.put("wizard/Frostbolt", "Frostbolt|1000|0|c|200|d");
    META.put("wizard/Geyser", "Geyser|0|20000|c|210|d");
    META.put("wizard/IceSpikes", "IceSpikes|0|20000|c|220|d");
    META.put("wizard/LightningStrike", "LightningStrike|0|15000|c|240|d");
    META.put("wizard/MagicMissiles", "MagicMissiles|0|0|c|240|d");
    META.put("wizard/Meteor", "Meteor|1250|16000|c|300|d");
    META.put("wizard/RunicShield", "RunicShield|0|25000|c|115|d");
    META.put("wizard/Sheepify", "Sheepify|750|12000|c|175|d");
    META.put("wizard/ShockNova", "ShockNova|0|0|c|350|d");
    META.put("wizard/Teleport", "Teleport|0|14000|c|250|d");
    META.put("wizard/VolcanicEruption", "VolcanicEruption|500|10000|c|240|d");
  }

  static {
    VALS.put("assassin/Annihilate", new int[]{444, 222});
    VALS.put("assassin/Bandage", new int[]{507, 105, 26});
    VALS.put("assassin/Daze", new int[]{290});
    VALS.put("assassin/DisappearingAct", new int[]{});
    VALS.put("assassin/Envenom", new int[]{155});
    VALS.put("assassin/Puncture", new int[]{25, 50, 75, 100, 125, 150});
    VALS.put("assassin/ShadowWalk", new int[]{64});
    VALS.put("assassin/Slap", new int[]{177, 177});
    VALS.put("assassin/Slash", new int[]{365, 74, 148, 222, 296, 370});
    VALS.put("assassin/TempleStrike", new int[]{254});
    VALS.put("assassin/skill_121", new int[]{25, 50, 75, 100, 125, 150});
    VALS.put("assassin/skill_249", new int[]{155});
    VALS.put("champion/ArmorBreak", new int[]{221, 198});
    VALS.put("champion/Charge", new int[]{324});
    VALS.put("champion/Coward", new int[]{});
    VALS.put("champion/CripplingSlash", new int[]{212});
    VALS.put("champion/CrushingBlow", new int[]{189});
    VALS.put("champion/Decapitate", new int[]{314});
    VALS.put("champion/DisruptingBlade", new int[]{221, 198});
    VALS.put("champion/Enrage", new int[]{});
    VALS.put("champion/Intimidation", new int[]{});
    VALS.put("champion/Lacerate", new int[]{529});
    VALS.put("champion/MasterOfTheSword", new int[]{});
    VALS.put("champion/Safeguard", new int[]{});
    VALS.put("champion/SlashingStrike", new int[]{295});
    VALS.put("champion/Sprint", new int[]{});
    VALS.put("champion/Whirlwind", new int[]{219});
    VALS.put("champion/skill_339", new int[]{});
    VALS.put("elder/Bear_Ironhide", new int[]{});
    VALS.put("elder/Bear_Smash", new int[]{354});
    VALS.put("elder/CorrosiveAsp", new int[]{521});
    VALS.put("elder/Inspiration", new int[]{});
    VALS.put("elder/MendingSpirit", new int[]{104, 104, 467});
    VALS.put("elder/Ritual", new int[]{});
    VALS.put("elder/Serenity", new int[]{98});
    VALS.put("elder/Soothe", new int[]{438, 81});
    VALS.put("elder/ToxicSpore", new int[]{510});
    VALS.put("elder/Windstorm", new int[]{});
    VALS.put("elder/skill_132", new int[]{});
    VALS.put("elder/skill_3", new int[]{354});
    VALS.put("lich/AbyssalSpike", new int[]{445, 208});
    VALS.put("lich/AcidRain", new int[]{207});
    VALS.put("lich/Contagion", new int[]{});
    VALS.put("lich/DeathsGrasp", new int[]{445});
    VALS.put("lich/Depravity", new int[]{168});
    VALS.put("lich/Exhaustion", new int[]{});
    VALS.put("lich/Inflame", new int[]{284, 76});
    VALS.put("lich/Miasma", new int[]{77, 9});
    VALS.put("lich/NetherBolt", new int[]{766});
    VALS.put("lich/Parasite", new int[]{562});
    VALS.put("lich/PoolOfSouls", new int[]{});
    VALS.put("lich/ShatterMagic", new int[]{249});
    VALS.put("lich/Terrify", new int[]{});
    VALS.put("lich/Torment", new int[]{75});
    VALS.put("lich/UnderworldArmor", new int[]{182});
    VALS.put("mystic/Aegis", new int[]{});
    VALS.put("mystic/AstralShock", new int[]{434, 83});
    VALS.put("mystic/Blackout", new int[]{390});
    VALS.put("mystic/BlessingSunAndMoon", new int[]{187});
    VALS.put("mystic/BlindingGlare", new int[]{498});
    VALS.put("mystic/Cleanse", new int[]{204});
    VALS.put("mystic/CosmicInfusion", new int[]{});
    VALS.put("mystic/Disenchant", new int[]{});
    VALS.put("mystic/HealingVision", new int[]{1073, 188});
    VALS.put("mystic/LifeStream", new int[]{});
    VALS.put("mystic/LightsWrath", new int[]{498});
    VALS.put("mystic/ManaTap", new int[]{379, 58});
    VALS.put("mystic/TemporalBarrier", new int[]{182, 1474});
    VALS.put("mystic/skill_276", new int[]{});
    VALS.put("nihilist/Amalgamation", new int[]{});
    VALS.put("nihilist/Blink", new int[]{349});
    VALS.put("nihilist/ChaosWave", new int[]{365, 730});
    VALS.put("nihilist/Infuse", new int[]{810});
    VALS.put("nihilist/Karma", new int[]{73, 36});
    VALS.put("nihilist/LingeringDemise", new int[]{1064});
    VALS.put("nihilist/MindLeech", new int[]{120, 218, 310});
    VALS.put("nihilist/OrbOfAbsolution", new int[]{195});
    VALS.put("nihilist/OrbOfReplenishment", new int[]{164});
    VALS.put("nihilist/OrbOfSmoke", new int[]{});
    VALS.put("nihilist/OrbOfWisdom", new int[]{});
    VALS.put("nihilist/Rockslide", new int[]{545});
    VALS.put("nihilist/ShadowAffinity", new int[]{1233});
    VALS.put("nihilist/SiphonMana", new int[]{});
    VALS.put("nihilist/SpellBreaker", new int[]{1208});
    VALS.put("paladin/AngelicStrike", new int[]{481});
    VALS.put("paladin/BlazingSlash", new int[]{447});
    VALS.put("paladin/CelestialProtection", new int[]{});
    VALS.put("paladin/CrusadersFury", new int[]{});
    VALS.put("paladin/HeavensGuidance", new int[]{});
    VALS.put("paladin/HeavensStrike", new int[]{434});
    VALS.put("paladin/HolyNova", new int[]{649, 647, 98});
    VALS.put("paladin/Immortality", new int[]{});
    VALS.put("paladin/InfernalStrike", new int[]{255, 101});
    VALS.put("paladin/Prudence", new int[]{474});
    VALS.put("paladin/Purify", new int[]{237});
    VALS.put("paladin/RiteOfPassage", new int[]{152});
    VALS.put("paladin/Sear", new int[]{255, 101});
    VALS.put("paladin/ShatteringSlash", new int[]{497});
    VALS.put("paladin/StreamOfLight", new int[]{689, 365, 98});
    VALS.put("paladin/Valor", new int[]{228});
    VALS.put("paladin/WrathOfHeaven", new int[]{542});
    VALS.put("ranger/AetherShot", new int[]{200, 76});
    VALS.put("ranger/ElementalArrow", new int[]{479});
    VALS.put("ranger/HeadShot", new int[]{588});
    VALS.put("ranger/HobblingArrow", new int[]{523, 164});
    VALS.put("ranger/LightningArrow", new int[]{506});
    VALS.put("ranger/MarkOfDeath", new int[]{});
    VALS.put("ranger/NightmareShot", new int[]{438});
    VALS.put("ranger/PoisonousShot", new int[]{408});
    VALS.put("ranger/RainOfArrows", new int[]{335});
    VALS.put("ranger/RejuvenationPotion", new int[]{998, 105});
    VALS.put("ranger/RejuvinationPotion", new int[]{998, 105});
    VALS.put("ranger/SilencingShot", new int[]{251, 251});
    VALS.put("ranger/Vigor", new int[]{});
    VALS.put("scholar/Armageddon", new int[]{500});
    VALS.put("scholar/EtherealBindings", new int[]{});
    VALS.put("scholar/Immortality", new int[]{});
    VALS.put("scholar/LifeBurst", new int[]{155, 730});
    VALS.put("scholar/Portal", new int[]{532});
    VALS.put("scholar/RiteOfPassage", new int[]{152});
    VALS.put("scholar/Silence", new int[]{});
    VALS.put("scholar/Truth", new int[]{});
    VALS.put("wizard/AganothsDescent", new int[]{481});
    VALS.put("wizard/Combust", new int[]{344});
    VALS.put("wizard/Counterspell", new int[]{});
    VALS.put("wizard/EyeOfTheStorm", new int[]{164});
    VALS.put("wizard/Fireball", new int[]{525});
    VALS.put("wizard/FlashFreeze", new int[]{423});
    VALS.put("wizard/Frostbolt", new int[]{620});
    VALS.put("wizard/Geyser", new int[]{93});
    VALS.put("wizard/IceSpikes", new int[]{416});
    VALS.put("wizard/LightningStrike", new int[]{574});
    VALS.put("wizard/MagicMissiles", new int[]{273});
    VALS.put("wizard/Meteor", new int[]{481, 481});
    VALS.put("wizard/RunicShield", new int[]{1306, 45});
    VALS.put("wizard/Sheepify", new int[]{});
    VALS.put("wizard/ShockNova", new int[]{281});
    VALS.put("wizard/Teleport", new int[]{});
    VALS.put("wizard/VolcanicEruption", new int[]{335});
  }

  /** Resolved %d values at base Power, or null. */

  public static int[] values(String character, String spell) {
    int[] v = VALS.get(character + "/" + spell);
    return v == null ? null : v.clone();
  }

  private SpellDescriptions() {
  }

  /** Raw tooltip literal, or null when absent from decompiled code. */
  public static String description(String character, String spell) {
    return DESC.get(character + "/" + spell);
  }

  /** "displayName|castMs|cooldownMs|resource|cost|uk", or null.
   * uk = spell type from the code (a = weapon ability, d = magic spell,
   * b/c = passive/aura). */
  public static String stats(String character, String spell) {
    return META.get(character + "/" + spell);
  }
}
